### ISSUE TITLE
有时候会会卡住 加个超时多少秒就结束吧

### ISSUE THREAD

**Issue by jonntd** [deanxv/coze-discord-proxy#1]

**Comment by deanxv** [comment]
可以的，明后天有空了会加上，流式返回情况下5s未从discord获取到更新则关闭流。

**Comment by bee10301** [comment]
在stream: false的情况下，似乎不知道何时coze结束，导致一直等待，最后返回504
如果是true的情况能正常接收data，但一样会一直等待，导致不会触发on end

**Comment by deanxv** [comment]
> 在stream: false的情况下，似乎不知道何时coze结束，导致一直等待，最后返回504 如果是true的情况能正常接收data，但一样会一直等待，导致不会触发on end

目前是通过是否携带了嵌入元素来判断是否结束来结束返回，你可以拉取最新的docker镜像再试下？
或者你是不是把coze的Auto-Suggestion关掉了？

**Comment by bee10301** [comment]
> 目前是通过是否携带了嵌入元素来判断是否结束来结束返回，你可以拉取最新的docker镜像再试下？ 或者你是不是把coze的Auto-Suggestion关掉了？

原来如此，确实我是把Auto-Sug关了，感谢回覆。
项目很有趣，感谢分享！

**Comment by deanxv** [comment]
> > 目前是通过是否携带了嵌入元素来判断是否结束来结束返回，你可以拉取最新的docker镜像再试下？ 或者你是不是把coze的Auto-Suggestion关掉了？
> 
> 原来如此，确实我是把Auto-Sug关了，感谢回覆。 项目很有趣，感谢分享！

谢谢支持！

**Comment by deanxv** [comment]
已增加
REQUEST_OUT_TIME:60 [可选]对话接口非流响应下的请求超时时间
STREAM_REQUEST_OUT_TIME:60 [可选]对话接口流响应下的每次流返回超时时间
