### ISSUE TITLE
curl返回的 embedUrls 中的Unicode编码

### ISSUE THREAD

**Issue by wrhsd1** [deanxv/coze-discord-proxy#10]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
大佬
curl 画图 返回的 embedUrls 中的 & 被显示为\u0026 导致图片打不开
手动换回去就好了

**Comment by wrhsd1** [comment]
换用js就好了 
另问一下大佬  新建频道的parentId填什么
总是提示
{"message":"discord创建频道异常","success":false}

**Comment by deanxv** [comment]
> 换用js就好了 另问一下大佬 新建频道的parentId填什么 总是提示 {"message":"discord创建频道异常","success":false}

可选的值 这个要填分类Id 非频道id 分类就是disocrd中的 文字频道、语音频道这种 就是分类

**Comment by wrhsd1** [comment]
明白了 感谢回复

**Comment by deanxv** [comment]
curl 下编码问题 貌似就是这样的 postman或者集成oneapi后都可以正常使用的

**Comment by wrhsd1** [comment]
好的 明白了
