### ISSUE TITLE
在调用api端代码无法改动的情况下，如何设置才能使用多个coze的bot，来进行负载平衡，避免过快出现“You have exceeded the daily limit for sending messages to the bot. Please try again later.”

### ISSUE THREAD

**Issue by GoTop** [deanxv/coze-discord-proxy#100]
使用的是最新版本4.2.3

设置不同的PROXY_SECRET

但是每次调用的时候，只能选择一个proxySecret，就会调用这个proxySecret对应的coze的bot

调用次数多了，就会返回错误
`{"error":{"message":"Request timeout","type":"request_error","param":"","code":"500"}}`

在discord和机器人的对话中，可以看到
`You have exceeded the daily limit for sending messages to the bot. Please try again later.`

这时候修改调用的proxySecret为另一个，则可以继续使用一段时间

请问有什么方法可以在coze-discord-proxy里设置后，让PROXY_SECRET可以和USER_AUTHORIZATION一样，自动进行负载均衡？

**Comment by deanxv** [comment]
出现该报错并非由于coze-bot回答达到上限，而是coze对discord用户做了标识，每个用户目前24小时内对话coze-bot有次数限制，所以项目中才可以配置多个用户user_auth来叠加次数及请求负载。

**Comment by GoTop** [comment]
> 出现该报错并非由于coze-bot回答达到上限，而是coze对discord用户做了标识，每个用户目前24小时内对话coze-bot有次数限制，所以项目中才可以配置多个用户user_auth来叠加次数及请求负载。

嗯，好像确实是coze限制discord bot发消息次数。

不过测试了一下，coze是根据使用的bot使用的模型来限制次数的，如果一个在discord中和一个bot对话，提示超过限制了，如果这时候去coze中更改这个bot所使用的模型，比如从gtp4(8k)替换成gtp4-turbo(128k),这时在discord中就可以正常和这个bot对话了

而且次数限制gtp3.5 > gtp4(8k) > gtp4-turbo(128k)
如果程序可以自动选择不同的coze的bot，就可以使用多一点次数

**Comment by deanxv** [comment]
> > 出现该报错并非由于coze-bot回答达到上限，而是coze对discord用户做了标识，每个用户目前24小时内对话coze-bot有次数限制，所以项目中才可以配置多个用户user_auth来叠加次数及请求负载。
> 
> 嗯，好像确实是coze限制discord bot发消息次数。
> 
> 不过测试了一下，coze是根据使用的bot使用的模型来限制次数的，如果一个在discord中和一个bot对话，提示超过限制了，如果这时候去coze中更改这个bot所使用的模型，比如从gtp4(8k)替换成gtp4-turbo(128k),这时在discord中就可以正常和这个bot对话了
> 
> 而且次数限制gtp3.5 > gtp4(8k) > gtp4-turbo(128k) 如果程序可以自动选择不同的coze的bot，就可以使用多一点次数

<img width="847" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/57529708/919eeba3-b53d-4f37-8808-d4739bb1e641">

**Comment by 14790897** [comment]
一个coze账户多个机器人是共享次数上限的吗？
