### ISSUE TITLE
获取到discord账号的AUTHORIZATION字符串后，需要在网页上保持该账号处于登陆状态吗？可以退出该账号后登陆另一个discord账号吗？

### ISSUE THREAD

**Issue by GoTop** [deanxv/coze-discord-proxy#101]
获取到discord账号的AUTHORIZATION字符串后，需要在网页上保持该账号处于登陆状态吗？

可以退出该账号后登陆另一个discord账号吗？

这样之前获取到的AUTHORIZATION是否仍然有效？

**Comment by deanxv** [comment]
不触发退出登录或者重新登录就可以，登录后可以关闭网站，也可以关闭电脑，保持活跃几乎可以永久有效。

**Comment by deanxv** [comment]
> > 不触发退出登录或者重新登录就可以，登录后可以关闭网站，也可以关闭电脑，保持活跃几乎可以永久有效。
> 
> 
> 
> 那我为了登陆多个discord账号，获取AUTHORIZATION字符串，可以这样操作么？
> 
> 1.在Chrome中打开无痕模式，登陆discord账号1，获取该账号的AUTHORIZATION字符串
> 
> 2.关闭Chrome中无痕模式
> 
> 3.再次在Chrome中打开无痕模式，登陆discord账号2，获取该账号的AUTHORIZATION字符串

可以

**Comment by GoTop** [comment]
> > > 不触发退出登录或者重新登录就可以，登录后可以关闭网站，也可以关闭电脑，保持活跃几乎可以永久有效。
> > 
> > 
> > 那我为了登陆多个discord账号，获取AUTHORIZATION字符串，可以这样操作么？
> > 1.在Chrome中打开无痕模式，登陆discord账号1，获取该账号的AUTHORIZATION字符串
> > 2.关闭Chrome中无痕模式
> > 3.再次在Chrome中打开无痕模式，登陆discord账号2，获取该账号的AUTHORIZATION字符串
> 
> 可以

多谢～～～

还想请教一下，有什么方法可以检测一个AUTHORIZATION的有效性？

因为同时使用好几个AUTHORIZATION，就怕其中有几个失效了又很久没发觉，就浪费账号了

而且从新登陆discord账号获取到的AUTHORIZATION和原来记录的不一样，还不能用这个方法来验证

**Comment by deanxv** [comment]
> > > > 不触发退出登录或者重新登录就可以，登录后可以关闭网站，也可以关闭电脑，保持活跃几乎可以永久有效。
> 
> > > 
> 
> > > 
> 
> > > 那我为了登陆多个discord账号，获取AUTHORIZATION字符串，可以这样操作么？
> 
> > > 1.在Chrome中打开无痕模式，登陆discord账号1，获取该账号的AUTHORIZATION字符串
> 
> > > 2.关闭Chrome中无痕模式
> 
> > > 3.再次在Chrome中打开无痕模式，登陆discord账号2，获取该账号的AUTHORIZATION字符串
> 
> > 
> 
> > 可以
> 
> 
> 
> 多谢～～～
> 
> 
> 
> 还想请教一下，有什么方法可以检测一个AUTHORIZATION的有效性？
> 
> 
> 
> 因为同时使用好几个AUTHORIZATION，就怕其中有几个失效了又很久没发觉，就浪费账号了
> 
> 
> 
> 而且从新登陆discord账号获取到的AUTHORIZATION和原来记录的不一样，还不能用这个方法来验证

当user_auth过期或者因为重新登录退出登录失效时，cdp项目会自动切换其他user_auth，所有user_auth失效后请求会抛出异常

**Comment by GoTop** [comment]
> > > > > 不触发退出登录或者重新登录就可以，登录后可以关闭网站，也可以关闭电脑，保持活跃几乎可以永久有效。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 那我为了登陆多个discord账号，获取AUTHORIZATION字符串，可以这样操作么？
> > 
> > 
> > > > 1.在Chrome中打开无痕模式，登陆discord账号1，获取该账号的AUTHORIZATION字符串
> > 
> > 
> > > > 2.关闭Chrome中无痕模式
> > 
> > 
> > > > 3.再次在Chrome中打开无痕模式，登陆discord账号2，获取该账号的AUTHORIZATION字符串
> > 
> > 
> > > 
> > 
> > 
> > > 可以
> > 
> > 
> > 多谢～～～
> > 还想请教一下，有什么方法可以检测一个AUTHORIZATION的有效性？
> > 因为同时使用好几个AUTHORIZATION，就怕其中有几个失效了又很久没发觉，就浪费账号了
> > 而且从新登陆discord账号获取到的AUTHORIZATION和原来记录的不一样，还不能用这个方法来验证
> 
> 当user_auth过期或者因为重新登录退出登录失效时，cdp项目会自动切换其他user_auth，所有user_auth失效后请求会抛出异常

是否考虑“当user_auth过期或者因为重新登录退出登录失效时”，把发生时间和AUTHORIZATION字符串记录到log中，或者显示在docker的运行界面？

这样就可以方便的知道哪个AUTHORIZATION出现问题了

**Comment by deanxv** [comment]
> > 当user_auth过期或者因为重新登录退出登录失效时，cdp项目会自动切换其他user_auth，所有user_auth失效后请求会抛出异常
> 
> 
> 
> 是否考虑“当user_auth过期或者因为重新登录退出登录失效时”，把发生时间和AUTHORIZATION字符串记录到log中，或者显示在docker的运行界面？
> 
> 
> 
> 这样就可以方便的知道哪个AUTHORIZATION出现问题了

很早就实现了

**Comment by GoTop** [comment]
> > > 不触发退出登录或者重新登录就可以，登录后可以关闭网站，也可以关闭电脑，保持活跃几乎可以永久有效。
> > 
> > 
> > 那我为了登陆多个discord账号，获取AUTHORIZATION字符串，可以这样操作么？
> > 1.在Chrome中打开无痕模式，登陆discord账号1，获取该账号的AUTHORIZATION字符串
> > 2.关闭Chrome中无痕模式
> > 3.再次在Chrome中打开无痕模式，登陆discord账号2，获取该账号的AUTHORIZATION字符串
> 
> 可以

请问如果直接使用discord自带的切换账号功能，是否会导致不同账号的AUTHORIZATION失效呢？

**Comment by deanxv** [comment]
> > > > 不触发退出登录或者重新登录就可以，登录后可以关闭网站，也可以关闭电脑，保持活跃几乎可以永久有效。
> 
> > > 
> 
> > > 
> 
> > > 那我为了登陆多个discord账号，获取AUTHORIZATION字符串，可以这样操作么？
> 
> > > 1.在Chrome中打开无痕模式，登陆discord账号1，获取该账号的AUTHORIZATION字符串
> 
> > > 2.关闭Chrome中无痕模式
> 
> > > 3.再次在Chrome中打开无痕模式，登陆discord账号2，获取该账号的AUTHORIZATION字符串
> 
> > 
> 
> > 可以
> 
> 
> 
> 请问如果直接使用discord自带的切换账号功能，是否会导致不同账号的AUTHORIZATION失效呢？

基本不会，这种问题可不可以自行测试呢？已经不是CDP服务本身的问题了，我无法给你明确的解答。

**Comment by GoTop** [comment]
> > > 当user_auth过期或者因为重新登录退出登录失效时，cdp项目会自动切换其他user_auth，所有user_auth失效后请求会抛出异常
> > 
> > 
> > 是否考虑“当user_auth过期或者因为重新登录退出登录失效时”，把发生时间和AUTHORIZATION字符串记录到log中，或者显示在docker的运行界面？
> > 这样就可以方便的知道哪个AUTHORIZATION出现问题了
> 
> 很早就实现了

请问在哪里可以查看？

**Comment by deanxv** [comment]
> > > > 当user_auth过期或者因为重新登录退出登录失效时，cdp项目会自动切换其他user_auth，所有user_auth失效后请求会抛出异常
> > > 
> > > 
> > > 是否考虑“当user_auth过期或者因为重新登录退出登录失效时”，把发生时间和AUTHORIZATION字符串记录到log中，或者显示在docker的运行界面？
> > > 这样就可以方便的知道哪个AUTHORIZATION出现问题了
> > 
> > 
> > 很早就实现了
> 
> 请问在哪里可以查看？

自己尝试使用失效的user_auth启动服务，请求后查看日志

**Comment by Gijela** [comment]
> > 不触发退出登录或者重新登录就可以，登录后可以关闭网站，也可以关闭电脑，保持活跃几乎可以永久有效。
> 
> 那我为了登陆多个discord账号，获取AUTHORIZATION字符串，可以这样操作么？ 1.在Chrome中打开无痕模式，登陆discord账号1，获取该账号的AUTHORIZATION字符串 2.关闭Chrome中无痕模式 3.再次在Chrome中打开无痕模式，登陆discord账号2，获取该账号的AUTHORIZATION字符串

哥们 这个问题后来你怎么解决的 ？无痕模型关闭窗口会退出账户，我看discord服务器上无痕模式登录的账号已经不处于在线状态了

**Comment by CellLz** [comment]
> > > 不触发退出登录或者重新登录就可以，登录后可以关闭网站，也可以关闭电脑，保持活跃几乎可以永久有效。
> > 
> > 
> > 那我为了登陆多个discord账号，获取AUTHORIZATION字符串，可以这样操作么？ 1.在Chrome中打开无痕模式，登陆discord账号1，获取该账号的AUTHORIZATION字符串 2.关闭Chrome中无痕模式 3.再次在Chrome中打开无痕模式，登陆discord账号2，获取该账号的AUTHORIZATION字符串
> 
> 哥们 这个问题后来你怎么解决的 ？无痕模型关闭窗口会退出账户，我看discord服务器上无痕模式登录的账号已经不处于在线状态了

你可以单独创建一个只有这一个authorization的docker-compose项目，然后把discord上登录这个账户网页关掉，再试试api还能不能用。（我的理解是用其他账号看到这个账号从discord上下线了无所谓，当api开始启动以后他会从后台登录这个账号并与coze-bot对话）
