### ISSUE TITLE
无法返回回复

### ISSUE THREAD

**Issue by 6uu1** [deanxv/coze-discord-proxy#102]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
更新4.3.1后 discord里机器人正常回复，但是nextchat里却无法返回，postman里也没有回复返回
**复现步骤**
更新4.3.1后 discord里机器人正常回复，但是nextchat里却无法返回，postman里也没有回复返回

**预期结果**
正常回复

**Comment by deanxv** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/792a68e1-492e-4c2e-b09f-e78a124b35b0)

所有机器人打开以上权限

**Comment by fgjfjfjfteyerifhfj** [comment]
谢谢
