### ISSUE TITLE
还请大佬帮忙，发出去的信息没有回应

### ISSUE THREAD

**Issue by kshz1445433** [deanxv/coze-discord-proxy#104]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
发出去的信息没有回应
**复现步骤**
在NextChat或者Discord发起出去的信信息没有得到回应
**相关截图**
如果没有的话,请删除此节。
<img width="989" alt="222" src="https://github.com/deanxv/coze-discord-proxy/assets/123808254/a1572293-d55a-4400-8255-bb83a9175922">
![111](https://github.com/deanxv/coze-discord-proxy/assets/123808254/2ff4a8bc-dc07-436e-8b74-348028224c26)

**Comment by deanxv** [comment]
检查coze发布的bot在discord中是否在线，不在线的话重新发布。

**Comment by kshz1445433** [comment]
> 检查coze发布的bot在discord中是否在线，不在线的话重新发布。

好的，我现在重新发布一下，谢谢大佬

**Comment by kshz1445433** [comment]
> 检查coze发布的bot在discord中是否在线，不在线的话重新发布。

显示在线，但是我还是重新发布了一下，目前使用正常，万分感谢大佬帮忙
