### ISSUE TITLE
fork仓库最新代码导致该方法报错 [FATAL] 2024/03/07 - 07:54:47 | [Error parsing JSON: json: cannot unmarshal string into Go struct field BotConfig.model of type []string]

### ISSUE THREAD

**Issue by AAlexDing** [deanxv/coze-discord-proxy#106]
**例行检查**

- [x] 我已确认目前没有类似 issue
- [x] 我已确认我已升级到最新版本
- [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
- [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
fork仓库最新代码导致该方法报错 [FATAL] 2024/03/07 - 07:54:47 | [Error parsing JSON: json: cannot unmarshal string into Go struct field BotConfig.model of type []string]

**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
多机器人配置json中的model已改为数组格式，重新参考readme配置。
