### ISSUE TITLE
大佬，这个404是什么意思？

### ISSUE THREAD

**Issue by GforPG** [deanxv/coze-discord-proxy#107]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

![1](https://github.com/deanxv/coze-discord-proxy/assets/138672705/6fae26ed-349d-4ad5-bcba-653a65f9264c)
![2](https://github.com/deanxv/coze-discord-proxy/assets/138672705/7489e458-43d6-4342-b90b-bd94fdcd45be)

**Comment by deanxv** [comment]
访问不存在的接口就会404，非异常报错。

**Comment by GforPG** [comment]
需要进行什么操作吗？

**Comment by deanxv** [comment]
> 需要进行什么操作吗？

不需要，部署完之后按照openai的对话接口格式调试就可以。
