### ISSUE TITLE
期望支持图片识别

### ISSUE THREAD

**Issue by yuanwangz** [deanxv/coze-discord-proxy#11]
期望支持openai gpt-4v的图片识别功能，数据结构：{
    "messages": [
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "这个pdf里写了什么，用中文回复"
                },
                {
                    "type": "image_url",
                    "image_url": {
                        "url": "https://bitcoin.org/bitcoin.pdf"
                    }
                }
            ]
        }
    ],
    "stream": false,
    "model": "gpt-4",
    "temperature": 0.5,
    "presence_penalty": 0,
    "frequency_penalty": 0,
    "top_p": 1
}

**Comment by deanxv** [comment]
计划中了。
不过其实已经支持了，把图片url和文本内容都放进msg.content中，也会识图的。

**Comment by deanxv** [comment]
这个数据结构的接口的官方文档可以麻烦提供一下吗

**Comment by deanxv** [comment]
接口已对齐，拉取最新镜像
