### ISSUE TITLE
关于请求访问的格式

### ISSUE THREAD

**Issue by xiaozhang959** [deanxv/coze-discord-proxy#110]
**例行检查**

+ [√] 我已确认目前没有类似 issue
+ [√] 我已确认我已升级到最新版本
+ [√] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [√] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
当自己使用post请求时，可以正常访问和返回，但是当使用next-chat或者别的WEB-UI的时候，一直无法返回信息。查看docker日志，报错如下：
![图片](https://github.com/deanxv/coze-discord-proxy/assets/89305607/864a8741-11fd-4df8-9d0b-84d9a8efadba)

**复现步骤**

使用openai的请求格式就会这样，不清楚是不是next-chat等网站请求时没有加上"channelId"导致的？

**预期结果**
![图片](https://github.com/deanxv/coze-discord-proxy/assets/89305607/87245104-2c44-42d7-8577-11e061265c23)

**相关截图**
![图片](https://github.com/deanxv/coze-discord-proxy/assets/89305607/b31f5f0a-3691-4d09-b1f7-64141db176d5)

如果没有的话,请删除此节。

**Comment by deanxv** [comment]
检查环境变量中的GUILD_ID，此ID为服务器ID，非频道ID。

**Comment by xiaozhang959** [comment]
原来是这样！  可以使用了，太感谢了！
