### ISSUE TITLE
发送消息后无法通过监听bot获取回复消息，总是超时

### ISSUE THREAD

**Issue by HQ-Zhang-233** [deanxv/coze-discord-proxy#111]
**例行检查**

+ [ √] 我已确认目前没有类似 issue
+ [√ ] 我已确认我已升级到最新版本
+ [√ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ √] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
通过zeabur部署，cozebot和监听bot都确认开启了相关权限，通过接口发送信息是正常的，在discord中可以看到通过接口发送的消息和cozebot的回复，但无法通过接口拿到回复信息，总是超时
**复现步骤**
//
**预期结果**

**相关截图**
调用截图：
![image](https://github.com/deanxv/coze-discord-proxy/assets/48396988/c9c1cbad-29f7-4e72-9352-36fc3a8faa09)
bot配置：
![image](https://github.com/deanxv/coze-discord-proxy/assets/48396988/35f09758-fe5c-42c8-93ab-ec42885b9b9f)

如果没有的话,请删除此节。

**Comment by HQ-Zhang-233** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/48396988/edff472c-febd-40cb-9a94-28f0561167b0)

**Comment by deanxv** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/858cbb57-5be0-45f9-ad43-d9e9a532c649)

**Comment by HQ-Zhang-233** [comment]
已解决，感谢大佬666666

**Comment by HQ-Zhang-233** [comment]
棒

**Comment by GoTop** [comment]
> ![image](https://private-user-images.githubusercontent.com/57529708/311595816-858cbb57-5be0-45f9-ad43-d9e9a532c649.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMDYzMzQsIm5iZiI6MTcxMDIwNjAzNCwicGF0aCI6Ii81NzUyOTcwOC8zMTE1OTU4MTYtODU4Y2JiNTctNWJlMC00NWY5LWFkNDMtZDllOWE1MzJjNjQ5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwMTEzNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTMxNzMxOTZiZjlmMmM2NTg5ZWQwYjYxNTYxNTk0OWM4MmE2ZWVhODc1MGYxOWY5ODhhYjViNTY5ZmRkYTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OV74yIKWM5rJ3bjzn3ZUhSvrzu_R4DiKMzr6lxKzE_8)

请问为什么这个选项会影响接口拿到回复信息？

**Comment by deanxv** [comment]
> > ![image](https://private-user-images.githubusercontent.com/57529708/311595816-858cbb57-5be0-45f9-ad43-d9e9a532c649.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMDYzMzQsIm5iZiI6MTcxMDIwNjAzNCwicGF0aCI6Ii81NzUyOTcwOC8zMTE1OTU4MTYtODU4Y2JiNTctNWJlMC00NWY5LWFkNDMtZDllOWE1MzJjNjQ5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwMTEzNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTMxNzMxOTZiZjlmMmM2NTg5ZWQwYjYxNTYxNTk0OWM4MmE2ZWVhODc1MGYxOWY5ODhhYjViNTY5ZmRkYTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OV74yIKWM5rJ3bjzn3ZUhSvrzu_R4DiKMzr6lxKzE_8)
> 
> 
> 
> 请问为什么这个选项会影响接口拿到回复信息？

原理是在监听discord中的消息回复时无法获取到响应结束的标识，当开启这个这个Auto-suggestion时，bot回复结束时会给出这个按钮嵌入，所以就可以通过消息是否含有这个嵌入格式来判断消息是否已结束，返回[DONE]标识

**Comment by GoTop** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/57529708/311595816-858cbb57-5be0-45f9-ad43-d9e9a532c649.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMDYzMzQsIm5iZiI6MTcxMDIwNjAzNCwicGF0aCI6Ii81NzUyOTcwOC8zMTE1OTU4MTYtODU4Y2JiNTctNWJlMC00NWY5LWFkNDMtZDllOWE1MzJjNjQ5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwMTEzNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTMxNzMxOTZiZjlmMmM2NTg5ZWQwYjYxNTYxNTk0OWM4MmE2ZWVhODc1MGYxOWY5ODhhYjViNTY5ZmRkYTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OV74yIKWM5rJ3bjzn3ZUhSvrzu_R4DiKMzr6lxKzE_8)
> > 
> > 
> > 请问为什么这个选项会影响接口拿到回复信息？
> 
> 原理是在监听discord中的消息回复时无法获取到响应结束的标识，当开启这个这个Auto-suggestion时，bot回复结束时会给出这个按钮嵌入，所以就可以通过消息是否含有这个嵌入格式来判断消息是否已结束，返回[DONE]标识

原来如此，我之前还觉得这个要求挺奇怪的，没想到时这样用的
