### ISSUE TITLE
coze里发布到discord，填完token，提示Please check whether the discord bot intents is correct

### ISSUE THREAD

**Issue by younggggger** [deanxv/coze-discord-proxy#112]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
应该是token复制错了，非本项目的问题。

**Comment by younggggger** [comment]
token应该没错的，我把token删掉一个字符，提示Please check whether the token is correct

**Comment by deanxv** [comment]
> token应该没错的，我把token删掉一个字符，提示Please check whether the token is correct

通过coze的相关反馈渠道咨询一下这个问题，非本项目的问题不方便排查。

**Comment by EthanChen8158** [comment]
去BOT里的Privileged Gateway Intents，把全部选项勾上

**Comment by igeekbb** [comment]
> Gateway

感谢，有用！
