### ISSUE TITLE
一直pending中

### ISSUE THREAD

**Issue by younggggger** [deanxv/coze-discord-proxy#113]
我fork了一份，zeabur环境变量也配置好了，在zeabur上部署失败，见图
**例行检查**
![image](https://github.com/deanxv/coze-discord-proxy/assets/127868785/258e59ca-762f-4c9e-8f7f-cac659f1984d)

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
免费试用到期，升级为付费用户(这种非cdp服务的问题下次会直接关闭issue，不予回答)
