### ISSUE TITLE
无法返回信息到前端

### ISSUE THREAD

**Issue by uzengo** [deanxv/coze-discord-proxy#115]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
在discord上部署正常，能正常和coze交互。但是获取不到返回的结果。一直超时。机器部署在zeabur.
无错误日志返回， 就是超时

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/deanxv/coze-discord-proxy/assets/21187455/81bce549-65b4-4784-9f1e-9e5748b33b82)

**Comment by deanxv** [comment]
提issue前请参考其他issue[issue#102](https://github.com/deanxv/coze-discord-proxy/issues/102)

**Comment by uzengo** [comment]
确实是机器人配置少打开了几个开关
