### ISSUE TITLE
Swagger是否能加上PROXY_SECRET请求头

### ISSUE THREAD

**Issue by Jesn** [deanxv/coze-discord-proxy#12]
**问题描述**
    我设置了`PROXY_SECRET`，部署好后想用swagger进行调试，但是在但是没办法添加`PROXY_SECRET`

**相关截图**
![image](https://github.com/deanxv/coze-discord-proxy/assets/5728274/f342841a-9c04-4909-9659-c5f9fe75eae2)

**Comment by deanxv** [comment]
> 
> 
> **问题描述**
> 
>     我设置了`PROXY_SECRET`，部署好后想用swagger进行调试，但是在但是没办法添加`PROXY_SECRET`
> 
> 
> 
> **相关截图**
> 
> ![image](https://github.com/deanxv/coze-discord-proxy/assets/5728274/f342841a-9c04-4909-9659-c5f9fe75eae2)

可以的 你也可以试试postman或者apifox 比swagger在线调试好用多了！

**Comment by deanxv** [comment]
已添加 但golang的swag貌似有bug 带-的字段不会传

**Comment by Jesn** [comment]
目前是在apifox上调试的
