### ISSUE TITLE
discord机器人接收到的内容长度有限，不完整

### ISSUE THREAD

**Issue by HQ-Zhang-233** [deanxv/coze-discord-proxy#121]
**例行检查**

+ [ +] 我已确认目前没有类似 issue
+ [ +] 我已确认我已升级到最新版本
+ [ +] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ +] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
discord机器人生成回复时，所能接收到的内容长度有限，并不能接收到完整的用户提问，导致最终生成的内容不和预期？想要咨询下这个是discord的限制么？还是有其他方式可以扩大长度？
**复现步骤**
用超长的prompt做输入，在discord页面观察机器人回复所引用的原文，发现长度仅有一半左右
![image](https://github.com/deanxv/coze-discord-proxy/assets/48396988/bf9f3c77-ef63-4591-908a-e7426c349061)

**预期结果**
期望bot可以接收到全部的prompt……

**Comment by deanxv** [comment]
不要用这个来判断，实际上所有内容已经被接收到了。

因为消息过长，所以服务会分割prompt分段发送消息，bot回复只会选择最新的消息但不代表之前的消息没有读取，频道内的所有对话消息都是bot的上下文的。

**Comment by HQ-Zhang-233** [comment]
哦，原来是这样，我为了防止上下文干扰，特别设置了coze那边仅接收0条上下文……
调整大一点试试，感谢大佬解答~

**Comment by GoTop** [comment]
在discord里，直接@bot发给bot的文字可以超过2000字？

那如果coze返回的文字超过2000字呢?好像2000字往后的文字将无法截取掉，无法收到

**Comment by deanxv** [comment]
> 在discord里，直接@bot发给bot的文字可以超过2000字？
> 
> 
> 
> 那如果coze返回的文字超过2000字呢?好像2000字往后的文字将无法截取掉，无法收到

Bot的单条回复是无法超过两千字的，但大多数场景下在bot的回答内容里想要超过2000字时会用省略号结尾，通过发送继续可以让bot继续响应。

![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/71de1492-41f6-4e6e-b1ea-52e31295521f)

**Comment by GoTop** [comment]
> > 在discord里，直接@bot发给bot的文本可以超过2000字？
> > 那如果coze返回的文本超过2000字呢?好像2000字往后的文本将无法截取掉，无法收到
> 
> Bot的单条回复是无法超过两千字的，但大多数场景下在bot的回答内容里想要超过2000字时会用省略号结尾，通过发送继续可以让bot继续响应。
> 
> ![image](https://private-user-images.githubusercontent.com/57529708/314002927-71de1492-41f6-4e6e-b1ea-52e31295521f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTYwOTcsIm5iZiI6MTcxMDg1NTc5NywicGF0aCI6Ii81NzUyOTcwOC8zMTQwMDI5MjctNzFkZTE0OTItNDFmNi00ZTZlLWIxZWEtNTJlMzEyOTU1MjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEzNDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYWM0YjZjNGU3NmEzNTIwOTdhMWVkNTk5MTgxM2RhMzRiZGU2YzZhNmNhYTQ3OWU1NmQ0Yjk4ZDkzOWVjMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0mm-t0Q_qtuRFrhQlxL-eYFB-rNIqP_oJZpojRnHLCs)

如果通过api调用的话，不太好处理这种发送字数超2000的情况吧

**Comment by deanxv** [comment]
> > > 在discord里，直接@bot发给bot的文本可以超过2000字？
> 
> > > 那如果coze返回的文本超过2000字呢?好像2000字往后的文本将无法截取掉，无法收到
> 
> > 
> 
> > Bot的单条回复是无法超过两千字的，但大多数场景下在bot的回答内容里想要超过2000字时会用省略号结尾，通过发送继续可以让bot继续响应。
> 
> > 
> 
> > ![image](https://private-user-images.githubusercontent.com/57529708/314002927-71de1492-41f6-4e6e-b1ea-52e31295521f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTYwOTcsIm5iZiI6MTcxMDg1NTc5NywicGF0aCI6Ii81NzUyOTcwOC8zMTQwMDI5MjctNzFkZTE0OTItNDFmNi00ZTZlLWIxZWEtNTJlMzEyOTU1MjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEzNDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYWM0YjZjNGU3NmEzNTIwOTdhMWVkNTk5MTgxM2RhMzRiZGU2YzZhNmNhYTQ3OWU1NmQ0Yjk4ZDkzOWVjMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0mm-t0Q_qtuRFrhQlxL-eYFB-rNIqP_oJZpojRnHLCs)
> 
> 
> 
> 如果通过api调用的话，不太好处理这种发送字数超2000的情况吧

这种场景下你用官方的api也是一样，总会有个响应的长度上限。

**Comment by Passerby1011** [comment]
> > > > 在discord里，直接@bot发给bot的文本可以超过2000字？
> > 
> > 
> > > > 那如果coze返回的文本超过2000字呢?好像2000字往后的文本将无法截取掉，无法收到
> > 
> > 
> > > 
> > 
> > 
> > > Bot的单条回复是无法超过两千字的，但大多数场景下在bot的回答内容里想要超过2000字时会用省略号结尾，通过发送继续可以让bot继续响应。
> > 
> > 
> > > 
> > 
> > 
> > > ![image](https://private-user-images.githubusercontent.com/57529708/314002927-71de1492-41f6-4e6e-b1ea-52e31295521f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTYwOTcsIm5iZiI6MTcxMDg1NTc5NywicGF0aCI6Ii81NzUyOTcwOC8zMTQwMDI5MjctNzFkZTE0OTItNDFmNi00ZTZlLWIxZWEtNTJlMzEyOTU1MjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEzNDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYWM0YjZjNGU3NmEzNTIwOTdhMWVkNTk5MTgxM2RhMzRiZGU2YzZhNmNhYTQ3OWU1NmQ0Yjk4ZDkzOWVjMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0mm-t0Q_qtuRFrhQlxL-eYFB-rNIqP_oJZpojRnHLCs)
> > 
> > 
> > 如果通过api调用的话，不太好处理这种发送字数超2000的情况吧
> 
> 这种场景下你用官方的api也是一样，总会有个响应的长度上限。

可以使用程序自动继续吗？就和以前的官网逆向一样，由代理代替人去发这个继续
