### ISSUE TITLE
对话结束逻辑

### ISSUE THREAD

**Issue by Gijela** [deanxv/coze-discord-proxy#122]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
每次对话chatgpt回答完问题后，仍需要等待一段时间才结束当次对话，请问一次对话的结束标志是coze给出三条推荐吗？有什么办法在chatgpt回答完问题就结束本次对话吗

**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
目前的判断结束是根据是否出现suggestions判断的，没有其他办法判断。你也可以通过设置环境变量中的超时时间来决定何时结束。

**Comment by CellLz** [comment]
> 目前的判断结束是根据是否出现suggestions判断的，没有其他办法判断。你也可以通过设置环境变量中的超时时间来决定何时结束。

难怪自从我把coze-bot的suggestions关闭以后，每次回答完对话都一直在转圈圈不结束，discord上的临时频道也没有被自动删除
