### ISSUE TITLE
authorization 失效问题

### ISSUE THREAD

**Issue by Gijela** [deanxv/coze-discord-proxy#124]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
昨天设置的 discord authorization 正常工作，今天服务失效了。是 discord authorization 有效期问题吗？discord用户需要保持在线状态吗？
后来重新登陆discord拿了新的authorization部署，服务正常了。请问这种情况怎么解决？难道需要每天都手动更换 authotization 吗？

**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
authorization有效期非常长，除非你自己主动操作了退出登录或者切换账号导致了authorization失效。

**Comment by Gijela** [comment]
> thorization有效期非常长，除非你自己主动操作了退出登录或者切换账号导致了au

再请教下大佬，设置多个discord用户，需要保持每个discord用户都处于在线状态吗？

**Comment by deanxv** [comment]
> > thorization有效期非常长，除非你自己主动操作了退出登录或者切换账号导致了au
> 
> 
> 
> 再请教下大佬，设置多个discord用户，需要保持每个discord用户都处于在线状态吗？

不需要，不要让authorization失效就行。
