### ISSUE TITLE
重复回答

### ISSUE THREAD

**Issue by Passerby1011** [deanxv/coze-discord-proxy#125]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
我在使用有些客户端时会碰到回复三遍的问题，即他把同一份答案回复了三遍：
下面时例子
#
以下是对上述内容的简洁总结：
- 完美适配NextChat，one-api，LobeChat等对话面板。
- 支持对话隔离和流式返回。
- 支持创建discord分类/频道/线程。
- 支持与openai对齐的对话接口(v1/chat/completions)和图生成接口(v1/images/generations)。
- 支持每日9点定时任务自动活跃机器人。
- 支持配置多discord用户Authorization和coze机器人响应负载均衡。
您可以参考接口文档获取更详细的信息。以下是对上述内容的简洁总结：
- 完美适配NextChat，one-api，LobeChat等对话面板。
- 支持对话隔离和流式返回。
- 支持创建discord分类/频道/线程。
- 支持与openai对齐的对话接口(v1/chat/completions)和图生成接口(v1/images/generations)。
- 支持每日9点定时任务自动活跃机器人。
- 支持配置多discord用户Authorization和coze机器人响应负载均衡。
您可以参考接口文档获取更详细的信息。以下是对上述内容的简洁总结：
- 完美适配NextChat，one-api，LobeChat等对话面板。
- 支持对话隔离和流式返回。
- 支持创建discord分类/频道/线程。
- 支持与openai对齐的对话接口(v1/chat/completions)和图生成接口(v1/images/generations)。
- 支持每日9点定时任务自动活跃机器人。
- 支持配置多discord用户Authorization和coze机器人响应负载均衡。
您可以参考接口文档获取更详细的信息。
#
这是我让它总结项目介绍它的回复，在第一段回复结束后它停顿了一会直接蹦出了重复的回答
**复现步骤**
这是我使用的客户端，在这个项目是百分百触发这个问题，其他有些客户端中是偶尔
https://github.com/josStorer/chatGPTBox

**预期结果**
正常回复

**Comment by deanxv** [comment]
提供完整问题

**Comment by Passerby1011** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/63802758/67084100-a2c9-49d5-89bf-02a1ff43e8ff)
截图就是回复本身，你看就会发现答案重复了三次

**Comment by deanxv** [comment]
提问给机器人的问题是什么，我需要本地复现

**Comment by Passerby1011** [comment]
> 提问给机器人的问题是什么，我需要本地复现

随便发什么问题都是三遍，我不确定是你接口的问题还是客户端的问题，有些客户端偶尔会出现这个问题，有的就是百分百触发
这个项目是百分百触发三个回复：https://github.com/josStorer/chatGPTBox

**Comment by deanxv** [comment]
> > 提问给机器人的问题是什么，我需要本地复现
> 
> 
> 
> 随便发什么问题都是三遍，我不确定是你接口的问题还是客户端的问题，有些客户端偶尔会出现这个问题，有的就是百分百触发
> 
> 这个项目是百分百触发三个回复：https://github.com/josStorer/chatGPTBox

可以给出具体示例的问题吗，你这样我没办法通过接口复现。

**Comment by Passerby1011** [comment]
这个问题的触发和客户端有关，只要是那个客户端就是百分百
![image](https://github.com/deanxv/coze-discord-proxy/assets/63802758/3429ea9e-e8a2-4414-9340-90b677ca1956)

**Comment by deanxv** [comment]
> 这个问题的触发和客户端有关，只要是那个客户端就是百分百无论你问什么
> 
> ![image](https://github.com/deanxv/coze-discord-proxy/assets/63802758/3429ea9e-e8a2-4414-9340-90b677ca1956)
> 
> 

那你应该给这个客户端提issue，这个客户端对响应流存在兼容问题，我使用其他的对话面板以及接口调试并没有出现这个问题。
