### ISSUE TITLE
定时活跃改为安装时各自随机或者自定义

### ISSUE THREAD

**Issue by ERCB** [deanxv/coze-discord-proxy#126]
**功能描述**
固定9点活跃改为默认以安装时间或随机时间活跃，支持自定义时间。
**应用场景**
最近几天9点又收到“There are too many users now. Please try again a bit later.”的回复，虽然暂时看似乎没太多影响也没掉线。
不过还是想请大佬看下要不要优化活跃时间？（不知道复杂性和必要性，只是提议哈 :D   主要担心大量的集中时间去请求，这个优秀的项目会不会更容易引起coze官方的关注和针对。）

**Comment by deanxv** [comment]
目前并不是9点整准时同时活跃所有的机器人，只是9点开始活跃任务，每次发送消息前都会加上1-60s之内的随机时间，活跃消息也并未非一成不变，有随机id来规避消息重复。

**Comment by rexcnxie** [comment]
能不能加个自定义参数？我也收到“There are too many users now. Please try again a bit later.”的提示，最好能自己定义下时间发送这个活跃伤务。

**Comment by deanxv** [comment]
> 能不能加个自定义参数？我也收到“There are too many users now. Please try again a bit later.”的提示，最好能自己定义下时间发送这个活跃伤务。

定时活跃任务的意义仅仅是为了让bot产生一次回答，所以没必要在乎回答的是异常信息还是正常响应，只要成功让bot响应了那就是活跃成功，和自定义时间无任何关系。

**Comment by forrestsocool** [comment]
主要是这个项目大家都是9点活跃，可能会有被官方ban的风险。。。我今天也是一堆9点报错的“There are too many users now. Please try again a bit later.”提示

**Comment by deanxv** [comment]
> 主要是这个项目大家都是9点活跃，可能会有被官方ban的风险。。。我今天也是一堆9点报错的“There are too many users now. Please try again a bit later.”提示

再次强调一遍哈，并非是准时9点活跃，而是在9点开始，每次60s随机一个时间发起请求且消息内也含有随机字符串，多机器人情况下会按顺序依次随机时间发起请求。

完全不需要考虑是否会被ban，官方几个月前就知道有这个项目了，官方针对的策略早晚会出来，跟这个定时任务是否需要自定义已经关系不大了。
