### ISSUE TITLE
docker运行无法启动

### ISSUE THREAD

**Issue by gllgoe** [deanxv/coze-discord-proxy#127]
docker运行时无法启动，
日志反馈：
[FATAL] 2024/03/23 - 12:21:39 | [Error parsing JSON: invalid character '/' looking for beginning of object key string]

**Comment by gllgoe** [comment]
是在vps服务器上采用docker-compose运行，换了最新版本也是同样问题，后来更换了v4.3.10，还是同样问题

**Comment by deanxv** [comment]
多机器人配置json格式有问题

**Comment by gllgoe** [comment]
你说的很对，我吧data里面的多机器人配置放在里面，没有修改内容，准备后面配置，后来部署了watchtower，给我自动更新了，我吧那个文件夹删掉重启就解决了。谢谢！
