### ISSUE TITLE
有时候在discord上能够看到coze的回复，但是本地获取不到

### ISSUE THREAD

**Issue by GoTop** [deanxv/coze-discord-proxy#128]
coze里的bot都auto-suggestion都设置为default，每天CDP也能正常使用

但是偶尔会出现discord里能够看到coze发回来的文本：
![WX20240323-184812@2x](https://github.com/deanxv/coze-discord-proxy/assets/1784319/9bc3bb09-61ed-4c89-b0e8-7d2c5cc6cac2)

![WX20240323-184835@2x](https://github.com/deanxv/coze-discord-proxy/assets/1784319/31e5efc7-6d66-4b84-bf6c-1d4e5ad24073)

Docker里显示超时：
```
2024-03-23 18:43:20 coze-discord-proxy  | [GIN] 2024/03/23 - 18:43:20 | 202403231833182150606350XHgA9kk | 200 | 10m2.096409773s |    192.168.65.1 |    POST /v1/chat/completions
2024-03-23 18:43:21 coze-discord-proxy  | [GIN] 2024/03/23 - 18:43:21 | 20240323183318216814135d6IySBvu | 200 | 10m3.134942816s |    192.168.65.1 |    POST /v1/chat/completions
2024-03-23 18:43:27 coze-discord-proxy  | [GIN] 2024/03/23 - 18:43:27 | 20240323183326420188888MEnD4AAz | 200 | 10m1.562940939s |    192.168.65.1 |    POST /v1/chat/completions
```

**Comment by deanxv** [comment]
哪里写了超时？

**Comment by GoTop** [comment]
> 哪里写了超时？

我的docker-composer.yml文件里设置超时为10min，所以docker显示的10m返回就是超时的吧
```
   - REQUEST_OUT_TIME=600
   - STREAM_REQUEST_OUT_TIME=600
```

之前我没有设置REQUEST_OUT_TIME和STREAM_REQUEST_OUT_TIME，docker里就会显示5m2s左右

实际中观察我的程序，这些discord上这些对话的文本并没有能传递回来

我怀疑可能是coze的返回的文本超过2000字，导致没有办法接受到auto-suggestion的信息（两张图里都没有auto-suggestion，正常能返回的文本都有auto-suggestion），导致CDP无法判断coze已经发送完成？

**Comment by deanxv** [comment]
> > 哪里写了超时？
> 
> 
> 
> 我的docker-composer.yml文件里设置超时为10min，所以docker显示的10m返回就是超时的吧
> 
> ```
> 
>    - REQUEST_OUT_TIME=600
> 
>    - STREAM_REQUEST_OUT_TIME=600
> 
> ```
> 
> 
> 
> 之前我没有设置REQUEST_OUT_TIME和STREAM_REQUEST_OUT_TIME，docker里就会显示5m2s左右
> 
> 
> 
> 实际中观察我的程序，这些discord上这些对话的文本并没有能传递回来
> 
> 
> 
> 我怀疑可能是coze的返回的文本超过2000字，导致没有办法接受到auto-suggestion的信息（两张图里都没有auto-suggestion，正常能返回的文本都有auto-suggestion），导致CDP无法判断coze已经发送完成？

如果是非流式请求，没有suggestion的情况下会返回超时异常。如果是流式请求，没有suggestion的情况下会正常返回响应内容，到超时时间后返回结束标识。

**Comment by GoTop** [comment]
> 如果是非流式请求，没有suggestion的情况下会返回超时异常。如果是流式请求，没有suggestion的情况下会正常返回响应内容，到超时时间后返回结束标识。

我调用的时候使用的非流式的，在docker运行页面中看到：
`2024-03-23 18:43:27 coze-discord-proxy  | [GIN] 2024/03/23 - 18:43:27 | 20240323183326420188888MEnD4AAz | 200 | 10m1.562940939s |    192.168.65.1 |    POST /v1/chat/completions`
虽然记录显示正常，但实际就是超时了
超过10分钟，没有数据返回，然后discord里这个频道就被删除了

**Comment by deanxv** [comment]
> > 如果是非流式请求，没有suggestion的情况下会返回超时异常。如果是流式请求，没有suggestion的情况下会正常返回响应内容，到超时时间后返回结束标识。
> 
> 
> 
> 我调用的时候使用的非流式的，在docker运行页面中看到：
> 
> `2024-03-23 18:43:27 coze-discord-proxy  | [GIN] 2024/03/23 - 18:43:27 | 20240323183326420188888MEnD4AAz | 200 | 10m1.562940939s |    192.168.65.1 |    POST /v1/chat/completions`
> 
> 虽然记录显示正常，但实际就是超时了
> 
> 超过10分钟，没有数据返回，然后discord里这个频道就被删除了

目前就是这样的:如果是非流式请求，没有suggestion的情况下会返回超时异常。

**Comment by GoTop** [comment]
> > > 如果是非流式请求，没有suggestion的情况下会返回超时异常。如果是流式请求，没有suggestion的情况下会正常返回响应内容，到超时时间后返回结束标识。
> > 
> > 
> > 我调用的时候使用的非流式的，在docker运行页面中看到：
> > `2024-03-23 18:43:27 coze-discord-proxy  | [GIN] 2024/03/23 - 18:43:27 | 20240323183326420188888MEnD4AAz | 200 | 10m1.562940939s |    192.168.65.1 |    POST /v1/chat/completions`
> > 虽然记录显示正常，但实际就是超时了
> > 超过10分钟，没有数据返回，然后discord里这个频道就被删除了
> 
> 目前就是这样的:如果是非流式请求，没有suggestion的情况下会返回超时异常。

但是我上面的例子里，discord上对话的bot已经获取到完整的coze的回复了，只是因为没有获取到auto suggestion，导致无法返回数据，这算是一个bug么？

**Comment by deanxv** [comment]
> > 目前就是这样的:如果是非流式请求，没有suggestion的情况下会返回超时异常。
> 
> 
> 
> 但是我上面的例子里，discord上对话的bot已经获取到完整的coze的回复了，只是因为没有获取到auto suggestion，导致无法返回数据，这算是一个bug么？

不是，就是这样设计的。在非流式请求下，没有suggestion无法判断是否coze-bot是否真正编辑完成了响应，所以没必要返回。

**Comment by GoTop** [comment]
> > > 目前就是这样的:如果是非流式请求，没有suggestion的情况下会返回超时异常。
> > 
> > 
> > 但是我上面的例子里，discord上对话的bot已经获取到完整的coze的回复了，只是因为没有获取到auto suggestion，导致无法返回数据，这算是一个bug么？
> 
> 不是，就是这样设计的。在非流式请求下，没有suggestion无法判断是否coze-bot是否真正编辑完成了响应，所以没必要返回。

哦，了解。

那可能是字数超过2000了，discord的bot就不接收suggestion文本了

**Comment by deanxv** [comment]
> > > > 目前就是这样的:如果是非流式请求，没有suggestion的情况下会返回超时异常。
> 
> > > 
> 
> > > 
> 
> > > 但是我上面的例子里，discord上对话的bot已经获取到完整的coze的回复了，只是因为没有获取到auto suggestion，导致无法返回数据，这算是一个bug么？
> 
> > 
> 
> > 不是，就是这样设计的。在非流式请求下，没有suggestion无法判断是否coze-bot是否真正编辑完成了响应，所以没必要返回。
> 
> 
> 
> 哦，了解。
> 
> 
> 
> 那可能是字数超过2000了，discord的bot就不接收suggestion文本了
> 
> 
> 
> 但是我自己把discord上coze的回复文本，放到 https://platform.openai.com/tokenizer 去计算，也才600个token，572个字符，我们是就获取不到suggestion了呢

和字符长度没有关系，coze托管的bot偶尔是会不生成suggestion的，概率很低。但目前coze有个bug，这个suggestion对每个discord用户一天的生成次数也是有限制的，每个用户一天100次，如果遇到了这个问题可以去找coze官方反馈下。

**Comment by GoTop** [comment]
> 和字符长度没有关系，coze托管的bot偶尔是会不生成suggestion的，概率很低。但目前coze有个bug，这个suggestion对每个discord用户一天的生成次数也是有限制的，每个用户一天100次，如果遇到了这个问题可以去找coze官方反馈下。

没想到除了调用模型的限制，suggestion对每个discord对用户也有限制啊

虽然GPT-4 Turbo (128k) - 50次/天、GPT-4 (8k) - 100次/天、GPT-3.5 (16k) - 500次/天，但是如果使用非流式，最多也只正常用100次/天

那我换成流式请求，就没有这每天100条suggestion的限制了？

**Comment by deanxv** [comment]
> > 和字符长度没有关系，coze托管的bot偶尔是会不生成suggestion的，概率很低。但目前coze有个bug，这个suggestion对每个discord用户一天的生成次数也是有限制的，每个用户一天100次，如果遇到了这个问题可以去找coze官方反馈下。
> 
> 
> 
> 没想到除了调用模型的限制，suggestion对每个discord对用户也有限制啊
> 
> 
> 
> 虽然GPT-4 Turbo (128k) - 50次/天、GPT-4 (8k) - 100次/天、GPT-3.5 (16k) - 500次/天，但是如果使用非流式，最多也只正常用100次/天
> 
> 
> 
> 那我换成流式请求，就没有这每天100条suggestion的限制了？

流式会正常响应，但结束会等到超时时间，这个issue里我已经是第三遍强调这点了。而且你可以自己尝试调试一下也会知道答案，不用什么问题都在这里提，我也没有那么多精力去回答每个问题。

最佳方案是配置多discord用户用gpt4模型，如果想要用coze的3.5那为何不用官网的呢？同样是免费且好用。

**Comment by GoTop** [comment]
> > > 和字符长度没有关系，coze托管的bot偶尔是会不生成suggestion的，概率很低。但目前coze有个bug，这个suggestion对每个discord用户一天的生成次数也是有限制的，每个用户一天100次，如果遇到了这个问题可以去找coze官方反馈下。
> > 
> > 
> > 没想到除了调用模型的限制，suggestion对每个discord对用户也有限制啊
> > 虽然GPT-4 Turbo (128k) - 50次/天、GPT-4 (8k) - 100次/天、GPT-3.5 (16k) - 500次/天，但是如果使用非流式，最多也只正常用100次/天
> > 那我换成流式请求，就没有这每天100条suggestion的限制了？
> 
> 流式会正常响应，但结束会等到超时时间，这个issue里我已经是第三遍强调这点了。而且你可以自己尝试调试一下也会知道答案，不用什么问题都在这里提，我也没有那么多精力去回答每个问题。
> 
> 最佳方案是配置多discord用户用gpt4模型，如果想要用coze的3.5那为何不用官网的呢？同样是免费且好用。

我也在尝试调试，但是没有你前面提到的suggestion有每天100条的限制，使用文本流不需要使用suggestion来判定文本发送完成，我根本不知道如何调试
