### ISSUE TITLE
大佬，求求你救救孩子吧~

### ISSUE THREAD

**Issue by MisZang** [deanxv/coze-discord-proxy#129]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
实在是自己解决不了了，nextchat报404 page not found，WeChatFerry微信机器人报Receiving message error: 'NoneType' object has no attribute 'startswith'，然后render控制台什么也没有输出，微信机器人是chatgpt-on-wechat，项目地址是：https://github.com/zhayujie/chatgpt-on-wechat；另一个微信机器人项目是：https://github.com/lich0821/WeChatFerry；，两个屏幕截图是render的控制台和链接
![屏幕截图 2024-03-24 221010](https://github.com/deanxv/coze-discord-proxy/assets/128830363/c833b387-b2b0-4066-b301-70c8dff551cc)
![屏幕截图 2024-03-24 221019](https://github.com/deanxv/coze-discord-proxy/assets/128830363/94b4516c-6faa-46ad-96a9-47ea5fb15f58)

**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
cow配置的接口地址中去掉v1

**Comment by MisZang** [comment]
> cow配置的接口地址中去掉v1

大佬
![屏幕截图 2024-03-24 221943](https://github.com/deanxv/coze-discord-proxy/assets/128830363/35267568-7a95-48fe-96af-4a9df25a56ed)
discord中@没有反应呀

**Comment by deanxv** [comment]
> > cow配置的接口地址中去掉v1
> 
> 
> 
> 大佬
> 
> ![屏幕截图 2024-03-24 221943](https://github.com/deanxv/coze-discord-proxy/assets/128830363/35267568-7a95-48fe-96af-4a9df25a56ed)
> 
> discord中@没有反应呀

机器人不在线的话去重新发布机器人

**Comment by MisZang** [comment]
> > > cow配置的接口地址中去掉v1
> > 
> > 
> > 大佬
> > ![屏幕截图 2024-03-24 221943](https://private-user-images.githubusercontent.com/128830363/316315276-35267568-7a95-48fe-96af-4a9df25a56ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyOTA0NDIsIm5iZiI6MTcxMTI5MDE0MiwicGF0aCI6Ii8xMjg4MzAzNjMvMzE2MzE1Mjc2LTM1MjY3NTY4LTdhOTUtNDhmZS05NmFmLTRhOWRmMjVhNTZlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxNDIyMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OThkNmM0NmQ3NjdjNTY3YTkyNjkwNDU2MjcyNTUzZGY1ZWNiYTg2ZWE1ZTg2MDczYjJhMzYxMWViNzQ3YmJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-ooHxykvRbxzv6k1RFgIrqD5W9S2OBIm-1t0PoEFGYI)
> > discord中@没有反应呀
> 
> 机器人不在线的话去重新发布机器人

谢谢大佬··Q^Q··
