### ISSUE TITLE
这个错误啥意思，我以为额度超了，但在diszord,coze里都可以正常回答

### ISSUE THREAD

**Issue by younggggger** [deanxv/coze-discord-proxy#131]
{
  "error": {
    "message": "no_available_user_auth",
    "type": "request_error",
    "param": "",
    "code": "500"
  }
}

**Comment by deanxv** [comment]
环境变量USER_AUTHORIZATION设置有误，检查是否已过期。

**Comment by younggggger** [comment]
重新设置了 ，还是一样的错误
