### ISSUE TITLE
如何指定模型参数 model

### ISSUE THREAD

**Issue by tisfeng** [deanxv/coze-discord-proxy#135]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**

我尝试在接口中指定模型 model，但返回数据总是  gpt-4-turbo 。

文档描述不同模型有次数限制，如何指定模型参数 model ？

```bash
GPT-4 Turbo (128k) - 50次/天
GPT-4 (8k) - 100次/天
GPT-3.5 (16k) - 500次/天
```

**复现步骤**

**预期结果**

**相关截图**

<img width="953" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/25194972/4cfa3e28-be4b-4f78-911b-80e00711a1c7">

**Comment by deanxv** [comment]
1. 指定不了，模型在你发布coze机器人的时候就已经定好了。
2. 返回值中的model为系统默认，不可作为参考，直接无视掉。

**Comment by tisfeng** [comment]
如果我想使用 gpt-3.5-turbo，那是否需要新建一个 coze bot，选择 gpt-3.5-turbo 然后发布？

**Comment by deanxv** [comment]
> 如果我想使用 gpt-3.5-turbo，那是否需要新建一个 coze bot，选择 gpt-3.5-turbo 然后发布？

是的

**Comment by rexcnxie** [comment]
> 1. 指定不了，模型在你发布coze机器人的时候就已经定好了。
> 2. 返回值中的model为系统默认，不可作为参考，直接无视掉。

是指coze发布之前在页面中选的那个Model吗？
