### ISSUE TITLE
本来一切正常，突然报504超时了

### ISSUE THREAD

**Issue by Gijela** [deanxv/coze-discord-proxy#136]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**

请求网址: https://gpt-chat2hub.zeabur.app/api/openai/v1/chat/completions
请求方法: POST
状态代码: 504 Gateway Timeout

payload为
```json
{
"stream":true,
"model":"gpt-3.5-turbo",
"temperature":0.5,
"presence_penalty":0,
"frequency_penalty":0,
"top_p":1,
"messages":[{"role":"system","content":"\nYou are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2021- 
    09\nCurrent model: gpt-3.5-turbo\nCurrent time: 2024/3/28 23:08:16\nLatex inline: $x^2$ \nLatex block: $$e=mc^2$$\n\n"}, 
    {"role":"user","content":"1+4"},{"role":"assistant","content":"stream timeout"},{"role":"user","content":"1+4"}, 
    {"role":"assistant","content":"stream timeout"},{"role":"user","content":"1+44"}],
}
```

本来在vercel上是超时的，因为vercel免费版默认最大限制是10s，我后面部署到zeabur, 也超时了，请问是我们服务出了问题吗 调用超时了？？

**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by Gijela** [comment]
我在discord服务器上通过`@`bot的时候，是可以正常返回生成消息的。辛苦大佬看下什么原因啦~~~

**Comment by deanxv** [comment]
> 我在discord服务器上通过`@`bot的时候，是可以正常返回生成消息的。辛苦大佬看下什么原因啦~~~

服务中不会返回504，你中间使用了其他服务或使用了反代有默认超时时间，用postman调试即可校验是否为服务抛出的异常。

**Comment by mmwong1984** [comment]
> > 我在discord服务器上通过`@`bot的时候，是可以正常返回生成消息的。辛苦大佬看下什么原因啦~~~
> 
> 服务中不会返回504，你中间使用了其他服务或使用了反代有默认超时时间，用postman调试即可校验是否为服务抛出的异常。

什么意思，小白一个🥹
