### ISSUE TITLE
希望在日志里加一个请求接口时的body内容，谢谢

### ISSUE THREAD

**Issue by younggggger** [deanxv/coze-discord-proxy#137]
[GIN] 2024/03/29 - 05:09:30 | 20240329050921639632636zGCcP2RA | 200 |   8.87256838s |  34.136.131.100 |    POST /v1/chat/completions

[GIN] 2024/03/29 - 05:09:39 | 20240329050930672112431lh7ajMDy | 200 |  8.835631026s |  34.136.131.100 |    POST /v1/chat/completions

[GIN] 2024/03/29 - 05:09:48 | 20240329050939568695377ra6YCLGq | 200 |  8.742331596s |  34.136.131.100 |    POST /v1/chat/completions

[GIN] 2024/03/29 - 05:09:57 | 20240329050948376379827y2vt2PED | 200 |  9.245894369s |  34.136.131.100 |    POST /v1/chat/completions

**Comment by younggggger** [comment]
返回的内容的也可以顺便加上，返回的最后结果，也就是stream返回的最后一条

**Comment by deanxv** [comment]
不考虑，通常情况下请求体会很长，打印出来只会耽误排查其他错误。想查看具体对话是什么可以按照请求Id去discord中的频道名找对应的。
