### ISSUE TITLE
莫名自动生成大量空白频道，导致达到discord 服务器500个频道限制，从而不能提供服务

### ISSUE THREAD

**Issue by Gijela** [deanxv/coze-discord-proxy#138]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
如题，这个问题昨天出现过一次了，当时是手动删除的。
今天是第二次，问题描述是自动生成了大量的临时频道，估测是达到了discord 服务器500个频道的限制，
导致discord不能再次新建临时频道，从而不能提供服务，调用服务会报错
```javascript
{
  "error": true,
  "message": "empty response from server"
}
```

大量频道的图片，且频道里面是空的，没有产生对话
![](https://img2.imgtp.com/2024/03/29/WofsDnE6.png)

请问这个问题有好的解决方法吗？

**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
1. 产生原因为你的服务器网络发生波动或discord的网关服务发生波动导致频道创建未获取到响应一直发起重试，而因为你的请求并发量比较高导致在这段时间发生大量重试请求。

2. 服务提供接口一键删除临时频道: [GET] api/channel/del/all/cdp

**Comment by Gijela** [comment]
手动删除频道可以解决问题

**Comment by Gijela** [comment]
> 1. 产生原因为你的服务器网络发生波动或discord的网关服务发生波动导致频道创建未获取到响应一直发起重试，而因为你的请求并发量比较高导致在这段时间发生大量重试请求。
> 2. 服务提供接口一键删除临时频道: [GET] api/channel/del/all/cdp

感谢您的解答。
我在尝试调用「一键删除临时频道」这个接口的时候，产生了报错 404 page not found。
请问是什么原因呢？目前项目已经部署到最新版本。

![](https://img2.imgtp.com/2024/03/29/BAWJVezf.png)

**Comment by deanxv** [comment]
api/channel/del/all/cdp

swag中的地址是错误的，不要使用swag，swag对请求头的格式校验也有bug。

**Comment by deanxv** [comment]
5分钟后你会提出另一个问题，"为什么提示 未提供正确的proxy-secret？"

答: 服务中非openai对齐的接口鉴权逻辑为请求头加入 proxy-secret ，值为你的环境变量中的PROXY_SECRET。
