### ISSUE TITLE
在chatnext聊天时报错500，该怎么解决

### ISSUE THREAD

**Issue by fgjfjfjfteyerifhfj** [deanxv/coze-discord-proxy#142]
{
  "error": {
    "message": "config error,check logs",
    "type": "request_error",
    "param": "",
    "code": "500"
  }
}

**Comment by deanxv** [comment]
查看docker日志

**Comment by fgjfjfjfteyerifhfj** [comment]
我用render部署的怎么查看，是这个吗
![image](https://github.com/deanxv/coze-discord-proxy/assets/128902618/def2d4d1-f2f1-4f3f-a225-8199940e52d1)

**Comment by deanxv** [comment]
BOT未给ADMIN权限

**Comment by fgjfjfjfteyerifhfj** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/128902618/571f9252-b906-4c49-9fba-b3b9d208aade)
现在无法反馈到chatnext，我看discord的上面有消息

**Comment by deanxv** [comment]
提issue前请参考其他issue[issue#102](https://github.com/deanxv/coze-discord-proxy/issues/102)

**Comment by fgjfjfjfteyerifhfj** [comment]
谢谢
