### ISSUE TITLE
在ChatGPT-Next-Web使用时，总是显示正在输入，但在discord里看是回复完了，回到NextChat还是显示正在输入

### ISSUE THREAD

**Issue by cakota6462** [deanxv/coze-discord-proxy#145]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
在部署好后，在ChatGPT-Next-Web使用时，总是显示正在输入，但在discord里看是回复完了，回到NextChat还是显示正在输入。
**复现步骤**
正常部署后使用提供的NextChat测试。
**预期结果**
希望大佬可以修复。
**相关截图**
<img width="874" alt="截屏2024-04-01 18 00 08" src="https://github.com/deanxv/coze-discord-proxy/assets/153862945/867fa61d-9186-498d-b527-bbc6f28206b8">

**Comment by deanxv** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/6baffb20-1b31-49f6-ad47-56e8242108d2)

**Comment by cakota6462** [comment]
大佬nb
