### ISSUE TITLE
我想让每次对话都包含上下文信息，设置DEFAULT_CHANNEL_ENABLE=1，但是coze bot回答的问题会不完整

### ISSUE THREAD

**Issue by GoTop** [deanxv/coze-discord-proxy#149]
我想让每次对话都包含上下文信息，所以设置DEFAULT_CHANNEL_ENABLE=1，这样可以实现想要的效果吗？

但是设置DEFAULT_CHANNEL_ENABLE=1后，会有很大的概率出现回答不完整的情况

**Comment by deanxv** [comment]
不需要设置DEFAULT_CHANNEL_ENABLE

**Comment by GoTop** [comment]
> 不需要设置DEFAULT_CHANNEL_ENABLE

也就是说，在coze的bot的Model Configuration里，设置了Dialog round，不管是否设置CDP的DEFAULT_CHANNEL_ENABLE，都可以让coze的bot记住之前对话的信息？

**Comment by deanxv** [comment]
> > 不需要设置DEFAULT_CHANNEL_ENABLE
> 
> 
> 
> 也就是说，在coze的bot的Model Configuration里，设置了Dialog round，不管是否设置CDP的DEFAULT_CHANNEL_ENABLE，都可以让coze的bot记住之前对话的信息？

具体要看你调用接口时是否传递了上下文，如果对openai的接口文档不熟悉，只需要关闭DEFAULT_CHANNEL_ENABLE是最佳方案。

**Comment by GoTop** [comment]
> 具体要看你调用接口时是否传递了上下文，如果对openai的接口文档不熟悉，只需要关闭DEFAULT_CHANNEL_ENABLE是最佳方案。

也就是说，对话是否包含上下文信息，和DEFAULT_CHANNEL_ENABLE的设置没有关系。

但是关闭DEFAULT_CHANNEL_ENABLE是正常运行CDP的最佳选择
