### ISSUE TITLE
创bot不成功

### ISSUE THREAD

**Issue by History203** [deanxv/coze-discord-proxy#15]
跟据issue里设了权限
![test](https://github.com/deanxv/coze-discord-proxy/assets/154799729/695afec6-b8f4-49d3-bf62-89d1ed85c40e)

**Comment by deanxv** [comment]
这不是bug 不要把提这种issue到bug里。

先创建个服务器，才能把bot拉进群。

readme中有TG交流群 ，群中有详细文档可以查看。

**Comment by History203** [comment]
好呢
