### ISSUE TITLE
无法创建频道

### ISSUE THREAD

**Issue by yushangxiao** [deanxv/coze-discord-proxy#150]
无法创建频道，post请求/api/channel/create一直失败，

返回：    {"message":"无权进行此操作,未提供正确的 proxy-secret","success":false}

我的请求头认证是正确的，因为我可以正常使用其他接口，比如chat和生成image。

环境：在render上使用docker部署

请求部分主要代码：

self.base_url='https://*****.onrender.com'
self.headers={
            'Content-Type': 'application/json',
            'Authorization': self.key
            }

def creat_cheenl(self,name):
        url=self.base_url+'/api/channel/create'
        data={
            "name": name,
            "parentId": self.parentId,
            "type": 0
        }
        res=requests.post(url,headers=self.headers,data=json.dumps(data))
        print(res.text)

**Comment by deanxv** [comment]
非openai对齐接口的鉴权请求头为 proxy-secret:<PROXY_SECRET>

**Comment by yushangxiao** [comment]
感谢，这对我很有帮助。
