### ISSUE TITLE
接口还未获取到完整响应连接就中断了

### ISSUE THREAD

**Issue by sweethclz** [deanxv/coze-discord-proxy#151]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
接口还未获取到完整响应连接就中断了。

- 使用第三方容器平台render部署没有问题
- 使用自己的 aws 香港节点 服务器部署会出现这个问题
- aws节点系统是重装的，没有进行过网络配置修改
- racknerd平台租赁的美国节点也有这个问题

**复现步骤**

**预期结果**

**相关截图**
配置：
![配置2](https://github.com/deanxv/coze-discord-proxy/assets/52772637/6e7dedca-6ae0-4aec-9604-7ca2836be902)
接口：
![接口1](https://github.com/deanxv/coze-discord-proxy/assets/52772637/c0f8be90-a7e7-4db1-99e8-584864cc25fa)

**Comment by deanxv** [comment]
查看discord中的对话记录是否正常，并查看非流式请求下是否正常。

**Comment by sweethclz** [comment]
> 查看discord中的对话记录是否正常，并查看非流式请求下是否正常。

discord里面的是正常的，非流式请求也会报错。他也不是所有会话都会中断连接，是回复的token比较长时才会有这个问题。我感觉是我服务器网络的问题，香港节点服务器重装Ubuntu后重新部署还是有这个问题。

**Comment by deanxv** [comment]
> > 查看discord中的对话记录是否正常，并查看非流式请求下是否正常。
> 
> 
> 
> discord里面的是正常的，非流式请求也会报错。他也不是所有会话都会中断连接，是回复的token比较长时才会有这个问题。我感觉是我服务器网络的问题，香港节点服务器重装Ubuntu后重新部署还是有这个问题。

如果服务日志中没有报错信息，更换地区的vps再试试。

**Comment by sweethclz** [comment]
> > > 查看discord中的对话记录是否正常，并查看非流式请求下是否正常。
> > 
> > 
> > discord里面的是正常的，非流式请求也会报错。他也不是所有会话都会中断连接，是回复的token比较长时才会有这个问题。我感觉是我服务器网络的问题，香港节点服务器重装Ubuntu后重新部署还是有这个问题。
> 
> 如果服务日志中没有报错信息，更换地区的vps再试试。

好，我再试试

**Comment by sweethclz** [comment]
> > > 查看discord中的对话记录是否正常，并查看非流式请求下是否正常。
> > 
> > 
> > discord里面的是正常的，非流式请求也会报错。他也不是所有会话都会中断连接，是回复的token比较长时才会有这个问题。我感觉是我服务器网络的问题，香港节点服务器重装Ubuntu后重新部署还是有这个问题。
> 
> 如果服务日志中没有报错信息，更换地区的vps再试试。

换了地区也不行，后来配置了ssl证书，使用https，就不存在那个问题了。
