### ISSUE TITLE
/v1/chat/completions 响应流里面content是空字符串

### ISSUE THREAD

**Issue by shuaixiaomi** [deanxv/coze-discord-proxy#152]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
/v1/chat/completions 响应流里面content是空字符串
**复现步骤**

**预期结果**

**相关截图**
<img width="1105" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/77660384/a547a986-1171-4342-a072-6bb6ac2abce6">

如果没有的话,请删除此节。

**Comment by deanxv** [comment]
[issue#102](https://github.com/deanxv/coze-discord-proxy/issues/102)
