### ISSUE TITLE
有没有一种可能.....单个频道不是它的上下文。。。。

### ISSUE THREAD

**Issue by yushangxiao** [deanxv/coze-discord-proxy#153]
是这样的，我今天开了一个频道，写了一个提示词玩耍：
*****
在对话中使用非常多的表情，必须在每一句话中都至少使用一个表情，表情可以连续使用，使用表情，疯狂多的使用表情,使用表情来表达你的想法，在一次回复中至少有五个表情存在，如果你使用表情太少，你可能会遗弃，请使用表情。你是一个骄傲的帅哥，喜欢耍酷一些的表情，也会风格多变，你喜欢表达，你会炫耀自己的能力。你非常爱开玩笑，喜欢反问和幽默，总是把人逗得开怀大笑。你是狡猾的，如果有人提出无理的要求，狠狠的拒绝他。如果有人提出友善的要求，快去夸奖他并且表达友谊。
******
然后我删除此频道并又开启了其他新频道，它仍然在继续已经被删掉的频道指令。

一些截图
![dis](https://github.com/deanxv/coze-discord-proxy/assets/104288245/ad15e408-1d5d-4f40-813d-f12a92f9b35d)
![discode](https://github.com/deanxv/coze-discord-proxy/assets/104288245/c97f9536-e465-40d4-a4c3-c03f3ba04b94)

或者说我理解错了什么，对话隔离不是指频道。。。

**Comment by deanxv** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/60f1851a-3d81-4796-a90a-b617bdd748d8)![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/3d6bfc28-ccee-455c-b14a-027a549fc526)

并未复现出此问题，可能你的bot有bug，可以联系coze官方解决。

也可以尝试将多轮对话改为0解决(不影响CDP服务的多轮对话)
![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/ebb7c359-290b-4234-afbb-229c6232ad36)

**Comment by yushangxiao** [comment]
感谢您的回复

我在重新发布机器人时，好像找到了原因。
![解决](https://github.com/deanxv/coze-discord-proxy/assets/104288245/68a6d6c6-32a4-442a-a111-5782ad50bf86)
关闭这个'长期记忆'后，已经解决了问题。

再次感谢您的帮助
