### ISSUE TITLE
请问一下是不是非得使用discord ，可不可以不配置，使用slack

### ISSUE THREAD

**Issue by syx-413** [deanxv/coze-discord-proxy#16]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
请问一下是不是非得使用discord ，可不可以不配置，使用slack
**应用场景**

**Comment by deanxv** [comment]
此项目是为了通过discord-bot实现代理出api给其它对话面板或程序使用，如果只是想在slack中对话，那可以直接在coze中将机器人发布到slack。
