### ISSUE TITLE
机器人无法结束对话，该设置的地方都设置了

### ISSUE THREAD

**Issue by y1713375484** [deanxv/coze-discord-proxy#160]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
<img width="704" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/80376536/6f8da55a-e2b1-47b8-95e4-2fe524838b26">
并且dis上也能看到聊天结束
<img width="544" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/80376536/f0e0309f-db93-4232-9724-b99274586ea3">

**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by y1713375484** [comment]
并且查看logs里面也没有记录
<img width="1598" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/80376536/836bd158-8246-45fb-8da6-9891e78dc901">

**Comment by deanxv** [comment]
提供相关截图

**Comment by y1713375484** [comment]
<img width="1912" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/80376536/06d61c4d-3ff3-4adf-83b7-ca39ed4ce315">
<img width="1202" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/80376536/2c325ec9-21d3-4248-af15-c7b585fb7bfc">
就一直在请求中，无法响应

<img width="592" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/80376536/c0d3c6d9-bad8-426d-a5a7-911dd7c320c4">

**Comment by y1713375484** [comment]
gpt-4-8k都次数已经用完了，这是用的gpt4-128k

**Comment by y1713375484** [comment]
而且用流式请求会这样
<img width="1480" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/80376536/7134dd2d-1ace-45cf-9758-99232b862b37">
<img width="1456" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/80376536/1617c42b-3a88-49b6-91d7-47cb9a1850ef">

**Comment by deanxv** [comment]
每个discord账号每天有100次生成suggestion的数量限制，达到限制后无法生成suggestion导致无法获取响应结束标识。更换discord账号。

**Comment by y1713375484** [comment]
意思就是，无论如何一个账号就只能获取到100条消息呗

**Comment by deanxv** [comment]
> 意思就是，无论如何一个账号就只能获取到100条消息呗

不是，在流式响应下可以设置超时时间来获取完整响应，但要有一定开发基础。如果不想折腾就直接换discord账号。
