### ISSUE TITLE
时区问题

### ISSUE THREAD

**Issue by mt-altman** [deanxv/coze-discord-proxy#162]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [ X] 我已确认目前没有类似 issue
+ [ X] 我已确认我已升级到最新版本
+ [ X] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ X] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
   怎么解决时区问题。我理解是coze的问题，但是还是想确认一下
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/deanxv/coze-discord-proxy/assets/161905557/6614e80c-55ae-4f73-a5d4-ae7d11288fcd)

**Comment by deanxv** [comment]
无法解决，需要联系coze官方客服。
