### ISSUE TITLE
国内服务器已配置代理docker-compose部署报错

### ISSUE THREAD

**Issue by Shadownc** [deanxv/coze-discord-proxy#165]
**国内服务器已配置代理docker-compose部署运行日志：error opening connection, Get "https://discord.com/api/v9/gateway": unexpected EOF**

**Comment by deanxv** [comment]
说明代理配置的不对，检查服务启动日志是否打印了"proxy set success"，代理是否为http。

**Comment by Shadownc** [comment]
代理已配置 日志已打印proxy set success

**Comment by deanxv** [comment]
那就是代理地址是无效的
