### ISSUE TITLE
请求报错：Invalid request parameters

### ISSUE THREAD

**Issue by iamagirlforios** [deanxv/coze-discord-proxy#168]
使用postman进行请求的时候，返回500错误：
请求头：
![image](https://github.com/deanxv/coze-discord-proxy/assets/19585883/5c50ad77-d8ae-449f-84e1-53ec49a9facd)

请求参数：
![image](https://github.com/deanxv/coze-discord-proxy/assets/19585883/ab043272-dcb6-4a3b-9d8b-80ae3459d668)

结果返回：
![image](https://github.com/deanxv/coze-discord-proxy/assets/19585883/c1037d1c-795b-4e0d-a569-b6cdd2b5e196)

帮忙看看~

**Comment by deanxv** [comment]
接口地址，请求体粘贴出来看看

**Comment by iamagirlforios** [comment]
http://10.253.45.130:7077/v1/chat/completions

**Comment by iamagirlforios** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/19585883/c3b12f8f-11c6-442b-8fef-e6f024fa06ac)

**Comment by iamagirlforios** [comment]
http://10.253.45.130:7077/v1/chat/completions

**Comment by deanxv** [comment]
查看docker日志有无报错信息

**Comment by deanxv** [comment]
重启服务再看日志，不要开自动重启

**Comment by iamagirlforios** [comment]
试了日志还是一样的诶~

**Comment by iamagirlforios** [comment]
<img width="1114" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/19585883/cc36553a-0d20-4e5e-b616-2f5fdd7a1311">
全是这样的大佬

**Comment by deanxv** [comment]
说明服务器不通discord网关，需要国外网络。

**Comment by iamagirlforios** [comment]
我现在已经连着vpn了，那我再试试，感谢~

**Comment by deanxv** [comment]
如果使用了代理，可以把代理后的地址及端口设置到环境变量PROXY_SRCRET中，如果对这方面了解不多，不懂如何设置建议直接使用国外vps。

**Comment by iamagirlforios** [comment]
好嘞好嘞，我先试试，不行了再请教你哈
