### ISSUE TITLE
使用ChatGPT-Next-Web部署到vercel，然后通过配置的地址后，使用时提示：Failed to fetch，接口提示：blocked:mixed-content

### ISSUE THREAD

**Issue by forjone** [deanxv/coze-discord-proxy#170]
背景：
将[ChatGPT-Next-Web](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web)部署到vercel，然后通过配置的地址使用时，提示：
{
  "error": true,
  "message": "Failed to fetch"
}

![image](https://github.com/deanxv/coze-discord-proxy/assets/24834711/be30ef5b-a795-4282-8d2c-dd6ce092ce96)

排查了好一圈，最后发现：接口是http的，但是部署到vercel上的地址是https的。这种有没有办法解决，除了在coze-discord-proxy部署的服务器上加入SSL证书的方法外。

![image](https://github.com/deanxv/coze-discord-proxy/assets/24834711/4c600230-e56d-468d-9164-ad2ddb5cecb0)

**Comment by deanxv** [comment]
<img width="494" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/57529708/7e25f48a-a97d-4712-b47b-5d73b4d74d1c">
<img width="429" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/57529708/3df4c678-a1fb-4ae7-8ec3-1a357a6446fc">
<img width="1108" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/57529708/bb1c1b21-13e6-4fc5-93f1-aac06f09130e">

**Comment by forjone** [comment]
好的，感谢
