### ISSUE TITLE
请问如何获取 discord suggestions区域的内容

### ISSUE THREAD

**Issue by cumany** [deanxv/coze-discord-proxy#172]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
请问如何获取 discord suggestions区域的内容，目前问题结束后一般 discord会列出三个相关问题，能否获取问题的文本呢？

**应用场景**

**Comment by deanxv** [comment]
目前未提供该信息返回，因为正常对接openai对齐的接口不需要这个内容。
