### ISSUE TITLE
Render 

### ISSUE THREAD

**Issue by texplorer1** [deanxv/coze-discord-proxy#173]
Render Log出现以下提示：

**问题描述**
[SYS] 2024/05/05 - 18:37:39 | COZE-DISCORD-PROXY v4.4.6 started 
2024/05/05 18:37:39 [DG0] restapi.go:282:RequestWithLockedBucket() rate limit unmarshal error, invalid character 'e' looking for beginning of value
[FATAL] 2024/05/05 - 18:37:39 | [error opening connection, invalid character 'e' looking for beginning of value] 
[SYS] 2024/05/05 - 18:38:10 | COZE-DISCORD-PROXY v4.4.6 started 
2024/05/05 18:38:10 [DG0] restapi.go:282:RequestWithLockedBucket() rate limit unmarshal error, invalid character 'e' looking for beginning of value
[FATAL] 2024/05/05 - 18:38:10 | [error opening connection, invalid character 'e' looking for beginning of value]

**Comment by deanxv** [comment]
非bug，尝试使用国外vps部署
