### ISSUE TITLE
咨询一个流式请求和非流式请求的问题

### ISSUE THREAD

**Issue by wangxyd** [deanxv/coze-discord-proxy#174]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**

问题背景：

1. 我有3个CozeBot，分别对应GPT-4-Turbo、GPT-4和GPT-3.5三个模型，我误关闭了GPT-4-Turbo的CozeBot的Auto-Suggestion，GPT-4和GPT-3.5的没有关闭，下面是coze-discord-proxy的日志：
```sh
[root@cdp001 ~]# docker logs --tail=6 coze-discord-proxy-03
# 昨天的GPT-4-Turbo请求，每次响应时间都是30s左右
[GIN] 2024/05/07 - 22:36:31 | 2024050722360065086702984Kn5Su5 | 200 | 31.134971888s |      172.29.0.1 |    POST /v1/chat/completions
# 今天的cozebot-active请求，GPT-4-Turbo响应时间30s，GPT-4和GPT-3.5响应很快
[GIN] 2024/05/08 - 03:12:07 | 2024050803153682783466KeExT6oH | 200 | 31.175261373s |      172.29.0.1 |    POST /v1/chat/completions
[GIN] 2024/05/08 - 03:20:01 | 20240508031950393977883a7g8uLNg | 200 |  11.23728639s |      172.29.0.1 |    POST /v1/chat/completions
[GIN] 2024/05/08 - 03:33:29 | 20240508033325546789843uNay7snZ | 200 |  4.335900964s |      172.29.0.1 |    POST /v1/chat/completions
# 今天打开Auto-Suggestion前的GPT-4-Turbo请求，响应时间30s
[GIN] 2024/05/08 - 07:25:58 | 202405080725275493083811WRABZB0 | 200 | 31.056662381s |      172.29.0.1 |    POST /v1/chat/completions
# 今天打开Auto-Suggestion后的GPT-4-Turbo请求，响应很快
[GIN] 2024/05/08 - 07:50:39 | 20240508075026654697648bIHKpV3Q | 200 | 12.552765547s |      172.29.0.1 |    POST /v1/chat/completions
[root@cdp001 ~]# cat /root/coze-discord-proxy/03/docker-compose.yml | grep OUT_TIME
    - REQUEST_OUT_TIME=30
    - STREAM_REQUEST_OUT_TIME=60
```
2. 之前在issue里面看到您说`如果是非流式请求，没有suggestion的情况下会返回超时异常。如果是流式请求，没有suggestion的情况下会正常返回响应内容，到超时时间后返回结束标识。`。
3. `docker-compose.yml`确定已经生效了。

我的问题：

1. 我的GPT-4-Turbo的CozeBot没有开启Auto-Suggestion，但是到超时时间后正常返回了响应内容，根据问题背景2可以判断我的请求是流式请求，但是为什么日志中打印的响应时间等于`REQUEST_OUT_TIME`而非`STREAM_REQUEST_OUT_TIME`呢？
2. 我想了解一下coze-discord-proxy什么情况下使用流式请求，什么情况下使用非流式请求？这个是程序自动选择的还是可以配置的？

**复现步骤**

**预期结果**

**Comment by deanxv** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/ca0010a4-2c9d-4751-a903-85b7a81fada7)

v4.4.0版本已修改逻辑，无论流式与非流式在超时后都会返回响应的内容，已不再会返回超时异常。

请求体中的stream为true/false来选择是否为流式请求，可自行查看openai官方接口文档。

**Comment by wangxyd** [comment]
那就说得通了，我的客户端应用是cow，我大概看了一下它的源码，它使用的是非流式请求访问chatgpt，因此没有Auto-Suggestion的情况下，响应时间是`REQUEST_OUT_TIME`秒。

感谢大佬的解答和这么nb的开源应用！
