### ISSUE TITLE
無法用nginx 反代到next web chat 失敗，不能用

### ISSUE THREAD

**Issue by WillWang2122** [deanxv/coze-discord-proxy#175]
**温馨提示: 未`star`项目会被自动关闭issue哦!**
己經start 了，謝謝作者和各位developer
**例行检查**

+ [ YES] 我已确认目前没有类似 issue
+ [ YES] 我已确认我已升级到最新版本
+ [ YES] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ YES] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
在nextchat 中使用生成如下錯誤：
```
{
  "error": true,
  "message": "empty response from server"
}

hello

{
  "error": true,
  "message": "empty response from server"
}

hi

{
  "error": true,
  "message": "empty response from server"
}

hi

{
  "error": true,
  "message": "NetworkError when attempting to fetch resource."
}

{
  "error": true,
  "message": "empty response from server"
}

hi

{
  "error": true,
  "message": "NetworkError when attempting to fetch resource."
}

{
  "error": true,
  "message": "empty response from server"
}

hi

{
  "error": true,
  "message": "NetworkError when attempting to fetch resource."
}

{
  "error": true,
  "message": "empty response from server"
}

hi

{
  "error": true,
  "message": "NetworkError when attempting to fetch resource."
}

hi

{
  "error": true,
  "message": "NetworkError when attempting to fetch resource."
}

{
  "error": true,
  "message": "empty response from server"
}
```

**复现步骤**
在我的伺服器上我做了如下的設定:
反代 gui.mydomain.com 到nextweb (前端GUI)， nginx 設定如下：
location ^~ / {
    proxy_pass http://172.17.0.4:3000; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header X-Cache $upstream_cache_status; 
    add_header Strict-Transport-Security "max-age=31536000"; 
    add_header Cache-Control no-cache; 
}

在app.mydomain.com 的root 是反代到我的後端模型的endpoint (就是coze-discord-proxy 的docker 容器~~).
location ^~ / {
    proxy_pass http://172.17.0.9:7077; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header X-Cache $upstream_cache_status; 
    add_header Strict-Transport-Security "max-age=31536000"; 
    add_header Cache-Control no-cache; 
}

結果產生上述錯誤
我在nextchat 中endpoint 不管是用反代https://app.mydomain.com的或是IP:端口 172.17.0.9:7077都會報錯
**预期结果**
可以用，不報錯
**相关截图**
如果没有的话,请删除此节。

![w](https://github.com/deanxv/coze-discord-proxy/assets/168748301/91cede2b-cfef-469d-8c49-553f8ba13291)

**Comment by deanxv** [comment]
NextChat的地址是否为https协议？
