### ISSUE TITLE
怎样配置两个discord帐号

### ISSUE THREAD

**Issue by haso2007** [deanxv/coze-discord-proxy#176]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
我有两个discord帐号，且都获取了USER_AUTHORIZATION,但是我发现服务器GUILD_ID只能填一个，因此我只能使用其中的一个帐号。我需要怎样做才能使用两个帐号来做负载均衡呢。
另外我在我的服务器中邀请了三个Coze的机器人，这有必要吗。负载均衡是用discord帐号还是使用Coze机器人来实现呢，我有点混乱。
**应用场景**

**Comment by deanxv** [comment]
[查看文档](https://cdp-docs.pages.dev/)

**Comment by haso2007** [comment]
其它的还有一点，两个USER_AUTHORIZATION，可以设置同一个PROXY_SECRET吗，还是一定要分开。

**Comment by deanxv** [comment]
> 其它的还有一点，两个USER_AUTHORIZATION，可以设置同一个PROXY_SECRET吗，还是一定要分开。

这两个之间没有关系
