### ISSUE TITLE
在使用gpt4v时遇到一个问题

### ISSUE THREAD

**Issue by y1713375484** [deanxv/coze-discord-proxy#177]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
在请求时如果将文本内容置于图片内容后面将会报错
<img width="868" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/80376536/37a2444d-05e7-4345-ad28-f7309f6aa195">

将文本内容放在图片内容前侧将能正常响应
<img width="1081" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/80376536/44b707b4-1e84-42ce-9954-710171d583b2">

**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
是的，就是这样设计要按照顺序的，不过后期也可以修改兼容下。

**Comment by y1713375484** [comment]
> 是的，就是这样设计要按照顺序的，不过后期也可以修改兼容下。

好的，感谢

**Comment by fitzhang** [comment]
{'error': {'message': 'authorization(proxy-secret)校验失败', 'type': 'invalid_request_error', 'param': '', 'code': 'invalid_authorization'}}
import requests
url = 'https://XXXX.zeabur.app/v1/chat/completions'
headers = {'Authorization':'Bearer ${123456}'}
data = {
  "channelId": "12387*********4666",
  "messages": [
    {
      "content": "请介绍一下佛山职业技术学院",
      "role": "user"
    }
  ],
  "model": "gpt-4-32k",
  "stream": True
}

response = requests.post(url, headers=headers, json=data)

try:
    print(response.json())
请问亲怎么修改

**Comment by fitzhang** [comment]
> ```
> {'error': {'message': 'authorization(proxy-secret)校验失败', 'type': 'invalid_request_error', 'param': '', 'code': 'invalid_authorization'}}
> ```
> 
> import requests url = 'https://XXXX.zeabur.app/v1/chat/completions' headers = {'Authorization':'Bearer ${123456}'} data = { "channelId": "12387*********4666", "messages": [ { "content": "请介绍一下佛山职业技术学院", "role": "user" } ], "model": "gpt-4-32k", "stream": True }
> 
> response = requests.post(url, headers=headers, json=data)
> 
> try: print(response.json()) 请问亲怎么修改

我试验过把headers = {'PROXY_SECRET': '123456'}  这样好像也是报错

**Comment by deanxv** [comment]
> > ```
> > {'error': {'message': 'authorization(proxy-secret)校验失败', 'type': 'invalid_request_error', 'param': '', 'code': 'invalid_authorization'}}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > import requests url = 'https://XXXX.zeabur.app/v1/chat/completions' headers = {'Authorization':'Bearer ${123456}'} data = { "channelId": "12387*********4666", "messages": [ { "content": "请介绍一下佛山职业技术学院", "role": "user" } ], "model": "gpt-4-32k", "stream": True }import requests url = 'https://XXXX.zeabur.app/v1/chat/completions' headers = {'Authorization':'Bearer ${123456}'} data = {"channelId": "12387*********4666", "messages": [{"content": "请介绍一下佛山职业技术学院", "role": "user"}], "model": "gpt-4-32k", "stream": True}
> > response = requests.post(url, headers=headers, json=data)响应 = requests.post(url, headers=headers, json=data)
> > try: print(response.json()) 请问亲怎么修改
> 
> 我试验过把headers = {'PROXY_SECRET': '123456'} 这样好像也是报错

请提出自己的issue 而不是在其他人的issue下回复
