### ISSUE TITLE
Render 和 Docker 部署的 Discord 机器人响应延迟

### ISSUE THREAD

**Issue by SxBgHjSjolqCZxD** [deanxv/coze-discord-proxy#178]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

- [x] 我已确认目前没有类似 issue
- [x] 我已确认我已升级到最新版本
- [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
- [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**

在使用我们部署在 Render 和 Docker 上的 Discord 机器人时，发现它总是需要 5 分钟才能响应消息。相反，托管在 Coze 上的机器人能够立即响应。

**复现步骤**

1. 在 Render 或 Docker 上部署 Discord 机器人。
2. 向机器人发送消息。
3. 观察响应时间。

**预期结果**

机器人应该能够在 Coze 机器人响应完成后立即响应消息。

**相关截图**
![image](https://github.com/deanxv/coze-discord-proxy/assets/157099517/0bfcad81-6ecb-4fb2-98f8-8690369245be)
![image](https://github.com/deanxv/coze-discord-proxy/assets/157099517/5d0bfe85-db53-4508-be2d-e27579ea8f16)
![image](https://github.com/deanxv/coze-discord-proxy/assets/157099517/4d411870-b749-4c84-b87a-032bc2c5ae20)
![image](https://github.com/deanxv/coze-discord-proxy/assets/157099517/e8b0870b-b37a-4704-99c3-3445be5d55e9)
![image](https://github.com/deanxv/coze-discord-proxy/assets/157099517/f3f7a38c-0102-48ca-a4ef-a2f9b2ed0b64)

**Comment by deanxv** [comment]
<img width="963" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/57529708/fa30204d-46d6-4e18-b7b0-d67b75a1e692">

**Comment by SxBgHjSjolqCZxD** [comment]
> Add your comment here...
> 
> [ Markdown is supported ](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

谢谢，现在已经修好了。

**Comment by SxBgHjSjolqCZxD** [comment]
> <img alt="image" width="963" src="https://private-user-images.githubusercontent.com/57529708/330340363-fa30204d-46d6-4e18-b7b0-d67b75a1e692.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzQ0MTEsIm5iZiI6MTcxNTY3NDExMSwicGF0aCI6Ii81NzUyOTcwOC8zMzAzNDAzNjMtZmEzMDIwNGQtNDZkNi00ZTE4LWI3YjAtZDY3Yjc1YTFlNjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA4MDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MjIwNTQ2YzU2ODkxZTI5NjFiMjMxODFjODJjYjlmNTE4YjljZTA1NmJjODRmOGQzYmRkMThhODg3ZmFjMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QUcTBsQuECg6sfoslo7AtlhAhZLYJZoWQKE0WDUPu7g">

谢谢，现在已经修好了。
