### ISSUE TITLE
您好，请问这个无法加入绘图的功能吗

### ISSUE THREAD

**Issue by PpVzll5zQE88ohr** [deanxv/coze-discord-proxy#18]
您好，我在bot中设置了DALLE 3 的插件 ，在discord可以出图，但是在使用api后就无法出图了，请问一下有没有什么解决办法
还有一个是STREAM_REQUEST_OUT_TIME 设置 ，太短无法完全生成，太长会出现{
  "error": true,
  "message": "network error"
}
请问有没有办法让输入完之后直接结束而不是持续出现正在输入，这是我在 Chat gpt next web 上测试的
感谢您在百忙之中抽出空来阅读该信息

**Comment by deanxv** [comment]
支持绘图

这个个参数可以不用设置 因为出图时间大概在一分钟左右，你可能使用了一些带有超时时间的对话面板

使用postman测试下画图可以是否正常返回图片url
