### ISSUE TITLE
关于常见的疑难杂症第四点的请教

### ISSUE THREAD

**Issue by fitzhang** [deanxv/coze-discord-proxy#180]
与openai对齐的接口鉴权请求头为 Authorization，value为Bearer < Api-Key >，CDP项目自有接口鉴权请求头为 proxy-secret，value为< Api-Key >（Api-Key即是环境变量PROXY_SECRET）。
json
{
  "error": {
    "message": "authorization(proxy-secret)校验失败",
    "type": "invalid_request_error",
    "param": "",
    "code": "invalid_authorization"
  }
}
我的代码是
import requests
url = 'https://xxxx.zeabur.app/v1/chat/completions'
headers = {'Authorization':'Bearer ${123456}'}
data = {
"channelId": "12387*********4666",
"messages": [
{
"content": "请介绍一下XXXXXX学院",
"role": "user"
}
],
"model": "gpt-4-32k",
"stream": True
}
response = requests.post(url, headers=headers, json=data)
try:
print(response.json())
系统仍然报错

**Comment by fitzhang** [comment]
我试验过把headers = {'PROXY_SECRET': '123456'} 这样好像也是报错，谢谢作者赐教

**Comment by deanxv** [comment]
headers = {'Authorization':'Bearer 123456'}

**Comment by fitzhang** [comment]
好的，谢谢作者！ @deanxv
