### ISSUE TITLE
系统调试的时候会回显很多data.

### ISSUE THREAD

**Issue by fitzhang** [deanxv/coze-discord-proxy#181]
作者您好，当我我调试代码的时候，系统会回显弹出很多的data，请问我怎么样才能配置才能让系统只回复我最后一条data即可，谢谢！！
curl -X 'POST' \
  'https://XXXX.zeabur.app/v1/chat/completions' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer 123456' \
  -H 'Content-Type: application/json' \
  -d '{
  "channelId": "123875**********666",
  "messages": [
    {
      "content": "请介绍一下你是基于什么语言模型开发的？",
      "role": "user"
    }
  ],
  "model": "gpt-4-32k",
  "stream": true
}'
系统回显内容如下：
{"id":"1239872317417586741","object":"chat.completion.chunk","created":1715678996,"model":"gpt-4-turbo","choices":[{"index":0,"message":{"role":"assistant","content":"很抱歉，我不能为您提供"},"logprobs":null,"finish_reason":null,"delta":{"content":"很抱歉，我不能为您提供"}}],"usage":{"prompt_tokens":42,"completion_tokens":13,"total_tokens":55},"system_fingerprint":null,"suggestions":null}  data: {"id":"1239872317417586741","object":"chat.completion.chunk","created":1715678996,"model":"gpt-4-turbo","choices":[{"index":0,"message":{"role":"assistant","content":"很抱歉，我不能为您提供我被开"},"logprobs":null,"finish_reason":null,"delta":{"content":"我被开"}}],"usage":{"prompt_tokens":42,"completion_tokens":17,"total_tokens":59},"system_fingerprint":null,"suggestions":null}  data: {"id":"1239872317417586741","object":"chat.completion.chunk","created":1715678997,"model":"gpt-4-turbo","choices":[{"index":0,"message":{"role":"assistant","content":"很抱歉，我不能为您提供我被开发出来的"},"logprobs":null,"finish_reason":null,"delta":{"content":"发出来的"}}],"usage":{"prompt_tokens":42,"completion_tokens":21,"total_tokens":63},"system_fingerprint":null,"suggestions":null}  data: {"id":"1239872317417586741","object":"chat.completion.chunk","created":1715678997,"model":"gpt-4-turbo","choices":[{"index":0,"message":{"role":"assistant","content":"很抱歉，我不能为您提供我被开发出来的具体技"},"logprobs":null,"finish_reason":null,"delta":{"content":"具体技"}}],"usage":{"prompt_tokens":42,"completion_tokens":24,"total_tokens":66},"system_fingerprint":null,"suggestions":null}
data: [DONE]

--

**Comment by deanxv** [comment]
这是流式请求，参考[openai官方接口文档](https://platform.openai.com/docs/api-reference/chat/create)使用流式或非流式。

**Comment by fitzhang** [comment]
好的 谢谢楼主，把  "stream": false  这样改即可
