### ISSUE TITLE
使用报错error sending message，但是所有权限都开了

### ISSUE THREAD

**Issue by y1713375484** [deanxv/coze-discord-proxy#182]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
<img width="1639" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/80376536/032498b7-401b-4754-81fd-e60f0cebcd13">
<img width="1502" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/80376536/d98fd4ad-9d97-4a0c-8197-1607009ac675">
<img width="1509" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/80376536/a1e231e3-b7e5-40e1-a63a-00b3960fa555">
应该是权限都开了，我用了三个号做负载，当请求到其中一个账号的时候就会报这个

**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
既然有的好使有的不好使，那就非CDP服务的bug，自行排查下机器人权限问题，检查下是否在服务器中，重新开启Admin权限拉入群聊。

**Comment by y1713375484** [comment]
找到问题了，这个账号并未邀请经discord主服务器中，但是很奇怪的一点是，我不记得前面的账号有操作过邀请加入服务器这一步啊
