### ISSUE TITLE
zeabur上部署，日志报4004错误

### ISSUE THREAD

**Issue by fitzhang** [deanxv/coze-discord-proxy#183]
作者您好，我在zeabur上部署，日志报4004错误，显示如下：
[SYS] 2024/05/15 - 07:19:50 | COZE-DISCORD-PROXY v4.4.9 started 
[FATAL] 2024/05/15 - 07:19:50 | [error opening connection, websocket: close 4004: Authentication failed.] 
[SYS] 2024/05/15 - 07:19:55 | COZE-DISCORD-PROXY v4.4.9 started
 请作者有空查看一下故障，谢谢！

**Comment by deanxv** [comment]
环境变量 USER_AUTHORIZATION 填写有误

**Comment by fitzhang** [comment]
好的，我回去看看，感谢

**Comment by fitzhang** [comment]
![GPT856](https://github.com/deanxv/coze-discord-proxy/assets/65891578/e94e94d1-c0c2-4a43-ad22-087f967e27fe)
![GPT857](https://github.com/deanxv/coze-discord-proxy/assets/65891578/5f33f99b-11b2-4faa-ac35-4e0929b4abc2)
![GPT858](https://github.com/deanxv/coze-discord-proxy/assets/65891578/5ee9e289-5115-4fde-9093-81af6f4bbde7)
作者您好，我确认我的USER_AUTHORIZATION都是完全正确的哈

**Comment by deanxv** [comment]
重新depoly服务了吗

**Comment by fitzhang** [comment]
重新depoly过了 我都重新删除整个服务 重新来的了

**Comment by deanxv** [comment]
不能删除，在配置完环境变量后重新deploy

**Comment by deanxv** [comment]
也有可能是地区ip不支持，也有可能是其他问题，不是很好排查，非项目bug。

**Comment by fitzhang** [comment]
估计是地区原因了  我没有选择美国  选择了香港  可能香港无法使用GPT。。。

**Comment by deanxv** [comment]
检查环境变量 BOT_TOKEN
