### ISSUE TITLE
设定system prompt使用openai兼容的接口，返回内容不按照system prompt的要求执行，时好时坏

### ISSUE THREAD

**Issue by ihorizons2022** [deanxv/coze-discord-proxy#185]
如果不设定system prompt，直接把system prompt做成user prompt的一部分，按照指令执行的效果好一些
请问为啥如此

**Comment by deanxv** [comment]
> Thank you for your nice work.
> 
> 
> 
> 也就是说这是正常的，我也应该把system prompt合并到user prompt中是么？

其实我感觉大差不差，没多大影响。
