### ISSUE TITLE
频道中的机器人突然没有提示问题了

### ISSUE THREAD

**Issue by fitzhang** [deanxv/coze-discord-proxy#186]
平常在频道对话的过程中，每次回答完毕以后，机器人都带了三个的问题扩展提示的，但是今天中午的时候机器人突然没有提示了，进去coze里面排查以下机器人，里面的机器人也是有提示的，问题是没有了这个提示以后，response = requests.post(url, headers=headers, json=data, timeout=timeout)  response一直无法获取完整的信息，系统默认没有提示即为问题没有回复完毕，一直再等待无法结束。请deanxv大神看看有什么办法解决。谢谢！
![没有提示问题](https://github.com/deanxv/coze-discord-proxy/assets/65891578/5c721930-74ea-48d2-96c6-d22b35eeaa78)

**Comment by fitzhang** [comment]
response = requests.post(url, headers=headers, json=data, timeout=timeout)
    response.raise_for_status()
    response_json = response.json()
    content = response_json['choices'][0]['message']['content']
    return response_json
    程序一直等待回复超时报错
    
![Uploading 没有提示问题2.png…]()

**Comment by fitzhang** [comment]
![没有提示问题2](https://github.com/deanxv/coze-discord-proxy/assets/65891578/d8d2c796-4e7f-4e77-9b3e-66775af22920)

**Comment by deanxv** [comment]
一个discord用户一天只能生成100次suggestion

**Comment by fitzhang** [comment]
那么有没有办法可以解决程序一直在等待服务器的问题，服务器没有返回response，一直在等待，求救

**Comment by deanxv** [comment]
> 那么有没有办法可以解决程序一直在等待服务器的问题，服务器没有返回response，一直在等待，求救

用另外的discord账号，或参考文档中的多用户配置。
