### ISSUE TITLE
希望作者能增加无suggestions版本

### ISSUE THREAD

**Issue by fitzhang** [deanxv/coze-discord-proxy#189]
suggestions对于我们需要GPT回复的情况下没啥用途，而且Discord也有限制生成.......
或者能否增加某个参数，控制是否需要回复suggestions，不需要的情况下直接回复答案即可

**Comment by deanxv** [comment]
用不到就不取用这个字段不就完了，响应体中你用到什么就拿什么就可以了，用不到就不用管

**Comment by deanxv** [comment]
你应该是误以为响应体中的suggestions影响了回复。

目前的项目中判断Coze-Bot响应完成的条件是是否在discord中生成了suggestions，如果没有生成的话服务无法知道何时Bot已经完成了响应，所以Coze-Bot在discord中尽量要生成suggestions。如果因为你的discord用户一天的生成次数已满或其他原因，那就如你上个issue中我的建议: 更换discord账号或配置多用户或第二天再请求，也可以修改请求超时时间，但需要你熟悉项目文档并知晓一定的项目原理。

**Comment by fitzhang** [comment]
请问作者如果希望修改读取回复时候的请求超时时间，可以在那个文件中设置？好像是config，但是这里设置应该会引起输出报错信息而已，另外discord.go 和processmessage.go  、sendmessage.go这三个文件好像都没有看得出那个是读取机器人回复消息的，求作者赐教。谢谢！

import (
	"coze-discord-proxy/common/env"
	"os"
	"strings"
	"time"
)

var ProxySecret = os.Getenv("PROXY_SECRET")
var ProxySecrets = strings.Split(os.Getenv("PROXY_SECRET"), ",")
var AllDialogRecordEnable = os.Getenv("ALL_DIALOG_RECORD_ENABLE")
var RequestOutTime = os.Getenv("REQUEST_OUT_TIME")
var StreamRequestOutTime = os.Getenv("STREAM_REQUEST_OUT_TIME")
var SwaggerEnable = os.Getenv("SWAGGER_ENABLE")
var OnlyOpenaiApi = os.Getenv("ONLY_OPENAI_API")
var MaxChannelDelType = os.Getenv("MAX_CHANNEL_DEL_TYPE")

**Comment by fitzhang** [comment]
> 你应该是误以为响应体中的suggestions影响了回复。
> 
> 目前的项目中判断Coze-Bot响应完成的条件是是否在discord中生成了suggestions，如果没有生成的话服务无法知道何时Bot已经完成了响应，所以Coze-Bot在discord中尽量要生成suggestions。如果因为你的discord用户一天的生成次数已满或其他原因，那就如你上个issue中我的建议: 更换discord账号或配置多用户或第二天再请求，也可以修改请求超时时间，但需要你熟悉项目文档并知晓一定的项目原理。

请问作者如果希望修改读取回复时候的请求超时时间，可以在那个文件中设置？好像是config，但是这里设置应该会引起输出报错信息而已，另外discord.go 和processmessage.go 、sendmessage.go这三个文件好像都没有看得出那个是读取机器人回复消息的，求作者赐教。谢谢！

**Comment by deanxv** [comment]
> 请问作者如果希望修改读取回复时候的请求超时时间，可以在那个文件中设置？好像是config，但是这里设置应该会引起输出报错信息而已，另外discord.go 和processmessage.go  、sendmessage.go这三个文件好像都没有看得出那个是读取机器人回复消息的，求作者赐教。谢谢！
> 
> 
> 
> import (
> 
> 	"coze-discord-proxy/common/env"
> 
> 	"os"
> 
> 	"strings"
> 
> 	"time"
> 
> )
> 
> 
> 
> var ProxySecret = os.Getenv("PROXY_SECRET")
> 
> var ProxySecrets = strings.Split(os.Getenv("PROXY_SECRET"), ",")
> 
> var AllDialogRecordEnable = os.Getenv("ALL_DIALOG_RECORD_ENABLE")
> 
> var RequestOutTime = os.Getenv("REQUEST_OUT_TIME")
> 
> var StreamRequestOutTime = os.Getenv("STREAM_REQUEST_OUT_TIME")
> 
> var SwaggerEnable = os.Getenv("SWAGGER_ENABLE")
> 
> var OnlyOpenaiApi = os.Getenv("ONLY_OPENAI_API")
> 
> var MaxChannelDelType = os.Getenv("MAX_CHANNEL_DEL_TYPE")

你的很多问题在项目Readme中都有解释，Readme中有文档地址，有环境变量解释，还有各种配置方案，请认真看完再提问。
