### ISSUE TITLE
更多的link提取

### ISSUE THREAD

**Issue by wrhsd1** [deanxv/coze-discord-proxy#19]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**

大佬 有些回复的超链接的url能不能也单独提取出来
例如capcut的链接 现在是在content中用文本显示，希望能将链接的url提取出来放到embedUrls:

**Comment by deanxv** [comment]
可以麻烦给我一个discord和集成的对话面板的问答示例截图吗？
晚点我复现一下研究研究

**Comment by deanxv** [comment]
> ![3](https://github.com/deanxv/coze-discord-proxy/assets/16531553/0bd85988-f3e7-4b4f-bb06-78337455cff1)
> 
> ![2](https://github.com/deanxv/coze-discord-proxy/assets/16531553/7d91fdc1-68c5-4ffe-94db-9796567230d8)
> 
> ![1](https://github.com/deanxv/coze-discord-proxy/assets/16531553/7c6e17e7-cdaa-4de2-ba70-bf9885b5f974)
> 
> 我的意思是返回的这种的带超链接的 也能提取到embedUrls中 
> 
> 感谢大佬回复

个人感觉这个不属于嵌入url，嵌入url这个字段是传递discord中的嵌入元素，比如图片、按钮等等。示例里的是discord返回的内容，内容中存在了markdown格式的图片，将这个图片url提取出来放入嵌入url参数中，感觉不太合适。

你尝试可以使用正则来提取content中的markdown格式的url。

**Comment by wrhsd1** [comment]
好的 感谢回复
