### ISSUE TITLE
config error,check logs

### ISSUE THREAD

**Issue by onlinedear** [deanxv/coze-discord-proxy#191]
在NextChat里测试返回的结果是500
```
{
  "error": {
    "message": "config error,check logs",
    "type": "request_error",
    "param": "",
    "code": "500"
  }
}
```

部署的接口地址：gpt.ai-api.com.cn

安装文档的提示，api文档地址为：https://gpt.ai-api.com.cn/swagger/index.html

在docker的日志中，报错信息如下：

`[GIN] 2024/05/19 - 10:50:30 | 20240519105030473126266Hyz9xhTj | 204 | 4.536948ms | 115.193.202.111 | OPTIONS /v1/chat/completions
[ERR] 2024/05/19 - 10:50:30 | 202405191050305218965233mnxL5nB | HTTP 404 Not Found, {"message": "Unknown Guild", "code": 10004}
[GIN] 2024/05/19 - 10:50:30 | 202405191050305218965233mnxL5nB | 500 | 278.197929ms | 115.193.202.111 | POST /v1/chat/completions
[GIN] 2024/05/19 - 10:50:30 | 202405191050308421896651zlN1vAu | 204 | 18.632µs | 115.193.202.111 | OPTIONS /v1/chat/completions
[GIN] 2024/05/19 - 10:50:31 | 20240519105030882546878THzDmnk2 | 500 | 264.366884ms | 115.193.202.111 | POST /v1/chat/completions
[ERR] 2024/05/19 - 10:50:31 | 20240519105030882546878THzDmnk2 | HTTP 404 Not Found, {"message": "Unknown Guild", "code": 10004}`

**Comment by deanxv** [comment]
环境变量GUILD_ID配置有误

**Comment by onlinedear** [comment]
> 环境变量GUILD_ID配置有误

感谢，已经搞好了
