### ISSUE TITLE
增加对windows的需求 

### ISSUE THREAD

**Issue by 1522526209** [deanxv/coze-discord-proxy#192]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [yes ] 我已确认目前没有类似 issue
+ [yes ] 我已确认我已升级到最新版本
+ [yes ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [yes ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
对windows 提供支持 可以在windows上运行 
![7143365d73c2a2a7dcde2507977954bb](https://github.com/deanxv/coze-discord-proxy/assets/138223000/b2cb509b-5666-4838-9f28-d52ca515f194)
我已经看到了  但是呢 他貌似不识别  那么对于环境变量来说 那么我应该放哪儿呢  win PATH环境变量 ?
我希望能改成 xml json之类的 这样也能直接分开 只需要读取本地的配置文件 互不影响

**Comment by deanxv** [comment]
1. Windows也可以安装docker环境用来容器化部署服务。

2. Windows执行exe时可以指定临时环境变量，可以自行搜索相关资料。

**Comment by 1522526209** [comment]
Set命令 ?
