### ISSUE TITLE
多机器人/并发/会话隔离等问题

### ISSUE THREAD

**Issue by YouYouLip** [deanxv/coze-discord-proxy#193]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [√ ] 我已确认目前没有类似 issue
+ [√] 我已确认我已升级到最新版本
+ [√] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [√] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
方便大佬知道我的病症，我先做一个问题总结

- 我试过了独立频道，这会导致开启新聊天等功能无法使用，需要亲自去discord的频道给机器人用/clear命令
- 我试过了不删除频道，这会导致每次的对话都会在一个新的子频道进行，无法连串上下文
- 我试过了5s删除频道，结果也是会导致每一个对话在一个新的频道进行，无法连串上下文

（以下是详细一点的废话）
此项目我只是和朋友2个人使用，小量并发，并且2个人都配备了文档中的多机器人，独立频道，但是问题也在这里了，朋友玩酒馆，我是用nextchat，为了防止串会话，我设置了独立频道，但是设置独立频道之后nextchat的开启新聊天并不会真正的重新开启，而是还在那一个频道上，酒馆并不知道，大概也会把？毕竟环境配置锁定了默认的频道，如果想去正常开启新的会话的话，那环境配置里的5s删除频道对于酒馆来说好像有点问题，这会导致酒馆角色每次对话都会重复同一句，nextchat我也试过了，创建子频道的话也会导致上下文丢失，如果我设置不删除的话，每次对话都会创建一个新频道，还是一样的上下文丢失

**复现步骤**
只需对话即可
**预期结果**
是否有解决办法解决现在的这种问题吗，（我不是很懂代码，所以有些话的发言可能无法实现，外加现在一夜未眠，容易胡言乱语，但是希望我的话有可能会提到一些可以执行的点上）比如说
- 在独立频道上调整修改，所有用户的消息默认从独立频道发送，但是如果用户发送的消息APIkey不一样的话就新建一个子频道把这个频道定向到那个APIkey上（因为我注意到，调用的用户token是随机的，如果不定向的话大概还会进行串会话等操作吧）
- 在不删除频道上做调整的话 那就是锁定子频道的ID或者名称，所有用户会话定向在这里，还是和APIkey一样，不同的话就新建一个频道锁定另一个人的APIkey
- 在删除频道上做更改（我怎么感觉好像这方面改不了呢，因为我发现频道内的会话好像就代表上下文记忆了，如果新建一个频道就是新会话了）
- 当然我感觉问题最大的应该是，在高并发/多人的情况下 发送内容的用户是随机的，（等等，更多的应该是第三方和discord不是很兼容以及此项目不是很成熟等问题吧）如果不及时删除或者，会导致另一个用户的字串过来这个频道，并且AI会读取上下文给出迷惑性的回复

好像不知道还有什么问题了，先写这么多吧）

**Comment by YouYouLip** [comment]
说真的，我都怀疑大佬你能不能看懂我的话了，因为我感觉我的话毫无逻辑，我都看不懂我自己的话

**Comment by deanxv** [comment]
可能你对于项目的内部实现原理还是有一些误解。

环境变量不指定频道的话，每次对话都会新建频道，而新建频道并不代表每次对话没有基于原有的上下文，你可以自行测试下，比如第一次发起问题"你是谁？"，第二次发起问题"我刚刚问了什么问题？"即可验证对话是否关联了上下文。

我感觉你的误会主要是在于:新建频道=新会话

但实际上:新建频道≠新会话

**Comment by YouYouLip** [comment]
> 可能你对于项目的内部实现原理还是有一些误解。
> 
> 环境变量不指定频道的话，每次对话都会新建频道，而新建频道并不代表每次对话没有基于原有的上下文，你可以自行测试下，比如第一次发起问题"你是谁？"，第二次发起问题"我刚刚问了什么问题？"即可验证对话是否关联了上下文。
> 
> 我感觉你的误会主要是在于:新建频道=新会话
> 
> 但实际上:新建频道≠新会话

大佬 我测试了一下，新频道就是新会话了，我给您看2张截图
![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/3274dc23-c5fa-4976-baac-6a7d9664e481)

![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/e0d2f79a-4577-442a-b699-f196afe1d030)

这是我在coze上随便找的一个模型测试，应该没有开启长会话记忆，我的也是

**Comment by YouYouLip** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/1bf39f7f-80ad-4d42-875f-dcbb3a671d1e)
![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/a41ce25b-e001-4072-8330-63919b24da04)
这是两张图的全貌区别

**Comment by deanxv** [comment]
> > 可能你对于项目的内部实现原理还是有一些误解。
> 
> > 
> 
> > 环境变量不指定频道的话，每次对话都会新建频道，而新建频道并不代表每次对话没有基于原有的上下文，你可以自行测试下，比如第一次发起问题"你是谁？"，第二次发起问题"我刚刚问了什么问题？"即可验证对话是否关联了上下文。
> 
> > 
> 
> > 我感觉你的误会主要是在于:新建频道=新会话
> 
> > 
> 
> > 但实际上:新建频道≠新会话
> 
> 
> 
> 大佬 我测试了一下，新频道就是新会话了，我给您看2张截图
> 
> ![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/3274dc23-c5fa-4976-baac-6a7d9664e481)
> 
> 
> 
> ![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/e0d2f79a-4577-442a-b699-f196afe1d030)
> 
> 
> 
> 这是我在coze上随便找的一个模型测试，应该没有开启长会话记忆，我的也是

使用CDP服务的对话接口请求，不要直接在discord的频道中对话。

**Comment by YouYouLip** [comment]
> > > 可能你对于项目的内部实现原理还是有一些误解。
> > 
> > 
> > > 
> > 
> > 
> > > 环境变量不指定频道的话，每次对话都会新建频道，而新建频道并不代表每次对话没有基于原有的上下文，你可以自行测试下，比如第一次发起问题"你是谁？"，第二次发起问题"我刚刚问了什么问题？"即可验证对话是否关联了上下文。
> > 
> > 
> > > 
> > 
> > 
> > > 我感觉你的误会主要是在于:新建频道=新会话
> > 
> > 
> > > 
> > 
> > 
> > > 但实际上:新建频道≠新会话
> > 
> > 
> > 大佬 我测试了一下，新频道就是新会话了，我给您看2张截图
> > ![image](https://private-user-images.githubusercontent.com/119958263/331941251-3274dc23-c5fa-4976-baac-6a7d9664e481.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzkxOTYsIm5iZiI6MTcxNjE3ODg5NiwicGF0aCI6Ii8xMTk5NTgyNjMvMzMxOTQxMjUxLTMyNzRkYzIzLWM1ZmEtNDk3Ni1iYWFjLTZhN2Q5NjY0ZTQ4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNDIxMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTY0MDE1MzZjMWU0MDUwM2UxOTMyMjYxMzFlNWJjMDFhMDdlM2QxYWY1NTE4Njg2ODFlY2JhMmI1YTg5MjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lYRhG-WCJUsJAuMImo6nzSrnQDgv28-NoEuy3W3w4xA)
> > ![image](https://private-user-images.githubusercontent.com/119958263/331941276-e0d2f79a-4577-442a-b699-f196afe1d030.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzkxOTYsIm5iZiI6MTcxNjE3ODg5NiwicGF0aCI6Ii8xMTk5NTgyNjMvMzMxOTQxMjc2LWUwZDJmNzlhLTQ1NzctNDQyYS1iNjk5LWYxOTZhZmUxZDAzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNDIxMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzUwNjIwMmQzYzc2YTgzYTBmNGNjYTkwZTljNjFkMjVlODY4MWViMWY1NGM5MzY3NjY1ZWNhZDY0ZGFjMTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MgGkZzEwx0jyONI8yB5_pqzGG-xltuqTkAskdNNtfLY)
> > 这是我在coze上随便找的一个模型测试，应该没有开启长会话记忆，我的也是
> 
> 使用CDP服务的对话接口请求，不要直接在discord的频道中对话。

我在nextchat上测试是此结果
![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/da8c518b-e94d-489a-8b4b-d73bdfb64862)

是否和我的接口有问题？因为我是用Windows上的dockerdesktop部署的此项目，由于有点笨）用的内网穿透ngrok代替的接口地址，也是可以正常申请的

**Comment by deanxv** [comment]
提供部署的版本和环境变量配置

**Comment by YouYouLip** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/9c2a58ad-d0de-4fb1-b8b3-ccfae2feb842)
我配置的环境变量有以下几个，用户的token 监听机器人的token 服务器ID 响应机器人ID 频道ID 还有APIkey
USER_AUTHORIZATION
BOT_TOKEN
GUILD_ID
COZE_BOT_ID
CHANNEL_ID
PROXY_SECRET
还载入了这个
![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/8d7186f9-990b-4d09-8019-9264d8fedee4)

**Comment by deanxv** [comment]
coze的模型更改为GPT4-8k或者128k重新发布

**Comment by YouYouLip** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/792ad578-9f46-48a6-9bb1-2038170117d7)
以上我重新发布后的GPT4-8k给出的回应
以下是128k的回应
![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/7686ba87-a4c9-4454-b222-fae32eb28d63)

**Comment by YouYouLip** [comment]
这是我发布时的设置，看了一下往期的issues，问题出现过最多的好像就是这2个，但是我没开启，另一个和我相似的就是那个长上下文功能
![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/5a37d4c2-cf07-491a-b0fe-4b976719ea3a)
![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/ad4aedae-9ae1-47c2-9aee-1bc32aef49fd)

**Comment by YouYouLip** [comment]
有个有意思的发现，在之前那个人issues里说开启了长上下文功能会导致换频道也会继承之前的记忆，是伪会话隔离这种意思，原因是开了长上下文，但是现在的我即便是打开了长上下文功能他还是会失忆（huh？傻掉了）
![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/dfe30cb7-e9bb-464b-b026-dc6dfb9d8031)
我这边也是openai的请求接口格式
![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/94a8deb3-9078-4d68-a104-5ee33ade3a6d)

**Comment by deanxv** [comment]
> 有个有意思的发现，在之前那个人issues里说开启了长上下文功能会导致换频道也会继承之前的记忆，是伪会话隔离这种意思，原因是开了长上下文，但是现在的我即便是打开了长上下文功能他还是会失忆（huh？傻掉了）
> 
> ![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/dfe30cb7-e9bb-464b-b026-dc6dfb9d8031)
> 
> 我这边也是openai的请求接口格式
> 
> ![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/94a8deb3-9078-4d68-a104-5ee33ade3a6d)
> 
> 
> 
> 补充：我发现了用nextchat进行对话时，频道应该在设置中的5秒后删除，但是这个子频道一直都还在（持续了大概一分钟，貌似是没有活动后主动删除的？）但是申请对话的时候却是创建了新的频道，我并没有添加不删除频道的这个环境变量，好怪（）

和这两个没有关系，请求后打开discord查看对话，你就明白为什么每个频道不是新对话了。

**Comment by YouYouLip** [comment]
如果我的智商在线的话，应该是因为调用的用户token不一致，是随机的导致每次都临时申请了新的频道这种情况吧）

**Comment by deanxv** [comment]
> 如果我的智商在线的话，应该是因为调用的用户token不一致，是随机的导致每次都临时申请了新的频道这种情况吧）

并不是，你还是误解了项目的原理

**Comment by deanxv** [comment]
每次对话都会新建频道，频道内会包含请求体内messages的所有内容，当这次请求完成响应，频道会删除。如果出现了各种问题那大概率就是调用时的参数有问题。

**Comment by YouYouLip** [comment]
> 每次对话都会新建频道，频道内会包含请求体内messages的所有内容，当这次请求完成响应，频道会删除。如果出现了各种问题那大概率就是调用时的参数有问题。

抱歉，我有点学艺不精，考虑的不是很全面，在我的理解看来是那种情况的，如果不是的话那我就换个角度思考吧（）所以大佬的意思是大概率还是我的环境变量或者其他的有问题？如果是的我话我在自己研究研究吧）

**Comment by deanxv** [comment]
> > 每次对话都会新建频道，频道内会包含请求体内messages的所有内容，当这次请求完成响应，频道会删除。如果出现了各种问题那大概率就是调用时的参数有问题。
> 
> 
> 
> 抱歉，我有点学艺不精，考虑的不是很全面，在我的理解看来是那种情况的，如果不是的话那我就换个角度思考吧（）所以大佬的意思是大概率还是我的环境变量或者其他的有问题？如果是的我话我在自己研究研究吧）

1.在NextChat发起对话，截图
2.在discord中查看新的频道中的对话信息，截图

**Comment by YouYouLip** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/eb9cd72e-53fb-491c-976a-915364f6c376)
![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/a4f257c4-e172-4315-811e-8cddeac8013d)
![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/60db15e7-72dc-4e4a-89be-db342d3afe28)
![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/60689bb3-b408-41f9-b916-4adefae1803d)

这个样子可以吗）我记得我昨天和前天并没有此情况，是在我配置了多机器人APIkey之后出现的好像

**Comment by deanxv** [comment]
1. 两次对话是否在同一NextChat的对话窗口下
2. 如果是，检查这里的历史附带消息数量
<img width="887" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/57529708/d5b991c0-b669-4932-9764-e7d74d983873">
3. 今日使用模型总数量是否达到了100次？（此问题与上述问题无关联）

**Comment by YouYouLip** [comment]
是同一对话窗口下，而且我的历史消息附带数是0
模型总量这个我不清楚，因为我有多个用户....）

**Comment by deanxv** [comment]
> 是同一对话窗口下，而且我的历史消息附带数是0 模型总量这个我不清楚，因为我有多个用户....）

1. 历史消息附带数代表了NextChat对话时传递的上下文数量，你选择了0自然就代表NextChat每次对话不会传递上下文。

2. discord中bot的响应未生成如下的suggestion的话会影响返回的结束流的判断，建议多配置几个USER_AUTH。

**Comment by YouYouLip** [comment]
> > 是同一对话窗口下，而且我的历史消息附带数是0 模型总量这个我不清楚，因为我有多个用户....）
> 
> 1. 历史消息附带数代表了NextChat对话时传递的上下文数量，你选择了0自然就代表NextChat每次对话不会传递上下文。
> 2. discord中bot的响应未生成如下的suggestion的话会影响返回的结束流的判断，建议多配置几个USER_AUTH。
> 
> <img alt="image" width="925" src="https://private-user-images.githubusercontent.com/57529708/331961261-3c72b376-bf0b-44e4-84a1-3b7b73c3de3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODU4MzQsIm5iZiI6MTcxNjE4NTUzNCwicGF0aCI6Ii81NzUyOTcwOC8zMzE5NjEyNjEtM2M3MmIzNzYtYmYwYi00NGU0LTg0YTEtM2I3YjczYzNkZTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2MTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NjkyMTA2MWNlMzEwOGVhZGU3MWVmNjcyM2JmNWZkOGY4MzAzZGNiNTczNTNmMTM4NDJlNTcxZjQ1N2FkMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.myTXsfIxFnq4c1h-NvJv1i22hlUoVHJiv2DougpYLMc">

可以了，谢谢开发者大佬愿意花费可以午休的时间来进行指导，那我想问一下，如果酒馆没有类似于nextchat的传递上下文的功能的话，是不是酒馆还是会出现这种问题

**Comment by deanxv** [comment]
> > > 是同一对话窗口下，而且我的历史消息附带数是0 模型总量这个我不清楚，因为我有多个用户....）
> > 
> > 
> > 
> > 1. 历史消息附带数代表了NextChat对话时传递的上下文数量，你选择了0自然就代表NextChat每次对话不会传递上下文。
> > 2. discord中bot的响应未生成如下的suggestion的话会影响返回的结束流的判断，建议多配置几个USER_AUTH。
> > 
> > <img alt="image" width="925" src="https://private-user-images.githubusercontent.com/57529708/331961261-3c72b376-bf0b-44e4-84a1-3b7b73c3de3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODU4MzQsIm5iZiI6MTcxNjE4NTUzNCwicGF0aCI6Ii81NzUyOTcwOC8zMzE5NjEyNjEtM2M3MmIzNzYtYmYwYi00NGU0LTg0YTEtM2I3YjczYzNkZTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2MTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NjkyMTA2MWNlMzEwOGVhZGU3MWVmNjcyM2JmNWZkOGY4MzAzZGNiNTczNTNmMTM4NDJlNTcxZjQ1N2FkMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.myTXsfIxFnq4c1h-NvJv1i22hlUoVHJiv2DougpYLMc">
> 
> 可以了，谢谢开发者大佬愿意花费可以午休的时间来进行指导，那我想问一下，如果酒馆没有类似于nextchat的传递上下文的功能的话，是不是酒馆还是会出现这种问题 （好吧我感觉我自己好像在问废话，不带的话肯定是不行，有点脑子蒙了 抱歉）

不清楚你说的酒馆是哪个项目，但只要是适配了openai的接口自然就会支持上下文的功能
