### ISSUE TITLE
在 ChatGPT-Next-Web使用时，总是显示正在输入 （已按【必看】常见疑难杂症导航中配置相应权限，问题依旧存在）

### ISSUE THREAD

**Issue by 80imike** [deanxv/coze-discord-proxy#194]
在 ChatGPT-Next-Web使用时，总是显示正在输入，但在discord里看是回复完了，回到NextChat还是显示正在输入

（已按【必看】常见疑难杂症导航中配置相应权限，问题依旧存在）

**Comment by deanxv** [comment]
截图discord中的回复

**Comment by 80imike** [comment]
> 截图discord中的回复

感谢回复 问题已解决，有一 bot 权限设置时忘记保存了。
