### ISSUE TITLE
Zeabur使用了一段时间就要收费了，呜呜呜

### ISSUE THREAD

**Issue by fitzhang** [deanxv/coze-discord-proxy#195]
face-frown
升级方案以继续
你已经使用完了 Serverless 方案中附赠的所有免费资源，你需要升级方案以继续使用 Zeabur 。否则你的服务将会被自动暂停并无法再部署新的服务
呜呜呜呜呜呜呜呜呜呜呜呜，我还以为能一直免费使用的。。。。。。。。。

**Comment by deanxv** [comment]
几乎没有可以白嫖的容器化部署平台

**Comment by liuliuDog** [comment]
我也是，转到render上了，不过render不能多机器人
