### ISSUE TITLE
为什么我按照这个方法接入微信bot之后，在微信里跟bot对话，但是微信里收不到回复，回复是在discord里的？

### ISSUE THREAD

**Issue by zhaolu1206** [deanxv/coze-discord-proxy#197]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
两个Bot是否按照文档站中的第7步开启权限

**Comment by zhaolu1206** [comment]
是开启两个bot的管理员权限吧？都开了

**Comment by deanxv** [comment]
> 是开启两个bot的管理员权限吧？都开了
> 
> ![image](https://github.com/deanxv/coze-discord-proxy/assets/30510452/b023d0b8-7a1b-4fac-adbf-6ac421f30e44)
> 
> 是在这个里面给管理员权限吧？

按照文档站的第7步开启

**Comment by zhaolu1206** [comment]
好的，谢谢，我今天再试试

**Comment by zhaolu1206** [comment]
> > 是开启两个bot的管理员权限吧？都开了
> > ![image](https://private-user-images.githubusercontent.com/30510452/333786075-b023d0b8-7a1b-4fac-adbf-6ac421f30e44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Njc3MzAsIm5iZiI6MTcxNjc2NzQzMCwicGF0aCI6Ii8zMDUxMDQ1Mi8zMzM3ODYwNzUtYjAyM2QwYjgtN2ExYi00ZmFjLWFkYmYtNmFjNDIxZjMwZTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDIzNTAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MjFiNmU1OWVmY2MxODJhMjUwNDdjYmJlZTQxOWM4YWViMjZlYzI0OTIzYzcyM2U5ZWIxN2Q2MWZlZDEyNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tvn7EIBLKDqwrUzFexY9tBa6VtFKP61ijRgL2P7w5ZM)
> > 是在这个里面给管理员权限吧？
> 
> 按照文档站的第7步开启

大佬，我全部按照文档教程走了一遍，还是在微信里发问bot只会在discord里回复

**Comment by flyinsz** [comment]
同样的问题，流程都走了一遍了

**Comment by flyinsz** [comment]
找到解决办法了，是cdp-bot的Privileged Gateway Intents三个选项没有打开
