### ISSUE TITLE
奇怪的USER_AUTHORIZATION EXPIRED

### ISSUE THREAD

**Issue by am-abudu** [deanxv/coze-discord-proxy#198]
在配置了多用户来规避限制时，机器人对程序创建的会话依然提示Some error occurred. Please try again or contact the support team in our communities。但当使用此用户直接在主频道AT机器人对话时没有此问题，可以正常使用。怀疑是风控升级

**Comment by deanxv** [comment]
1. 日志EXPIRED代表该Auth已过期或失效。
2. 目前Coze有bug，开启suggestion的情况下，同一用户使用当天使用100次后会报错。

**Comment by am-abudu** [comment]
请问过期是指这个authorization在discord不可用还是说coze使用次数达到限制？我确认这个authorization可以在主频道中调用bot，但不能在程序唤起的会话中调用

**Comment by deanxv** [comment]
> 请问过期是指这个authorization在discord不可用还是说coze使用次数达到限制？我确认这个authorization可以在主频道中调用bot，但不能在程序唤起的会话中调用

过期或者失效的意思就是不能用了，就是你需要重新获取你这个discord用户的authorization重新配置，具体怎么失效的去文档站中获取authorization的步骤中查看有关提示。
