### ISSUE TITLE
[Feature Request] 添加/v1/models路由

### ISSUE THREAD

**Issue by Dawnnnnnn** [deanxv/coze-discord-proxy#199]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
增加/v1/models路由，适配下游应用

**应用场景**
有些下游应用调用openai服务时，会按照openai原生规范请求/v1/models接口，目前不存在该接口，导致下游应用无法正常工作

**Comment by deanxv** [comment]
后续优化

**Comment by deanxv** [comment]
4.5.0已支持
