### ISSUE TITLE
使用Powershell或C#代码调用部署在render的服务无法获取回复

### ISSUE THREAD

**Issue by ichat001** [deanxv/coze-discord-proxy#200]
coze国际版官方调用API只有免费100次, 几个回合下来就用尽了, 后来在油管搜索到相关视频并找到该项目, 也按下面链接的教程成功部署在了render
https://www.dqzboy.com/16532.html

将render部署后得到的域名和coze获到的token设置到下面链接的nextChat中, 也能正常聊天
https://ci.goeast.io/#/

但是当我使用下面的Powershell代码或等效的C#代码调用coze机器人时, 出现了如下的情况:
1.在discord网页端可以成功看到新开了会话, 机器人有响应并正确的回复, 
2.但在powershell(powershell7)代码或C#代码端就一直处于等待状态了, 也不显示回复的消息, 只能把程序强制关闭

另外, 我还有一个问题就是:
能否支持 "conversation_id" 会话ID参数, 这在大模型中非常普遍, 即: 同一会话ID下支持多轮会话, 且保持上下文

我使用下面链接的Coze官方的curl代码也能成功调用机器人进行正常会话
https://www.coze.com/docs/developer_guides/chat?_lang=zh

我使用该项目的主要目标是在C#或Powershell中进行调用多轮会话
请求路过大佬解惑, 非常感谢

**Comment by deanxv** [comment]
1. Render部署的服务15分钟没有请求就会休眠。
2. 接口是和openai对齐的，不需要考虑其他，上下文正常在messages数组中传递。

**Comment by ichat001** [comment]
> 1. Render部署的服务15分钟没有请求就会休眠。
> 2. 接口是和openai对齐的，不需要考虑其他，上下文正常在messages数组中传递。

感谢大佬神速的回复, 
1.应该不是休眠的问题
2. 我使用chatgpt的代码也尝试了很多, 但是仍然一直等待, 无法获取回复

**Comment by deanxv** [comment]
> > 1. Render部署的服务15分钟没有请求就会休眠。
> 
> > 2. 接口是和openai对齐的，不需要考虑其他，上下文正常在messages数组中传递。
> 
> 
> 
> 感谢大佬神速的回复, 
> 
> 1.应该不是休眠的问题
> 
> 2. 我使用chatgpt的代码也尝试了很多, 但是仍然一直等待, 无法获取回复

大概率没有打开Auto-suggestion，重新参考文档站的教程发布cozebot

**Comment by ichat001** [comment]
> > > 1. Render部署的服务15分钟没有请求就会休眠。
> > 
> > 
> > > 2. 接口是和openai对齐的，不需要考虑其他，上下文正常在messages数组中传递。
> > 
> > 
> > 感谢大佬神速的回复,
> > 1.应该不是休眠的问题
> > 
> > 2. 我使用chatgpt的代码也尝试了很多, 但是仍然一直等待, 无法获取回复
> 
> 大概率没有打开Auto-suggestion，重新参考文档站的教程发布cozebot

感谢, 大佬威武, 还真是没开 Auto-suggestion, 我认为机器人下这个功能应该用不上, 就特意关了, 没想到就掉坑里了

**Comment by ichat001** [comment]
> 1. Render部署的服务15分钟没有请求就会休眠。

再问一下: Render部署的服务15分钟没有请求就会休眠。
大佬推荐哪个免费的, 没有这个休眠问题或更好的网站?  zeabur 有类似限制吗

**Comment by deanxv** [comment]
> > 1. Render部署的服务15分钟没有请求就会休眠。
> 
> 
> 
> 再问一下: Render部署的服务15分钟没有请求就会休眠。
> 
> 大佬推荐哪个免费的, 没有这个休眠问题或更好的网站?  zeabur 有类似限制吗

目前没有完全免费的容器化部署平台，zeabur试用期过了需要开通5刀的月付计划

**Comment by ichat001** [comment]
> 1. Render

感谢提醒, 
我经过多次测试发现, 多轮会话后, 回复有时就文不对题了, 有时会把前面的答案重复, 但是前几轮就没事, 我是对接的模拟操作PC版微信, 大佬有相关的调用代码参考吗

**Comment by deanxv** [comment]
> > 1. Render
> 
> 
> 
> 感谢提醒, 
> 
> 我经过多次测试发现, 多轮会话后, 回复有时就文不对题了, 有时会把前面的答案重复, 但是前几轮就没事, 我是对接的模拟操作PC版微信, 大佬有相关的调用代码参考吗

使用4系列模型
