### ISSUE TITLE
无法正常生成图片

### ISSUE THREAD

**Issue by am-abudu** [deanxv/coze-discord-proxy#201]
在尝试调用API生成图片时，出现Some error occurred. Please try again or contact the support team in our communities.
如果直接使用Discord在主频道中尝试调用则没有问题

![程序生成会话频道的调用结果](https://github.com/deanxv/coze-discord-proxy/assets/51912589/97e76e9c-1a00-4c67-a3e6-151a51f4312a)

上图为程序生成会话频道的调用结果

![直接使用网页版Discord在主频道AT机器人的调用结果](https://github.com/deanxv/coze-discord-proxy/assets/51912589/767e611d-5f64-4f56-9525-aa8e0d740d88)

上图为直接使用网页版Discord在主频道AT机器人的调用结果

并且，在出现这个问题后程序会出现一段时间的卡死

**Comment by deanxv** [comment]
发起请求后提供discord的截图

**Comment by am-abudu** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/51912589/cb23b9c3-76b9-4e05-923e-810cd68ccaea)
上图为发起请求后discord的截图

![image](https://github.com/deanxv/coze-discord-proxy/assets/51912589/04e96364-2b69-444b-a60d-620f2da20e59)
上图为直接使用网页版Discord在主频道AT机器人的调用结果

**Comment by am-abudu** [comment]
尝试进行别的绘画也会出现问题

![image](https://github.com/deanxv/coze-discord-proxy/assets/51912589/c5c0cea1-c17f-42bf-9834-cf5aaee42aee)

**Comment by deanxv** [comment]
这些都是同一个discord账号？

**Comment by am-abudu** [comment]
相同昵称的都是同一个账号，并且我可以确定均未达到50次/天的限制

**Comment by deanxv** [comment]
换bot试试

**Comment by am-abudu** [comment]
请问是需要尝试更换receive bot还是coze bot，或是同时更换两个bot

**Comment by deanxv** [comment]
Coze发布新的bot

**Comment by am-abudu** [comment]
更换Bot后可以正常生成图像
