### ISSUE TITLE
chatnext里面输入问题，discord回复的是语音，请问这种可以获得回复吗，如果无法获得，怎么让回复文字

### ISSUE THREAD

**Issue by azz212** [deanxv/coze-discord-proxy#202]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [ Y] 我已确认目前没有类似 issue
+ [ Y] 我已确认我已升级到最新版本
+ [ Y] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ Y] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
见标题
**复现步骤**
coze的机器人选的插件比较多
**预期结果**
获得语音或者文字回复
**相关截图**
![Screenshot_20240601_170639_com.discord.jpg](https://user-images.githubusercontent.com/33420910/335790593-05278a8a-34f2-4a8b-b647-204fea621672.jpg)
![Screenshot_20240601_171020_com.chrome.beta.jpg](https://user-images.githubusercontent.com/33420910/335790722-79a68587-45b2-44f5-b092-3b2fc12b6eac.jpg)
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
coze发布发布机器人之前把voice关掉

**Comment by azz212** [comment]
请问能获得语音回复吗？如果能获得，那不是很多IM软件都支持语音了

**Comment by deanxv** [comment]
> 请问能获得语音回复吗？如果能获得，那不是很多IM软件都支持语音了

openai官方提供语音接口了吗？IM软件支持集成openai官方的语音接口吗？

**Comment by azz212** [comment]
不是OPENAI，比如微信的hook,可以发语音，主要是能否获取discord的语音，是什么格式的啊？

**Comment by deanxv** [comment]
> 不是OPENAI，比如微信的hook,可以发语音，主要是能否获取discord的语音，是什么格式的啊？

这个项目主要是为了对齐openai接口，如果你需要个性化接口，可以二次开发。
