### ISSUE TITLE
无法正常识别图片

### ISSUE THREAD

**Issue by flyinsz** [deanxv/coze-discord-proxy#203]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
从discord上传图片后无法正常识别图片，识别出来的内容和实际没有关联。
**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
discord上传图片无法识别请找coze官方反馈

**Comment by flyinsz** [comment]
> discord上传图片无法识别请找coze官方反馈

原来如此。不知道反馈渠道，算了，等官方自行修复吧，这么大一个bug

**Comment by deanxv** [comment]
其实是可以的，需要开启相关插件，但需要你自行研究下。

**Comment by flyinsz** [comment]
解决了，正确加载了gpt-4v插件后解决
