### ISSUE TITLE
python (openai) 调用报错

### ISSUE THREAD

**Issue by ly2164** [deanxv/coze-discord-proxy#204]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
感谢大佬！我小白，前面的安装过程一步一步认真跟下来还算顺利，目前nextchat、discord、swagger接口、docker日志均正常。
但用openai的python代码直接调用遇到麻烦：
（1）如不设地址，则报错key不对。
（2）如地址设为“http://127.0.0.1:7077”，则报404网页不存在。
我翻看了其它类似Issues，还没有针对此疑问的直接解答。自己各种尝试也都不行，可否请大佬指点一句，多谢多谢！

**相关截图**
![捕获](https://github.com/deanxv/coze-discord-proxy/assets/86272554/8cfdaf5c-a99a-44ea-ae26-7daeae366505)

**Comment by deanxv** [comment]
http://127.0.0.1:7077/v1
