### ISSUE TITLE
当通过代码随机调用多机器人PROXY_SECRET时，是否多个discord用户的授权密钥会随机选择？

### ISSUE THREAD

**Issue by ly2164** [deanxv/coze-discord-proxy#205]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
请教大佬！一步步做下来，我的情况和疑问如下：

已设置多个Discord账号，用户的授权密钥均有效，单独测试dock-compose.yml启动docker均有效。
已设置多个Discord服务器上的Coze-Bot，单独测试调用均正常。
已设置bot_config.json文件，单独测试调用均正常。

疑问1：
用代码，每次从PROXY_SECRET池中每次随机选出一个发包时（截屏如下），discord授权密钥池是否也会自动随机选择一个？
疑问2：
用nextchat，如何实现从PROXY_SECRET池中随机选择？
![屏幕截图 2024-06-04 105624](https://github.com/deanxv/coze-discord-proxy/assets/86272554/d8c65e23-c5b6-4dc7-89a9-ad0538f9a10a)

**Comment by deanxv** [comment]
1. 当你你在openai的后台新建多个key的时候，你也能用任意一个key去调用所有的key吗？那多个key还有什么意义呢？多个key只是为了分发给每个用户，每个用户用自己的key去bot_config中匹配自己的key对应的bot信息。
2. nextchat本身就支持在api-key参数中用`,`分隔多个key用来负载，其他项目具体的使用细节可以去对应的文档查询或社区询问下，毕竟各个项目的作者精力有限。

**Comment by ly2164** [comment]
多谢大佬的指点，我之前还是对项目不完全理解，现在又明白一些！
