### ISSUE TITLE
coze上其他人的bot，加入到我自己的discord后，如何调用

### ISSUE THREAD

**Issue by azz212** [deanxv/coze-discord-proxy#206]
**温馨提示: 未`star`项目会被自动关闭issue哦!**
你好，coze上其他人的bot，加入到我自己的discord后，如何调用，另外，如果每个机器人负责的内容不同，如何将不同的请求让不同的机器人处理，不是负载均衡，只是区分不同的功能，比如画图只让某一个机器人处理
**例行检查**

+ [ Y] 我已确认目前没有类似 issue
+ [ Y] 我已确认我已升级到最新版本
+ [ Y] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ Y] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
你好，coze上其他人的bot，加入到我自己的discord后，如何调用，另外，如果每个机器人负责的内容不同，如何将不同的请求让不同的机器人处理，不是负载均衡，只是区分不同的功能，比如画图只让某一个机器人处理
**应用场景**
处理不同请求使用不同机器人，更专业，更合理

**Comment by deanxv** [comment]
1. 邀请其他bot加入你的discord服务器后右键该机器人获取它的COZE_BOT_ID，不清楚怎么获取可以自行谷歌获取Discord用户ID。

2. 配置多机器人利用模型区分调用，参考文档站相关教程，这里不做赘述。

**Comment by azz212** [comment]
谢谢大佬指点，这2个应该能搞定，那coze上的很多机器人都能用了啊：）
