### ISSUE TITLE
请教服务出错原因：Some error occurred. Please try again or contact the support team in our communities.

### ISSUE THREAD

**Issue by Gijela** [deanxv/coze-discord-proxy#207]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
昨天开始无法获得回答。

<img width="708" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/82071209/3afa9431-39ec-46d0-8ce5-85340e60a334">
<img width="805" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/82071209/bb0a70ac-c9d2-42c2-a0aa-422e832e820d">

**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by y1713375484** [comment]
我也是出现这个问题了，4个机器人里3个都这样了
<img width="1079" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/80376536/ab8c8a33-a724-4660-b87e-57d02a5c710b">

**Comment by deanxv** [comment]
Coze官方昨日加了限制，发布Bot时的名称及描述中不可包含GPT相关内容，之前所有违规的Bot全部被停用，在Coze里新建合规的Bot重新发布

**Comment by y1713375484** [comment]
> Coze官方昨日加了限制，发布Bot时的名称及描述中不可包含GPT相关内容，之前所有违规的Bot全部被停用，在Coze里新建合规的Bot重新发布
discord中的机器人不用删了重新建吧

**Comment by deanxv** [comment]
> > Coze官方昨日加了限制，发布Bot时的名称及描述中不可包含GPT相关内容，之前所有违规的Bot全部被停用，在Coze里新建合规的Bot重新发布
> > discord中的机器人不用删了重新建吧
不需要

**Comment by Gijela** [comment]
> Coze官方昨日加了限制，发布Bot时的名称及描述中不可包含GPT相关内容，之前所有违规的Bot全部被停用，在Coze里新建合规的Bot重新发布

感谢大佬赐教，确实是这个问题

**Comment by GoTop** [comment]
如何查看coze里哪个bot因为不符合规定被禁了？

我的几个bot状态都是绿色的圆圈带着小钩

我直接修改这些bot的名称和描述，使其不出现gpt字符串，可以么？
