### ISSUE TITLE
请教大佬，在图片和提示词一起输出的时候，能获取到提示词吗？

### ISSUE THREAD

**Issue by azz212** [deanxv/coze-discord-proxy#208]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [Y ] 我已确认目前没有类似 issue
+ [ Y] 我已确认我已升级到最新版本
+ [ Y] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ Y] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
大佬，在请求图片的时候，coze和discord会生成一段文字，如果调用的是工作流，有些bot还会对你的输入优化提示词，然后提示词和图片一起输出，还有一种情况是bot认为你输入的不够详细，需要你再次描述你的提示词。然后再输入才能继续画图，请问这种在调用图片接口的时候能获取到提示词文字，或者让继续输入的文字吗？
如下这种：

視覺需求與用途
畫面描述：美女在做瑜伽
用途：健身攝影展的海報
中文prompt:
設計一個高解析度的圖片，畫面重點是一位美女在做瑜伽。背景應該是現代化的健身房內部，日光從落地窗透射進來，打出柔和的自然光線。瑜伽墊上有精緻的紋理細節，人物的姿勢是高難度的瑜伽動作，表現出強烈的身體線條感和平衡感。整體色調應該偏向中性色與自然色，避免過於鮮豔的色彩，以提升圖片的專業與高級感。整張圖片應具備出色的細節與真實感，光影效果需精巧，背景不應過於擁擠，以突出瑜伽動作及人物的美感。
英文prompt:
Create a high-resolution image focusing on a beautiful woman doing yoga. The background should be a modern gym interior with sunlight streaming through floor-to-ceiling windows, casting soft natural light. The yoga mat features intricate texture details, and the woman is in a high-difficulty yoga pose, emphasizing strong body lines and balance. The overall color tone should lean towards neutral and natural hues, avoiding overly bright colors to maintain a professional and upscale feel. The entire image should have exceptional detail and realism, with precise light and shadow effects. The background should not be too cluttered, allowing the yoga pose and the woman's beauty to stand out.
然后给出图片链接
**应用场景**
提示词优化+输出图片的场景，当然提示词获取到也用处不大。主要是提示词不够，无法画图的时候

**Comment by deanxv** [comment]
v4.5.3 已支持。
<img width="1079" alt="111222333" src="https://github.com/deanxv/coze-discord-proxy/assets/57529708/9c2bc120-5d14-4d29-a225-123c8e227eb6">
