### ISSUE TITLE
终端可以请求到数据，但是 nextchat 在浏览器没有响应

### ISSUE THREAD

**Issue by caoler** [deanxv/coze-discord-proxy#209]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
<img width="1444" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/26300971/15be1bf7-d6d6-46e8-b2e8-4942f80d9593">
终端可以请求到数据，但是 nextchat 在浏览器没有响应
**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
去文档站-常见问题里找解决方案

**Comment by caoler** [comment]
用域名反代了一下就好了
