### ISSUE TITLE
代理不完全

### ISSUE THREAD

**Issue by czyt** [deanxv/coze-discord-proxy#21]
可以请求，机器人也将我的消息发给coze机器人了，但是后续报错 
```
2024/01/31 13:25:23 [DG0] wsapi.go:82:Open() error connecting to gateway wss://gateway.discord.gg/?v=9&encoding=json, dial tcp [2a03:2880:f11f:83:face:b00c:0:25de]:443: i/o timeout
[FATAL] 2024/01/31 - 13:25:23 | [error opening connection, dial tcp [2a03:2880:f11f:83:face:b00c:0:25de]:443: i/o timeout]
```
我怀疑是代理设置不完全，参考discordgo这个库的issue
https://github.com/bwmarrin/discordgo/issues/852

**Comment by deanxv** [comment]
收到 晚些会验证

**Comment by XinShuichen** [comment]
可以先这样加在environment里验证. 我这边测可以了.

      - HTTP_PROXY=socks5://192.168.1.112:7891
      - HTTPS_PROXY=socks5://192.168.1.112:7891
      - ALL_PROXY=socks5://192.168.1.112:7891

       @czyt
