### ISSUE TITLE
api调用传入discord服务器整个 [ ] api参数，gpt-4o无法图片使用

### ISSUE THREAD

**Issue by Mr-XiaoYi** [deanxv/coze-discord-proxy#210]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
1. 在第三方调用接口的时候discord服务器内容貌似是不对的，整个【】内的参数直接被传入了
2. 调用gpt4o模型传入图片时，在discord服务器中上传图片正常回答，第三方例nextchat中使用会回答无法使用链接，我看频道猜测可能是第一个问题导致第二个问题出现
**复现步骤**
任何时候调用openai api复现——；第一张为此bug执行步骤之一——；第二张是直接在discord艾特coze的回答——；第三张是docker传入部分参数——；

**预期结果**
第三方平台调 用api gpt-4o图片正常识别正常回答
**相关截图**
![a8f3842239a1f7b8efe0493beabe3b6](https://github.com/deanxv/coze-discord-proxy/assets/67035205/83e4035f-d950-4f23-9394-df3fbb258f91)
![7f73da94c481ab8cfa88e2e1df0f290](https://github.com/deanxv/coze-discord-proxy/assets/67035205/fb7dce4a-c5de-4a46-8dbf-0f872a029680)
![4e8ef8f538a8b16ce0ff2e9a6a911c6](https://github.com/deanxv/coze-discord-proxy/assets/67035205/c8cc01a9-7bb7-4311-8ce0-94cef73390e5)

**Comment by deanxv** [comment]
1. 项目原理就是把整个json传入让gpt4理解上下文。

2. 你自己在discord发送图片是将图片作为附件传入，而cdp服务是将图片转为url，而目前默认的4o模型对图片url识别不出来，需要开启linkreader插件。

**Comment by Mr-XiaoYi** [comment]
我尝试了coze插件，gpt4v会介绍图片识别效果会更好，记录，关闭问题，感谢回答
