### ISSUE TITLE
The conversation title couldn't be correctly generated on Nextchat. 

### ISSUE THREAD

**Issue by 2ndMessiah** [deanxv/coze-discord-proxy#211]
Hi deanxv,

Thx for the effort u put into this awesome project!!

I'm not really sure if it's proper to open this issue here or on Nextchat's repo..But I decided to have a try here but you could definitely shut it down if it's irrelevant with coze-discord-proxy!! Kudos!

I found the titles are not generated on nextchat as shown below(I'm sure the 'auto-generate title' option is on on nextchat):
![image](https://github.com/deanxv/coze-discord-proxy/assets/22229188/5a568ab3-32ec-41fc-b3af-869f1bb434ef)

But this works with Openai API which I was using until today...

Please suggest some possible factors that might affect this function.

Thx again!!

ps:
Some built-in options:
![image](https://github.com/deanxv/coze-discord-proxy/assets/22229188/19a09a8a-a266-42ff-bc61-9314b5678bfe)
![image](https://github.com/deanxv/coze-discord-proxy/assets/22229188/5c193901-eaaf-495a-aba0-fc0be281f0c1)

**Comment by deanxv** [comment]
Open and observe the service log to check if an OPTION type request for v1/chat/completions is logged when initiating a request in NextChat.

**Comment by 2ndMessiah** [comment]
> Open and observe the service log to check if an OPTION type request for v1/chat/completions is logged when initiating a request in NextChat.

Thx for the reply!!

Knowing little about frontend, I found some failed requests to /completions every time I sent a prompt after a while:
![image](https://github.com/deanxv/coze-discord-proxy/assets/22229188/b1425171-118b-42f8-81e0-cfb64ec29ba9)
I reversed the service via Cloudflare tunnel. Is it the possible reason behind this?

Thx.

**Comment by deanxv** [comment]
What contents are contained within the body of this request's response?

**Comment by 2ndMessiah** [comment]
> What contents are contained within the body of this request's response?

I got some hints here:
![image](https://github.com/deanxv/coze-discord-proxy/assets/22229188/98613526-dd61-44ca-be59-d59d8a54e7f0)

Nextchat made a gpt3.5 request at the same time as the gpt4(my default) request... Is this used to summarize the title? omg.. I didn't configure the 3.5 model in the env parameters..

**Comment by 2ndMessiah** [comment]
> What contents are contained within the body of this request's response?

omg it's revealed 
![image](https://github.com/deanxv/coze-discord-proxy/assets/22229188/854f7168-f30c-44a2-aa75-62b1a00fc0a7)

**Comment by deanxv** [comment]
response，not payload

**Comment by 2ndMessiah** [comment]
> response，not payload

matched 
![image](https://github.com/deanxv/coze-discord-proxy/assets/22229188/9136c70d-a3ec-4628-abbb-d4ed161480e8)

**Comment by deanxv** [comment]
This is why the title wasn't summarized. NextChat uses the 3.5 model when requesting title summaries, which cannot be changed. However, your service likely uses a multi-bot configuration, but has not configured the 3.5 model.

**Comment by 2ndMessiah** [comment]
Appreciate your patience!!
