### ISSUE TITLE
增加 自动继续/continue 功能

### ISSUE THREAD

**Issue by human4real** [deanxv/coze-discord-proxy#212]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**

希望能增加一个`CONTINUE_TIMES`环境变量，在结束流之前，先对`auto-suggestions`进行检测，如果其中含有 `continue` 时，根据设置的非负整数值进行透明自动继续。如：

- 设置为0时，不自动继续
- 设置为1时，进行一次自动继续
- 设置为2时，进行两次自动继续

**应用场景**

在需要输出大段代码或者长篇文章的场景下，

- 由于discord回复的字数限制，coze-bot的回复易被截断，需发送一次甚至多次“继续”才能回答完整。
- 如果是openai api的话，设置max_tokens为4096，遇到这种情况的概率就比较小，基本能一次性回答完整。

所以希望可以增加 透明自动continue功能 来持平max_tokens=4096的api使用体验，根据设置的`CONTINUE_TIMES`非负整数值，决定进行几次透明continue。

**Comment by YouYouLip** [comment]
比起这个，我感觉现在问题最明显的问题其中之一确实是discord的回复字数限制，一次只能回复2000个字符，但实际上的话，我感觉即便是加了自动继续的功能也持平不了“所谓的4096响应长度”因为目前来说，如果做不到单次输出的字符始终都是一次性瞬发的话，而是靠分段发送，那你每次通过自动继续所带来的始终都是discord的最大响应长度而不是coze的最大响应长度，也就是说，单纯是discord的锅，再说甚至可以自己发送继续让机器人发送之后的片段，目前最严重的问题应该是使用的过程中达不到coze的最大上下文，比如说coze的Gemini模型都是200k上下文，但是实际上此项目搭配discord的话是做不到跑200k上下文的，因为每次都是分段发送，一次只能输出2000个字符，导致机器人并不会先响应而是先分段发送信息，确保消息发送完之后开始at机器人来把前面发送过的话充当全文，首先最大的问题就是每次的响应时间会大大增加，导致体验上会比较差，再就是你说的在进行大段代码和长篇文章的场景下的需求会更依赖token

**Comment by YouYouLip** [comment]
举个例子就是
在coze的文档上标注了100token≈150个汉字，也就是说1400token≈2000个字符，以中文计算的是这样
那如果说，采用自动继续的话，你每次申请的始终都是在1400token基础上申请，而不是4096token，因为4096token进行到1400token的时候就已经被掐了，采用自动继续也是一样的死循环，即便是持平也做不到，如果discord的字数无限制的话，你每次接受到的都是完整的4096token的响应长度，因为在有限制的基础上，你只能1400token，中间的差距会越拉越远，我个人觉得自动继续的功能其实是没什么太大用的，有用的前提是你无法通过其他手段来让机器人继续输出，
discord这边限制做的，把coze的机器人弄成了，上下文是残血的，响应长度是残血的，响应时间也是残血的（在官网和discord的响应速度明显官网快，不知道谁的锅）总体程度上甚至比不上官网的50%感觉

**Comment by deanxv** [comment]
> 举个例子就是
> 
> 在coze的文档上标注了100token≈150个汉字，也就是说1400token≈2000个字符，以中文计算的是这样
> 
> 那如果说，采用自动继续的话，你每次申请的始终都是在1400token基础上申请，而不是4096token，因为4096token进行到1400token的时候就已经被掐了，采用自动继续也是一样的死循环，即便是持平也做不到，如果discord的字数无限制的话，你每次接受到的都是完整的4096token的响应长度，因为在有限制的基础上，你只能1400token，中间的差距会越拉越远，我个人觉得自动继续的功能其实是没什么太大用的，有用的前提是你无法通过其他手段来让机器人继续输出，
> 
> 此项目搭配discord的话，会把coze的机器人弄成，上下文是残血的，响应长度是残血的，响应时间也是残血的，想要响应时间的话，上下文就要进行切割，想要大量上下文的话，响应时间就兼具不了了（在官网和discord的响应速度明显官网快，不知道谁的锅）总体程度上甚至比不上官网的50%感觉（但是实际上你直接去discord那边私信机器人的话，跟官网也差不了多少，感觉还是discord的这个字数限制导致此拓展项目不太好弄）

这个项目本身流式响应下几乎没什么延迟的，至于上下文这个问题，我和群友之前测试过(当时coze多轮对话最大仅支持30)，项目中采用的分段发送消息策略可以让bot一次至少理解2w-3w字，但目前coze多轮对话已最大调整为100，也就是说上下文最大可以支持超过128k的token也就是差不多18w的字符。
硬要说由于discord单条消息长度限制衍生出的问题的话，我感觉应该是discord bot的响应有可能被coze预设了prompt的让其尽量长度在2000字符内，但在群友的使用反馈下，出现超长响应时结尾会以省略号代替，通过发送"继续"让其继续响应。

至于为什么不做自动发送"继续"的逻辑，一个原因是比较麻烦，个人精力实在有限。第二个原因是这个功能不应该给这个服务内部实现，我们自己在openai官网使用或者调用官方api时也会出现因为响应长度到了限制只回答了一半的场景，难道这时候我们也要去让官方内部实现自动发送"继续"吗？这个不应该作为二次开发来实现吗？

**Comment by deanxv** [comment]
至于为什么不做自动发送"继续"的逻辑，一个原因是比较麻烦，个人精力实在有限。第二个原因是这个功能不应该给这个服务内部实现，我们自己在openai官网使用或者调用官方api时也会出现因为响应长度到了限制只回答了一半的场景，难道这时候我们也要去让官方内部实现自动发送"继续"吗？这个不应该作为二次开发来实现吗？

**Comment by YouYouLip** [comment]
> > 举个例子就是
> > 在coze的文档上标注了100token≈150个汉字，也就是说1400token≈2000个字符，以中文计算的是这样
> > 那如果说，采用自动继续的话，你每次申请的始终都是在1400token基础上申请，而不是4096token，因为4096token进行到1400token的时候就已经被掐了，采用自动继续也是一样的死循环，即便是持平也做不到，如果discord的字数无限制的话，你每次接受到的都是完整的4096token的响应长度，因为在有限制的基础上，你只能1400token，中间的差距会越拉越远，我个人觉得自动继续的功能其实是没什么太大用的，有用的前提是你无法通过其他手段来让机器人继续输出，
> > 此项目搭配discord的话，会把coze的机器人弄成，上下文是残血的，响应长度是残血的，响应时间也是残血的，想要响应时间的话，上下文就要进行切割，想要大量上下文的话，响应时间就兼具不了了（在官网和discord的响应速度明显官网快，不知道谁的锅）总体程度上甚至比不上官网的50%感觉（但是实际上你直接去discord那边私信机器人的话，跟官网也差不了多少，感觉还是discord的这个字数限制导致此拓展项目不太好弄）
> 
> 这个项目本身流式响应下几乎没什么延迟的，至于上下文这个问题，我和群友之前测试过(当时coze多轮对话最大仅支持30)，项目中采用的分段发送消息策略可以让bot一次至少理解2w-3w字，但目前coze多轮对话已最大调整为100，也就是说上下文最大可以支持超过128k的token也就是差不多18w的字符。 硬要说由于discord单条消息长度限制衍生出的问题的话，我感觉应该是discord bot的响应有可能被coze预设了prompt的让其尽量长度在2000字符内，但在群友的使用反馈下，出现超长响应时结尾会以省略号代替，通过发送"继续"让其继续响应。

流式响应确实没有延迟，和discord那边接受到的是同步可以说是，最大的问题是在进行传递时，如果历史对话足够多，选的传递会话也多且都是原文发送的话，就会出现响应慢的情况了，比如说，我的上下文长度在200k或者100k，那么我传递整条100k的信息的话就会出现，因为discord设置的单次输出最高2000字符的限制导致，是慢慢传递信息的，而不是一口气全部发送过去，测试的话，如果是过于多的上下文都要传递过去的话，大概要花费30s-60s的时间才能传递完，然后才是响应机器人（）感觉这个是真没办法弄

**Comment by YouYouLip** [comment]
> 至于为什么不做自动发送"继续"的逻辑，一个原因是比较麻烦，个人精力实在有限。第二个原因是这个功能不应该给这个服务内部实现，我们自己在openai官网使用或者调用官方api时也会出现因为响应长度到了限制只回答了一半的场景，难道这时候我们也要去让官方内部实现自动发送"继续"吗？这个不应该作为二次开发来实现吗？

是的，我也是这样认为的，毕竟可以自己手动发送继续让机器人继续响应，没有必要去做能用其他方式解决的事情，毕竟是无偿开源的项目

**Comment by deanxv** [comment]
> > > 举个例子就是
> 
> > > 在coze的文档上标注了100token≈150个汉字，也就是说1400token≈2000个字符，以中文计算的是这样
> 
> > > 那如果说，采用自动继续的话，你每次申请的始终都是在1400token基础上申请，而不是4096token，因为4096token进行到1400token的时候就已经被掐了，采用自动继续也是一样的死循环，即便是持平也做不到，如果discord的字数无限制的话，你每次接受到的都是完整的4096token的响应长度，因为在有限制的基础上，你只能1400token，中间的差距会越拉越远，我个人觉得自动继续的功能其实是没什么太大用的，有用的前提是你无法通过其他手段来让机器人继续输出，
> 
> > > 此项目搭配discord的话，会把coze的机器人弄成，上下文是残血的，响应长度是残血的，响应时间也是残血的，想要响应时间的话，上下文就要进行切割，想要大量上下文的话，响应时间就兼具不了了（在官网和discord的响应速度明显官网快，不知道谁的锅）总体程度上甚至比不上官网的50%感觉（但是实际上你直接去discord那边私信机器人的话，跟官网也差不了多少，感觉还是discord的这个字数限制导致此拓展项目不太好弄）
> 
> > 
> 
> > 这个项目本身流式响应下几乎没什么延迟的，至于上下文这个问题，我和群友之前测试过(当时coze多轮对话最大仅支持30)，项目中采用的分段发送消息策略可以让bot一次至少理解2w-3w字，但目前coze多轮对话已最大调整为100，也就是说上下文最大可以支持超过128k的token也就是差不多18w的字符。 硬要说由于discord单条消息长度限制衍生出的问题的话，我感觉应该是discord bot的响应有可能被coze预设了prompt的让其尽量长度在2000字符内，但在群友的使用反馈下，出现超长响应时结尾会以省略号代替，通过发送"继续"让其继续响应。
> 
> 
> 
> 流式响应确实没有延迟，和discord那边接受到的是同步可以说是，最大的问题是在进行传递时，如果历史对话足够多，选的传递会话也多且都是原文发送的话，就会出现响应慢的情况了，比如说，我的上下文长度在200k或者100k，那么我传递整条100k的信息的话就会出现，因为discord设置的单次输出最高2000字符的限制导致，是慢慢传递信息的，而不是一口气全部发送过去，测试的话，如果是过于多的上下文都要传递过去的话，大概要花费30s-60s的时间才能传递完，然后才是响应机器人（）感觉这个是真没办法弄

实际上是我对于分割后的消息加了间隔时间1s，分割20条就会有20s是白白浪费掉的。(之前没加，后来超长文本测试的时候发现在同一频道中discord对所有的消息发送有个速率限制，触发限制后会禁止发送消息10s左右，我尝试间隔0.5s还是会触发速率限制，就索性改成1s了)

**Comment by YouYouLip** [comment]
> > > > 举个例子就是
> > 
> > 
> > > > 在coze的文档上标注了100token≈150个汉字，也就是说1400token≈2000个字符，以中文计算的是这样
> > 
> > 
> > > > 那如果说，采用自动继续的话，你每次申请的始终都是在1400token基础上申请，而不是4096token，因为4096token进行到1400token的时候就已经被掐了，采用自动继续也是一样的死循环，即便是持平也做不到，如果discord的字数无限制的话，你每次接受到的都是完整的4096token的响应长度，因为在有限制的基础上，你只能1400token，中间的差距会越拉越远，我个人觉得自动继续的功能其实是没什么太大用的，有用的前提是你无法通过其他手段来让机器人继续输出，
> > 
> > 
> > > > 此项目搭配discord的话，会把coze的机器人弄成，上下文是残血的，响应长度是残血的，响应时间也是残血的，想要响应时间的话，上下文就要进行切割，想要大量上下文的话，响应时间就兼具不了了（在官网和discord的响应速度明显官网快，不知道谁的锅）总体程度上甚至比不上官网的50%感觉（但是实际上你直接去discord那边私信机器人的话，跟官网也差不了多少，感觉还是discord的这个字数限制导致此拓展项目不太好弄）
> > 
> > 
> > > 
> > 
> > 
> > > 这个项目本身流式响应下几乎没什么延迟的，至于上下文这个问题，我和群友之前测试过(当时coze多轮对话最大仅支持30)，项目中采用的分段发送消息策略可以让bot一次至少理解2w-3w字，但目前coze多轮对话已最大调整为100，也就是说上下文最大可以支持超过128k的token也就是差不多18w的字符。 硬要说由于discord单条消息长度限制衍生出的问题的话，我感觉应该是discord bot的响应有可能被coze预设了prompt的让其尽量长度在2000字符内，但在群友的使用反馈下，出现超长响应时结尾会以省略号代替，通过发送"继续"让其继续响应。
> > 
> > 
> > 流式响应确实没有延迟，和discord那边接受到的是同步可以说是，最大的问题是在进行传递时，如果历史对话足够多，选的传递会话也多且都是原文发送的话，就会出现响应慢的情况了，比如说，我的上下文长度在200k或者100k，那么我传递整条100k的信息的话就会出现，因为discord设置的单次输出最高2000字符的限制导致，是慢慢传递信息的，而不是一口气全部发送过去，测试的话，如果是过于多的上下文都要传递过去的话，大概要花费30s-60s的时间才能传递完，然后才是响应机器人（）感觉这个是真没办法弄
> 
> 实际上是我对于分割后的消息加了间隔时间1s，分割20条就会有20s是白白浪费掉的。(之前没加，后来超长文本测试的时候发现在同一频道中discord对所有的消息发送有个速率限制，触发限制后会禁止发送消息10s左右，我尝试间隔0.5s还是会触发速率限制，就索性改成1s了)

原来如此，我刚知道discord有消息速率限制这一回事，自己简单的测试了一下，刷屏过多会触发
![image](https://github.com/deanxv/coze-discord-proxy/assets/119958263/5a4d947e-2cc2-4712-b71b-4411baa62921)
貌似是因为待发送的消息达到上限了，待发送消息的队列处于6-8条，如果说有6-8条的消息仍然没发送出去的话，下一条消息就会突然弹出这个提示框，貌似是和自己的网速+魔法有关，测试的时候消息发送完毕的时间长短不一，而且只有当第一条消息发送完后才会处理第二条消息，有一种同步非异步的美了，感觉缓解信息传递过长的这个缺陷，
1.要么是采取随机间隔发送信息，数值取在（0.5s-1s之间内比较保守稳定）
2.要么就是前5次0s瞬发，后5次1s慢发这样一个循环操作
![b465273d2371d033ad4d366a4f11c37b](https://github.com/deanxv/coze-discord-proxy/assets/119958263/95d0d7fc-719f-4409-b612-14844223ca14)
