### ISSUE TITLE
freebsd构建搭建cozediscordproxy404

### ISSUE THREAD

**Issue by Aberion** [deanxv/coze-discord-proxy#213]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [✔ ] 我已确认目前没有类似 issue
+ [✔ ] 我已确认我已升级到最新版本
+ [✔ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [✔ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
自行build之后开启服务，postget都显示404,不知道什么原因，配置文件如下，目录如下
![PicsArt_06-20-11.18.00.jpg](https://github.com/deanxv/coze-discord-proxy/assets/65051091/c2b4d6da-9666-4e3a-9331-95cb2fe3c9bd)

![Screenshots_2024-06-20-11-15-21.png](https://github.com/deanxv/coze-discord-proxy/assets/65051091/01f7849a-1f9d-4eac-b2c0-6ab2e180405e)

![PicsArt_06-20-11.16.20.jpg](https://github.com/deanxv/coze-discord-proxy/assets/65051091/104a7999-1bcb-4076-b677-341c4d3dbc25)

![PicsArt_06-20-11.24.02.jpg](https://github.com/deanxv/coze-discord-proxy/assets/65051091/745b6ae7-c832-4393-92f3-30f8db741c9c)

**Comment by Aberion** [comment]
![PicsArt_06-20-11.27.23.jpg](https://github.com/deanxv/coze-discord-proxy/assets/65051091/d760dcc9-4a24-4c60-b713-db3f7fa4e5ff)

补一张cozebot权限图，并且已经上传coze

**Comment by changeCat** [comment]
路径重复了吧
![image](https://github.com/deanxv/coze-discord-proxy/assets/14162279/242b2422-9df9-4f2b-a6b4-21bda54159e7)

**Comment by deanxv** [comment]
就是路径重复了，对话面板的baseUrl多写了一段路由。

**Comment by Aberion** [comment]
![PicsArt_06-20-04.40.27.jpg](https://github.com/deanxv/coze-discord-proxy/assets/65051091/339ffe55-b989-42e2-8a9f-f7a5dbf7bb16)

![PicsArt_06-20-04.40.57.jpg](https://github.com/deanxv/coze-discord-proxy/assets/65051091/d909161f-27f9-4a81-96c1-7750f6c6b55c)

看看这个嘛

**Comment by deanxv** [comment]
ChannelId字段可传可不传，你要传那就得传个对的…

**Comment by Aberion** [comment]
500是内部错误，但是没有排查出来是啥，他报的errosending

**Comment by Aberion** [comment]
> ChannelId字段可传可不传，你要传那就得传个对的…

这样吗，我是直接复制的

**Comment by deanxv** [comment]
我是说你这个请求体里的"channelId:string"
这个是啥意思？

**Comment by Aberion** [comment]
> 我是说你这个请求体里的"channelId:string"
> 这个是啥意思？

最后一张图是主机的log

**Comment by deanxv** [comment]
你是不是没懂我说的请求体是啥意思…

**Comment by Aberion** [comment]
> 我是说你这个请求体里的"channelId:string"
> 这个是啥意思？

不好意思，刚看到

**Comment by Aberion** [comment]
> 你是不是没懂我说的请求体是啥意思…

不好意思，刚刚看到了，我这其实是swagger里面直接复制过来的，就没看那么多

**Comment by Aberion** [comment]
![Screenshot_20240620-181534.png](https://github.com/deanxv/coze-discord-proxy/assets/65051091/fc61f94e-0d04-4c98-95e5-1113a00b4e13)

大佬，这是咋回事啊，我填的接口是域名加端口加v1,一直报错不知道咋回事

**Comment by deanxv** [comment]
> ![Screenshot_20240620-181534.png](https://github.com/deanxv/coze-discord-proxy/assets/65051091/fc61f94e-0d04-4c98-95e5-1113a00b4e13)
> 
> 大佬，这是咋回事啊，我填的接口是域名加端口加v1,一直报错不知道咋回事

如果服务没日志就是你填错了，有日志就看日志

**Comment by Aberion** [comment]
> > ![Screenshot_20240620-181534.png](https://github.com/deanxv/coze-discord-proxy/assets/65051091/fc61f94e-0d04-4c98-95e5-1113a00b4e13)
> > 
> > 大佬，这是咋回事啊，我填的接口是域名加端口加v1,一直报错不知道咋回事
> 
> 如果服务没日志就是你填错了，有日志就看日志

没有的

**Comment by Aberion** [comment]
这个是fectch不到
![Screenshot_20240620-181942.png](https://github.com/deanxv/coze-discord-proxy/assets/65051091/f6ecc07a-1746-4ee2-acce-0c7b0de5a3bd)

**Comment by deanxv** [comment]
> > > ![Screenshot_20240620-181534.png](https://github.com/deanxv/coze-discord-proxy/assets/65051091/fc61f94e-0d04-4c98-95e5-1113a00b4e13)
> > > 
> > > 大佬，这是咋回事啊，我填的接口是域名加端口加v1,一直报错不知道咋回事
> > 
> > 如果服务没日志就是你填错了，有日志就看日志
> 
> 没有的

没有日志就说明没有请求到这个服务，这个服务无关，我也帮不到你。

**Comment by Aberion** [comment]
> > > > ![Screenshot_20240620-181534.png](https://github.com/deanxv/coze-discord-proxy/assets/65051091/fc61f94e-0d04-4c98-95e5-1113a00b4e13)
> > > > 
> > > > 大佬，这是咋回事啊，我填的接口是域名加端口加v1,一直报错不知道咋回事
> > > 
> > > 如果服务没日志就是你填错了，有日志就看日志
> > 
> > 没有的
> 
> 没有日志就说明没有请求到这个服务，这个服务无关，我也帮不到你。

好的谢谢大佬
