### ISSUE TITLE
当stream是false时，超时能不能把把discord里的内容返回？

### ISSUE THREAD

**Issue by reccea** [deanxv/coze-discord-proxy#214]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**

我的auto-suggestions是打开的，stream设置为false。但当bot的回答内容涉及网址url时，很多时候bot已经正常回答完成，但coze的没有回复auto-suggestions。（不是因为当天的auto-suggestions额度满的问题，这种情况时而发生，和额度无关。）导致程序取不到回复，但discord这边又是有正常答案的。
所以，能不能加个功能，在REQUEST_OUT_TIME超时的时候，即使没有auto-suggestions，也把当前discord回复的内容返回？

**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
检查自己的版本是否为最新

**Comment by reccea** [comment]
> 检查自己的版本是否为最新

是最新的，还是存在这个问题。

**Comment by deanxv** [comment]
> > 检查自己的版本是否为最新
> 
> 
> 
> 是最新的，还是存在这个问题。

提供截图
