### ISSUE TITLE
模型怎么选择

### ISSUE THREAD

**Issue by BaiJiang007** [deanxv/coze-discord-proxy#216]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
我在coze上发布的bot是gpt-4o模型，在coze使用没有问题。当我接入到discord时。它貌似变成了3.5模型，我直接使用CDP接口调用亦是如此。bot权限全开了，Auto-Suggtion为off
**复现步骤**

**预期结果**

**相关截图**
<img width="828" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/129240266/ea394234-2ec8-4044-8899-f5ec03a4d0db">

如果没有的话,请删除此节。

**Comment by deanxv** [comment]
在discord直接发送问题给Bot，看看是否与该答案一致，如果一致代表Bot模型发布时就出现了问题或者Coze出现了Bug，可以找Coze官方反馈。

**Comment by BaiJiang007** [comment]
那我找找Coze的问题，Issue先关了
