### ISSUE TITLE
https://cdp.aytsao.cn/v1/chat/completions 还能用吗？

### ISSUE THREAD

**Issue by 14790897** [deanxv/coze-discord-proxy#217]
![image](https://github.com/deanxv/coze-discord-proxy/assets/121866954/fbd5d977-b7e5-4915-82e3-e165aad23c11)

**Comment by deanxv** [comment]
不能了，coze推出了订阅收费，免费用户一天仅有1条的调用次数。

**Comment by azz212** [comment]
这个coze discord proxy 能不能增加代理的功能，直接连google的gemini，不走coze

**Comment by deanxv** [comment]
> 这个coze discord proxy 能不能增加代理的功能，直接连google的gemini，不走coze

那为什么不直接请求google的gemini？

**Comment by 14790897** [comment]
佬，项目还有希望吗？

**Comment by deanxv** [comment]
> 佬，项目还有希望吗？

可以用虚拟卡c新号三天试用
