### ISSUE TITLE
one-api+此项目openai格式调用v1/images/generations，返回的图片url打不开怎么解决

### ISSUE THREAD

**Issue by aicoder01** [deanxv/coze-discord-proxy#219]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**

{＇created＇: 1720080628, ＇dailyLimit＇: False, ＇data＇: [{＇url＇: ＇https://media.discordapp.net/attachments/1258333966281478205/1258334096808083536/14181354088232718336.png?ex=6687aa73&is=668658f3&hm=ddefa754838768ef9f89d7697f0336f001943c77463c113fd1d17231d797c389&＇, ＇revised_prompt＇: ＂Here is a minimalistic logo , ＇b64_json＇: ＇＇}], ＇suggestions＇: [＂Can you assist me in understanding the user＇s requirements for logo design?＂]}

**复现步骤**
one-api+此项目。调用v1/images/generations

**预期结果**
https://media.discordapp.net/attachments/1258333966281478205/1258334096808083536/14181354088232718336.png?ex=6687aa73&is=668658f3&hm=ddefa754838768ef9f89d7697f0336f001943c77463c113fd1d17231d797c389&
希望可以打开

**Comment by deanxv** [comment]
打不开是因为临时频道被删除了，需要在频道被删除前及时下载。

**Comment by aicoder01** [comment]
> 打不开是因为临时频道被删除了，需要在频道被删除前及时下载。

好的多谢，我这边返回消息之后马上下载就删除了，可以配置或者怎么操作把临时频道删除延迟吗，别删除这么快

**Comment by aicoder01** [comment]
另外补充下，之前是可以的，最近从coze收费后变成url拉不到的。国内服务器拉的图片url

**Comment by deanxv** [comment]
> > 打不开是因为临时频道被删除了，需要在频道被删除前及时下载。
> 
> 
> 
> 好的多谢，我这边返回消息之后马上下载就删除了，可以配置或者怎么操作把临时频道删除延迟吗，别删除这么快

有环境变量可以配置删除时间，可以查阅一下。

**Comment by deanxv** [comment]
> 另外补充下，之前是可以的，最近从coze收费后变成url拉不到的。国内服务器拉的图片url

因为coze现在更新了，有可能生成的图片的资源地址国内访问不了+频道删除后失效。

**Comment by aicoder01** [comment]
> > 另外补充下，之前是可以的，最近从coze收费后变成url拉不到的。国内服务器拉的图片url
> 
> 因为coze现在更新了，有可能生成的图片的资源地址国内访问不了+频道删除后失效。

好的，我试下

**Comment by aicoder01** [comment]
> > 另外补充下，之前是可以的，最近从coze收费后变成url拉不到的。国内服务器拉的图片url
> 
> 因为coze现在更新了，有可能生成的图片的资源地址国内访问不了+频道删除后失效。

确实原因是：图片的资源地址国内访问不了+频道删除后失效 
解决办法：加国外服务器代理+增大删除临时频道的时间

**Comment by aicoder01** [comment]
确实原因是：图片的资源地址国内访问不了+频道删除后失效
解决办法：加国外服务器代理+增大删除临时频道的时间
