### ISSUE TITLE
本项目中关于在discord平台发送信息的代码位置

### ISSUE THREAD

**Issue by cakota6462** [deanxv/coze-discord-proxy#221]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [x ] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
大佬好。之前就用您的项目搭了个接口，一直都是非常的稳定。最近coze收费了，接口也就寄了。前两天发现了个同样可以发布bot到discord上的平台，就试了下看能不能与您的项目兼容。

我发现这个平台的bot需要使用“/chatbotkit message:“命令来让bot响应，所以您的项目不出意外地无法兼容。经尝试，粘贴并发送“/chatbotkit message:你好”也能使bot响应。因此，我想试试修改发送信息的代码，将命令一同发送过去，从而让bot响应。

由于本人是个代码小白，今天尝试自己找了一下但没有找到，希望大佬能给指出关于在discord平台发送信息的代码位置，感激不尽！！！

**Comment by deanxv** [comment]
全局搜索 SendMsgByAuthorization

**Comment by cakota6462** [comment]
谢大佬
