### ISSUE TITLE
很好奇，coze提供的voice call 能否代理出来

### ISSUE THREAD

**Issue by a1667834841** [deanxv/coze-discord-proxy#225]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
![image](https://github.com/user-attachments/assets/47471538-4414-42f9-a6ad-cb0d968acde3)
![image](https://github.com/user-attachments/assets/4d5e72eb-ffb6-4842-a8ec-35206f1bde80)

**应用场景**
用于语音实时对话

**Comment by deanxv** [comment]
目前应该没有任何对话面板有规范的语音响应格式，所以即便代理出来了也用不了。
