### ISSUE TITLE
coze-discord-proxy未按照go modules要求处理module path

### ISSUE THREAD

**Issue by HappyHacker123** [deanxv/coze-discord-proxy#226]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
现在coze-discord-proxy使用go modules并且最新的release version是v4.6.2，但设置的module path是'`coze-discord-proxy`'，而按官方规则应该设置为'`github.com/deanxv/coze-discord-proxy/v4`', 可以看[官方文档](https://go.dev/wiki/Modules#releasing-modules-v2-or-higher)
```
A package that has opted in to modules must include the major version in the import path to import any v2+ modules. 
To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element.
For example, version v2.0.0 of example.com/m must instead use module path example.com/m/v2.
```
**复现步骤**
尝试用go get下载coze-discord-proxy时出错
```
root@iZj6c5flh0q5ax3d1ttfuhZ:~/temp/go-collectd# go get github.com/deanxv/coze-discord-proxy@v4.6.2
go: github.com/deanxv/coze-discord-proxy@v4.6.2: invalid version: module contains a go.mod file, so module path must match major version ("github.com/deanxv/coze-discord-proxy/v4")
```
**预期结果**
能够正常下载
**相关截图**
![图片](https://github.com/user-attachments/assets/673caa71-a713-48d5-8ccc-8b0144345865)

**解决措施**
修改module path以遵循Go Modules规范（推荐）

**Comment by deanxv** [comment]
该项目为后端服务，并非mod依赖或sdk项目。
