### ISSUE TITLE
自动活跃机器人功能异常

### ISSUE THREAD

**Issue by soulgod001** [deanxv/coze-discord-proxy#227]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
每日九点活跃机器人的任务发送消息时异常，以往只是发送失败就没有在意，确认过频道号是没问题的，在coze中可以看到直到10.23是有正常发送的。
以下为往常的日志：
[SYS] 2024/11/04 - 09:10:54 | CDP Scheduled Task Job Start!
[ERR] 2024/11/04 - 09:10:54 | UNKNOWN | error sending message: strconv.Atoi: parsing "": invalid syntax
[SYS] 2024/11/04 - 09:10:54 | ChannelId{1302802220160385076} BotId{1240309445142249522} 活跃机器人任务消息发送异常!

今天早上收到了coze的邮件提示api异常已自动重置CDPBot的token，看了一下服务日志发现昨天发送消息时报错导致服务自动重启然后重试，一直重试直到Token被重置开始报另一个错误。
以下是发送消息时的报错日志：
[SYS] 2024/11/06 - 09:05:06 | CDP Scheduled loadBotConfig Task Job Start!
[FATAL] 2024/11/06 - 09:05:06 | [Error parsing JSON: invalid character '/' looking for beginning of object key string]
[SYS] 2024/11/06 - 09:05:07 | COZE-DISCORD-PROXY v4.6.3 started
[FATAL] 2024/11/06 - 09:05:08 | [Error parsing JSON: invalid character '/' looking for beginning of object key string]
**复现步骤**
不太清楚怎么复现
**预期结果**
可以正常启动及活跃机器人

**Comment by deanxv** [comment]
看着应该是你的多机器人配置json内容格式有问题，不是标准的json格式

**Comment by soulgod001** [comment]
检查了一下确实是配置json有问题，我配到一半去忙别的就忘记了，我以为没重启容器就不会加载这个文件所以没想到是这个的问题。
修改json后可以正常启动了，能否正常活跃机器人暂未测试。
