### ISSUE TITLE
能否增加配置多个coze机器人的功能

### ISSUE THREAD

**Issue by siyu1234l** [deanxv/coze-discord-proxy#23]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**

**应用场景**

**Comment by deanxv** [comment]
已在开发中，预计明后天发版，可关注TG群。
