### ISSUE TITLE
请求失败

### ISSUE THREAD

**Issue by KasonWan** [deanxv/coze-discord-proxy#24]
**问题描述**
proxy-secret是正确的，也一直显示失败

**相关截图**
![1706839602040](https://github.com/deanxv/coze-discord-proxy/assets/58059719/eeafa93c-03e3-4393-9468-84f87b9d61ee)

**Comment by deanxv** [comment]
是否使用的swag？golang的swag有bug，请求头中有 - 不会传该参数，采用postman或apifox等工具调试下
