### ISSUE TITLE
使用模型名来指定bot

### ISSUE THREAD

**Issue by jzksnsjswkw** [deanxv/coze-discord-proxy#25]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
请求密钥应该用来鉴权，而不是用于分配具体的bot，这个功能应该由模型名来实现
**应用场景**
coze可以为bot定义提示词，使用模型名来区分不同的bot更为合适

**Comment by deanxv** [comment]
其实之前有想过，但如果用模型名来区分的话，当切换模型时，虽然会切换到指定模型的bot，但因为切换了bot，上下文会乱掉，上下文对于此项目来讲我感觉优先级很高。

毕竟对于discord bot代理服务来讲，想做到完全复刻官方接口难度极高，所以必须做出取舍。才设计为多用户情况下每个人一个key，通过key对应自己的bot和上下文频道。

再就是本身对于coze来讲，模型也只有三个，甚至还包含了openai目前不存在的模型，所以多次考虑后才如此设计。

**Comment by deanxv** [comment]
> > 其实之前有想过，但如果用模型名来区分的话，当切换模型时，虽然会切换到指定模型的bot，但因为切换了bot，上下文会乱掉，上下文对于此项目来讲我感觉优先级很高。
> 
> > 
> 
> > 毕竟对于discord bot代理服务来讲，想做到完全复刻官方接口难度极高，所以必须做出取舍。才设计为多用户情况下每个人一个key，通过key对应自己的bot和上下文频道。
> 
> > 
> 
> > 再就是本身对于coze来讲，模型也只有三个，甚至还包含了openai目前不存在的模型，所以多次考虑后才如此设计。
> 
> 
> 
> 单独为每个用户设置模型名对应的bot就行，其实并不冲突。单独加一个model字段，然后使用other或者all做回退就行。
> 
> 想过提pr但是对api不了解怕改错:(

是这样的，切换model会导致切换机器人，切换机器人会导致上下文乱掉。

**Comment by deanxv** [comment]
> > 其实之前有想过，但如果用模型名来区分的话，当切换模型时，虽然会切换到指定模型的bot，但因为切换了bot，上下文会乱掉，上下文对于此项目来讲我感觉优先级很高。
> 
> > 
> 
> > 毕竟对于discord bot代理服务来讲，想做到完全复刻官方接口难度极高，所以必须做出取舍。才设计为多用户情况下每个人一个key，通过key对应自己的bot和上下文频道。
> 
> > 
> 
> > 再就是本身对于coze来讲，模型也只有三个，甚至还包含了openai目前不存在的模型，所以多次考虑后才如此设计。
> 
> 
> 
> 单独为每个用户设置模型名对应的bot就行，其实并不冲突。单独加一个model字段，然后使用other或者all做回退就行。
> 
> 想过提pr但是对api不了解怕改错:(

这个需求并不是做不了，而且如果用户在页面中一个上下文中多次切换不同的机器人，在discord中会@不同的机器人，上下文被多个机器人分割开，而在页面中用户并无感知，他只会认为这是一套上下文，会产生更多的疑问。

这套服务中上下文并非由我们控制，全依靠discord的频道做隔离。没办法什么都兼容到，只能做出取舍的。

**Comment by jzksnsjswkw** [comment]
想着在nextchat上通过不同会话隔离的，有些问题确实没有考虑周全
