### ISSUE TITLE
请求问题

### ISSUE THREAD

**Issue by KasonWan** [deanxv/coze-discord-proxy#26]
**问题描述**
指定了频道ID，并没有在指定频道提问，而是在默认频道提问，没有使用openai接口

**相关截图**
![image](https://github.com/deanxv/coze-discord-proxy/assets/58059719/ec1507bf-c3bf-4b49-a31b-a2e4f1695d27)

**Comment by deanxv** [comment]
请问是配置多机器人吗？

**Comment by KasonWan** [comment]
> 请问是配置多机器人吗？

没有

**Comment by deanxv** [comment]
是未设置secret吗

**Comment by KasonWan** [comment]
> 是未设置secret吗

对的

**Comment by deanxv** [comment]
> > 是未设置secret吗
> 
> 
> 
> 对的

排查了一下是上次更新多机器人多频道时出现的bug，今天晚些会修复，多谢

**Comment by deanxv** [comment]
已修复 新镜像已推送

**Comment by KasonWan** [comment]
> 已修复 新镜像已推送

@机器人变成@频道号了

**Comment by deanxv** [comment]
> > 已修复 新镜像已推送
> 
> @机器人变成@频道号了

改错参数了 新镜像已推送
