### ISSUE TITLE
本项目的Java版本

### ISSUE THREAD

**Issue by oddfar** [deanxv/coze-discord-proxy#28]
地址：https://github.com/oddfar/coze-discord
使用SpringBoot3，也集成了Docker，功能目前如下
- 支持 api 方式调用
- 对话支持流式返回
- 支持对话指定 Discord 频道、子频道，实现对话隔离支
- 支持创建 Discord 频道、子频道、线程

**Comment by deanxv** [comment]
如果参考了本项目的话可否在文档中标识呢？

**Comment by oddfar** [comment]
已标识，感谢作者的付出

**Comment by deanxv** [comment]
> 已标识，感谢作者的付出

谢谢你! 祝你开心!
