### ISSUE TITLE
不用discord直接逆coze可以吗，discord有单条长度限制

### ISSUE THREAD

**Issue by think007** [deanxv/coze-discord-proxy#29]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
不用discord直接逆coze可以吗，discord有单条长度限制
**应用场景**
discord有单条长度限制

**Comment by deanxv** [comment]
> **例行检查**
> 
> 
> 
> + [ ] 我已确认目前没有类似 issue
> 
> + [ ] 我已确认我已升级到最新版本
> 
> + [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
> 
> + [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭
> 
> 
> 
> **功能描述**
> 
> 不用discord直接逆coze可以吗，discord有单条长度限制
> 
> **应用场景**
> 
> discord有单条长度限制

首先此项目非逆向项目，如果想直接逆向coze并实现对话隔离，难度相当于提高了一百倍。

目前在考虑是否要将超过2000字符的内容分段发送，但即便分段发送，中间被其他对话插入也会有上下文不连贯的风险。而且因为字符限制，coze托管的机器人给我们返回的内容最多也只会有2000字符。

不过目前也在调试将超过2000字的内容分段发送后的效果如何。

**Comment by deanxv** [comment]
请求消息长度增加至5000 更新最新镜像

**Comment by think007** [comment]
是分段发送吗，如果中间被其他对话插入也会有上下文不连贯的风险吗

**Comment by deanxv** [comment]
> 是分段发送吗，如果中间被其他对话插入也会有上下文不连贯的风险吗

会有 所以在多人使用时注意使用频道隔离。

**Comment by think007** [comment]
一个人一个频道？还是

**Comment by deanxv** [comment]
> 一个人一个频道？还是

如果是基于此服务二开的对话面板，设置对话请求体中的频道id参数即可，不用的时候删除。

如果是集成NextChat面板，利用多机器人配置每人一个secret对应一个(多个)机器人+一个频道

**Comment by think007** [comment]
如果对接one-api是不是得一人一个频道才能实现对话隔离

**Comment by deanxv** [comment]
> 如果对接one-api是不是得一人一个频道才能实现对话隔离

有几种方案：
1. 项目支持多secret，多配置[机器人-频道]，支持每个secret指定一个(多个)[机器人-频道]，相当于每个人使用不同的key调用了相同(不同)的[机器人-频道]。
2. 接入oneapi，启动一个(多个)服务，添加渠道，也是通过api-key(secret)指定了多[机器人-频道]中的任一个。

原理都一样，都是通过配置多[机器人-频道]，使用secret去指定，配置也很活，按照自己需求配置就可以。

**Comment by think007** [comment]
对接one-api：项目支持多secret，多配置[机器人-频道]，支持每个secret指定一个(多个)[机器人-频道]，相当于每个人使用不同的key调用了相同(不同)的[机器人-频道]。
有示例吗，看看

**Comment by deanxv** [comment]
> 对接one-api：项目支持多secret，多配置[机器人-频道]，支持每个secret指定一个(多个)[机器人-频道]，相当于每个人使用不同的key调用了相同(不同)的[机器人-频道]。 有示例吗，看看

ReadMe文档中就有，我没有时间将所有示例一一列出，根据自己的需求研究配置下
