### ISSUE TITLE
安装求助

### ISSUE THREAD

**Issue by cn0068** [deanxv/coze-discord-proxy#3]
两个bot开通对应权限(Send Messages,Read Message History等)并邀请进服务器,记录服务器ID(GUILD_ID) (过程不在此赘述)。

请问如何开通权限进服务器?查了一圈还是不太清楚

**Comment by deanxv** [comment]
可以参考下：https://juejin.cn/post/7219656530235473980

**Comment by cn0068** [comment]
再请问：Redirect URL 这个怎么填写？一定得有自己的服务器能访问的网址吗？服务器上如何设置？

**Comment by deanxv** [comment]
> 再请问：Redirect URL 这个怎么填写？一定得有自己的服务器能访问的网址吗？服务器上如何设置？

在哪里看到要设置这个的，项目中不需要用的。

**Comment by cn0068** [comment]
接下来回到刚刚的开发者平台，找到 OAuth2 选项卡，选择 URL Generator，这里我直接给机器人管理员的权限，选择如下所示：

此处需要有Redirect URL ，哪里弄错了？

**Comment by deanxv** [comment]
> 接下来回到刚刚的开发者平台，找到 OAuth2 选项卡，选择 URL Generator，这里我直接给机器人管理员的权限，选择如下所示：
> 
> 此处需要有Redirect URL ，哪里弄错了？

你点的应该是 General，非URL Generator，URL Generator下是不需要Redirect URL 的

**Comment by cn0068** [comment]
重置回默认的权限后，加上了。

**Comment by deanxv** [comment]
> 重置回默认的权限后，加上了。

一般情况下选中这几个就可以

<img width="962" alt="img4" src="https://github.com/deanxv/coze-discord-proxy/assets/57529708/06e6a8d3-47c9-4b2b-ac30-bb63309f7c83">

**Comment by cn0068** [comment]
请问在哪设置前端？docker安装时设置了。如何调用
PROXY_SECRET:123456 [可选]请求头校验的值（前后端统一）,配置此参数后，每次发起请求时请求头加上proxy-secret 参数，即header中添加 proxy-secret：123456
http://192.168.10.100:7077/
{"message":"无权进行此操作，未提供正确的 proxy-secret","success":false}

**Comment by deanxv** [comment]
> 请问在哪设置前端？docker安装时设置了。如何调用 PROXY_SECRET:123456 [可选]请求头校验的值（前后端统一）,配置此参数后，每次发起请求时请求头加上proxy-secret 参数，即header中添加 proxy-secret：123456 [http://192.168.10.100:7077](http://192.168.10.100:7077/) {"message":"无权进行此操作，未提供正确的 proxy-secret","success":false}

参考下：
<img width="1000" alt="img4" src="https://github.com/deanxv/coze-discord-proxy/assets/57529708/180b098e-a02a-4ca5-acad-26d32824fd6e">

**Comment by cn0068** [comment]
![屏幕截图 2024-01-27 181652](https://github.com/deanxv/coze-discord-proxy/assets/62278175/573964d6-53d5-4300-b3a8-c335cfeffced)
是这样的提示

**Comment by deanxv** [comment]
> ![屏幕截图 2024-01-27 181652](https://private-user-images.githubusercontent.com/62278175/300171524-573964d6-53d5-4300-b3a8-c335cfeffced.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNTEwMjUsIm5iZiI6MTcwNjM1MDcyNSwicGF0aCI6Ii82MjI3ODE3NS8zMDAxNzE1MjQtNTczOTY0ZDYtNTNkNS00MzAwLWIzYTgtYzMzNWNmZWZmY2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDEwMTg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNjIwNWQ0MzM2YTIzMzJmZWE4Nzk1MjU0NGIzZjg4MmU0ZmRmN2VkNGZiZDY0MjcxNzgyYTVjODI4NzVjMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q_Qf0EPaUMn69IokkqOm333-ZEsSRYbRFsqvKPJbvWo) 是这样的提示

可以看下docker启动命令和请求头及请求体吗

**Comment by cn0068** [comment]
dsm安装;
docker run --name code-discord-proxy -d --restart always \
-p 7077:7077 \
-e BOT_TOKEN="MTE5OTk2xxxxxxxxxxxxxxrwUrUWNbG63w" \
-e GUILD_ID="119xxxxxxxx796" \
-e COZE_BOT_ID="119xxxxxxxx7" \
-e PROXY_SECRET="123456" \
deanxv/code-discord-proxy
log:
![Uploading 屏幕截图 2024-01-27 182413.png…]()

**Comment by deanxv** [comment]
> dsm安装;
> 
> docker run --name code-discord-proxy -d --restart always \
> 
> -p 7077:7077 \
> 
> -e BOT_TOKEN="MTE5OTk2xxxxxxxxxxxxxxrwUrUWNbG63w" \
> 
> -e GUILD_ID="119xxxxxxxx796" \
> 
> -e COZE_BOT_ID="119xxxxxxxx7" \
> 
> -e PROXY_SECRET="123456" \
> 
> deanxv/code-discord-proxy
> 
> log:
> 
> ![屏幕截图 2024-01-27 182413](https://github.com/deanxv/coze-discord-proxy/assets/62278175/ba0eec86-2151-4124-a8b2-5ee9afeec3f6)
> 
> 
> 
> 
> 
> 

图片上传失败了 上传后多等一会 
如果你有tg的话可以在最新的readme里找到tg群 私聊我我帮你看下

**Comment by cn0068** [comment]
已加tg群

**Comment by MasterKeee** [comment]
我也遇到了这个问题
