### ISSUE TITLE
第二天无法正常使用

### ISSUE THREAD

**Issue by Passerby1011** [deanxv/coze-discord-proxy#31]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
部署完可以正常使用，第二天使用回报错，查看日志说他找不到频道和机器人
重启docker容器恢复正常

**复现步骤**

**预期结果**

**相关截图**
![20240204_121714_937_copy](https://github.com/deanxv/coze-discord-proxy/assets/63802758/07c2863c-b226-41e5-934b-0bc34cbaedee)

**Comment by deanxv** [comment]
是有这个bug，昨天下午的版本中已修复🥲，TG群中已通知。
