### ISSUE TITLE
使用v1/chat/completion接口，不能正常停止

### ISSUE THREAD

**Issue by wuweinero** [deanxv/coze-discord-proxy#33]
我在postman中测试的：
1. 当stream为true时，不会收到[DONE]这条消息，Discord中coze机器人发送完消息后，postman的请求就会阻塞停在那，一直不会停止；
2. 当stream为false时，Discord中coze机器人发送完消息后，postman也一直处于请求状态，不会终止。

**Comment by deanxv** [comment]
查看coze设置Auto Sug，改为默认。
![IMG_8318](https://github.com/deanxv/coze-discord-proxy/assets/57529708/5117bcbb-536b-47ac-b121-4491e4532355)

**Comment by wuweinero** [comment]
确实是这个问题，非常感谢！
