### ISSUE TITLE
问题咨询 环境变量BOT_TOKEN是？

### ISSUE THREAD

**Issue by think007** [deanxv/coze-discord-proxy#34]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
 环境变量BOT_TOKEN是 https://discord.com 的发送消息的Authorization 请求头吗还是
![image](https://github.com/deanxv/coze-discord-proxy/assets/45476940/4cf53e75-033a-4a84-8812-836bc5a49e3a)
https://discord.com/developers 里面Bot的token，两个都试了，运行ip+端口提示404，运行日志看了显示：环境变量 COZE_BOT_ID 不可为当前服务 BOT_TOKEN 关联的 BOT_ID。请问是改哪里配置呢
**应用场景**

**Comment by deanxv** [comment]
首先此项目并没有前端页面，只是个api服务，页面只有接口文档。

详细教程在TG群中，TG群在项目文档中。
