### ISSUE TITLE
第二天运行还是出错

### ISSUE THREAD

**Issue by spencergong** [deanxv/coze-discord-proxy#35]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
{'error': {'message': '配置异常', 'type': 'invalid_request_error', 'param': '', 'code': 'discord_request_err'}}
**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
可以看下是什么时候的镜像吗？

**Comment by spencergong** [comment]
有人说该Bug之后，您说修改之后，我下载的

**Comment by deanxv** [comment]
请拉取最新版本试下 刚更新了大版本支持对话隔离

**Comment by spencergong** [comment]
刚刚测试一下，还是出现配置错误，停止重启后又正常。

**Comment by deanxv** [comment]
可以发下截图看下镜像时间吗？

**Comment by deanxv** [comment]
执行 docker images

**Comment by spencergong** [comment]
![003](https://github.com/deanxv/coze-discord-proxy/assets/10891602/9d7602d0-01b7-4a36-929d-900987c26d4d)
我可能只是删除了container，而不是image,我再试试，到时候再告知

**Comment by spencergong** [comment]
删除Images后，重新安装了2次，二次都居然不能运行，出现配置错误。
![004](https://github.com/deanxv/coze-discord-proxy/assets/10891602/4d8012c0-759d-4892-ae1c-11f0834f7b0f)
![005](https://github.com/deanxv/coze-discord-proxy/assets/10891602/fe870c15-bcb7-4169-b990-a5d8fbb45afd)

**Comment by deanxv** [comment]
> 删除Images后，重新安装了2次，二次都居然不能运行，出现配置错误。
> 
> ![004](https://github.com/deanxv/coze-discord-proxy/assets/10891602/4d8012c0-759d-4892-ae1c-11f0834f7b0f)
> 
> ![005](https://github.com/deanxv/coze-discord-proxy/assets/10891602/fe870c15-bcb7-4169-b990-a5d8fbb45afd)
> 
> 
> 
> 

这明显不是配置错误。重新设置机器人权限拉入服务器。![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/24281e61-a850-4082-a51f-71e28ca8e24f)

**Comment by spencergong** [comment]
感谢！按照您的bot设置，可以正常运行了。所谓隔离，就是不在discord中显示我自己客户端发送和得到的信息，是吗？在discord上有声音提醒，但没有痕迹。如果我不需要隔离，可以吗？可以有个选择吗？

**Comment by deanxv** [comment]
CHANNEL_AUTO_DEL_TIME:60 [可选]频道自动删除时间(秒) 此参数为每次对话完成后自动删除频道的时间(默认为5s),为0时则不删除,推荐不设置


每次对话都会新建一个频道，服务器中最多500个频道，如果这个参数为0，则不会删除，就要承担服务器被频道撑满的风险，自己手动删除

**Comment by spencergong** [comment]
现在是每次对话新建一个新的频道，然后删除，如果这个参数为0，则会有很多频道，导致大于500。能否选择就生成固定的频道，这样为0的化，管理者在使用知识管理系统的场景时需要保留对话历史，也与coze的原有意愿不冲突，大家可以和谐相处。

**Comment by deanxv** [comment]
实际上这个项目目前的设计仅仅是为了对齐openai的接口，而openai的官方接口也并没有保留对话的功能。

我建议是从调用时就保存对话记录，相当于NextChat实现的方案一样，所有记录保存在浏览器的cookie中，自己随时导出存档。

也并不是不能实现将对话指定在一个频道，可能后面会实现，但要考虑的地方有很多，比如如何做到会话隔离，代码中如何兼容，有些时候就是因为各种需求都兼容了之后代码臃肿了起来导致后期不得不重构。
