### ISSUE TITLE
v1/chat/completion 自动化对话隔离策略建议

### ISSUE THREAD

**Issue by wuweinero** [deanxv/coze-discord-proxy#36]
不知道下面的策略是否可行：
1.创建频道
2.把所有messages打包作为一条消息
3.向discord发送消息并获取回复
4.删除频道
如果这样可行的话，v1/chat/completion可能更接近对齐一些

**Comment by deanxv** [comment]
之前有考虑过，一直在纠结，一个是因为discord单条消息最大仅支持2000字符，另一个是怕对话记录发给coze bot他不能正确的理解语义。

不过我可以尝试下。

**Comment by deanxv** [comment]
最新镜像已实现，请拉取镜像帮忙测试下，没问题的话今晚发正式版本。

**Comment by wuweinero** [comment]
不好意思，刚刚看到。我已经测试了，现在确实已经实现了这个逻辑（好像发送messages时，直接使用json序列化发送的），并且GPT4确实能够正确理解语义，并且在答案中不会加上类似"role":"assistant"之类的内容，而是直接返回content的内容，相当不错。不过我没测试更多轮次的对话中，会不会导致答案中重复前面的message格式。
我有个更进一步的提议，或许可以进一步提升答案的鲁棒性。即把prompt重新拼接成类似下面的结构：

user: 你好
assistant: 你好，有什么可以帮助你的？
user: 可以讲一个笑话嘛？
assistant:

这样在答案中，它可能更倾向于续写，而基本可以避免重复前面json序列化的模式，尽管现在直接序列化也没出现问题，但是不知道对话轮次以及内容变长之后，会不会由于强化了json格式的语义，导致结果也以json格式返回。
您可以考虑一下😊

**Comment by wuweinero** [comment]
role的角色为system的话，可以在前面加上
system: 这是系统的指令
user: 你好
....

可能GPT4太智能了，能自动克服这个问题。我之前测试比较弱的7B-13B的LLM，经常会出现续写模仿格式的问题。

**Comment by wuweinero** [comment]
或者您可以先试一下改成我前面提到的这种格式，GPT4是不是依然能够正常工作，可以先在Coze中测试一下。我这边测试下来，即使加上system也没有问题。并且使用这个格式，它或许可以进一步胜任代码补全的工作，而不仅仅是对话。

**Comment by deanxv** [comment]
现在的json格式是不支持代码补全吗？

**Comment by deanxv** [comment]
你可以搭建服务尝试一下
![补全](https://github.com/deanxv/coze-discord-proxy/assets/57529708/ee2ed908-9453-42b7-a80e-16899cc138e3)

**Comment by wuweinero** [comment]
是的，这样代码补全之前，它可能会先聊天。如果用作代码补全插件，可能没法直接用它实现auto completion（类似Github copilot那样，直接在代码内续写代码，没有前置对话内容）

**Comment by wuweinero** [comment]
不过这个auto completion的需求可能小众，现在的对话功能已经满足绝大部分场景了。
我之前测试过使用我前面说的那种格式替代json序列化的格式，在小模型上效果是更好的，我写过简单的代码插件，做过一些简单的测试。
您后面如果有空的话，可以考虑一下😊

**Comment by deanxv** [comment]
无论哪种方案都是依赖了GPT4的语义理解。

我采用json第一点原因是这是openai原生的json格式，可能会强化GPT的理解。

第二点是对于discord-proxy来讲，能少处理一步就是省下了一部分时间，更何况处理过程可能还有各种特殊情况(比如我们无法通过api传输\n换行标识)。

第三点是discord-bot的回答也仅仅只有2000字符，这也是coze对discord的隐藏prompt之一，导致了无法像官方那样用起来那么灵活。

至于你所说的像copilot一样没有前置对话内容 ，其实完全可以靠初始prompt来实现，因为在项目交流群中已经很多群友在搞了。

**Comment by wuweinero** [comment]
好的，非常感谢您的耐心解答😊

**Comment by itq5** [comment]
在使用GPT3.5时，似乎没法很好的区分上下文信息，3.5回答时会把发送给他的所有历史消息进行逐一重新答复。期待修复
