### ISSUE TITLE
处理长请求

### ISSUE THREAD

**Issue by tkizm1** [deanxv/coze-discord-proxy#38]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**

有时回复时间过长，会导致vercel无法处理
```
Your function was stopped as it did not return an initial response within 25s
```

**应用场景**
兼容vercel应用

**Comment by deanxv** [comment]
如果部署时环境变量里的各类超时参数没有定义的话，默认超时时间为5分钟，基本足够返回的了。

你可以尝试使用postman等接口调试工具验证一下。

或者使用这个也同样是vercel部署的[NextChat](https://ci.goeast.io/)

如果可以的话代表可能是你的vercel或者NextChat端配置了某些参数影响到了超时时间。

**Comment by Baozhi888** [comment]
你应该也套了CF吧，关掉域名代理试试看，我的关掉后一切正常，回头再找下CF配置的问题

**Comment by tkizm1** [comment]
没有套cf，直接连的vercel域名
用的lobechat，nextchat确实没出现这个问题

**Comment by tkizm1** [comment]
我的请求内容是
画一只小猫
目前只有画图特别慢

**Comment by deanxv** [comment]
> 我的请求内容是
> 
> 画一只小猫
> 
> 目前只有画图特别慢

画图是比较慢的，如果仅仅只有lobeChat出现问题的话，可以排查下是不是lobeChat中有哪些地方设置了超时时间什么的，翻阅一下文档

**Comment by tkizm1** [comment]
不只是lobe，NextChat 也返回504

**Comment by deanxv** [comment]
> 如果部署时环境变量里的各类超时参数没有定义的话，默认超时时间为5分钟，基本足够返回的了。
> 
> 你可以尝试使用postman等接口调试工具验证一下。
> 
> 或者使用这个也同样是vercel部署的[NextChat](https://ci.goeast.io/)
> 
> 如果可以的话代表可能是你的vercel或者NextChat端配置了某些参数影响到了超时时间。


首先，你可以采用postman请求试下，如果可以请求通那就代表不是服务的问题，那你就可以使用我上面提供的NextChat地址，如果也可以，那就可以排除既不是服务的问题也不是NextChat的问题。

**Comment by deanxv** [comment]
如果不是该服务的问题，请提issue至对话面板的github项目中。

**Comment by tkizm1** [comment]
看起来上游也没有解决方案
https://github.com/lobehub/lobe-chat/issues/1079
留给后人做个线索

**Comment by CellLz** [comment]
> 你应该也套了CF吧，关掉域名代理试试看，我的关掉后一切正常，回头再找下CF配置的问题

我想请教一下如何关掉cf，就是docker中部署了本项目之后，如果不套cf-tunnel的话怎么把api接口从http转成https？如果不转https的话好像在chat-next-web中不能使用（我的vps上暂时不考虑安装nginx等反代工具了）在chat-next-web上还是需要套一下cdn的，否则没有加密不安全。（我的情况是把chat-next-web和coze-discord-proxy都部署在同一台vps上）
