### ISSUE TITLE
Status Code 401, {"error":{"message":"authorization(proxy-secret)校验失败"

### ISSUE THREAD

**Issue by shentong0722** [deanxv/coze-discord-proxy#39]
API Error: Status Code 401, {"error":{"message":"authorization(proxy-secret)校验失败","type":"invalid_request_error","param":"","code":"invalid_authorization"}}

我没有配置PROXY_SECRET值，在NextChat中直接可用，但是在ChatBox出现了这个报错

**Comment by deanxv** [comment]
目前如果你没有填写该变量，是不会校验的(我记得是的)。
你可以尝试使postman测试下。
