### ISSUE TITLE
"message": "discord发送消息异常", "success": true

### ISSUE THREAD

**Issue by steady298** [deanxv/coze-discord-proxy#4]
<img width="526" alt="{C7CC319C-3B87-4034-87C5-0BCC10D20B90}" src="https://github.com/deanxv/coze-discord-proxy/assets/115759238/3041ccdd-0dfd-4b6d-a640-b70ff36f73dc">

如图，没有设置proxy密码，

**Comment by deanxv** [comment]
先确认机器人是否有发送消息的权限，如果有的话检查下channelId是不是写错了，非guildId。

比如 https://discord.com/channels/1199xxxxxxx53796/119xxxxxx963975

后面的 119xxxxxx963975 才是channelId

**Comment by steady298** [comment]
> 先确认机器人是否有发送消息的权限，如果有的话检查下channelId是不是写错了，非guildId。
> 
> 比如 https://discord.com/channels/1199xxxxxxx53796/119xxxxxx963975
> 
> 后面的 119xxxxxx963975 才是channelId

感谢，已经解决！
