### ISSUE TITLE
部署时出错

### ISSUE THREAD

**Issue by linzjian666** [deanxv/coze-discord-proxy#42]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**

在Render上进行部署时出错

**复现步骤**

**预期结果**

**相关截图**

![image](https://github.com/deanxv/coze-discord-proxy/assets/63142068/317479e8-45e5-4ccd-98e3-a05ab225c254)

**Comment by deanxv** [comment]
可能是render免费额度到期了，或者换个地区再试试，或者尝试在zeabur或者其他vps上部署，如果成功了代表是render的原因。
