### ISSUE TITLE
多机器人部署会出现 authorization(proxy-secret)校验失败

### ISSUE THREAD

**Issue by InternetBugs** [deanxv/coze-discord-proxy#44]
**例行检查**

+ [ √] 我已确认目前没有类似 issue
+ [ √] 我已确认我已升级到最新版本
+ [ √] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ √] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
进行多机器人部署时，在环境变量中写入的机器人一切正常，但是通过data/config/bot_config.json部署的多机器人会不断提示authorization(proxy-secret)校验失败
这个问题在pull到今天的新版本后出现，昨天使用一切正常

**复现步骤**
使用bot_config.json内配置的proxy-secret通过one-api请求api

**预期结果**
正常返回

**Comment by deanxv** [comment]
环境变量中的PROXY_SECRET是否配置了所有的key

**Comment by InternetBugs** [comment]
> 环境变量中的PROXY_SECRET是否配置了所有的key
检查了一下，确实是环境变量中只配置了一个key的原因
把多机器人的key写进去后正常了
