### ISSUE TITLE
请问能否支持SillyTavern

### ISSUE THREAD

**Issue by DoshideDK** [deanxv/coze-discord-proxy#47]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
适配SillyTavern的openai反向代理，https://github.com/SillyTavern/SillyTavern
**应用场景**

**Comment by deanxv** [comment]
项目已经对齐了openai的接口，如果支持openai原生接口，那这个项目肯定也是支持的。

**Comment by DoshideDK** [comment]
> 项目已经对齐了openai的接口，如果支持openai原生接口，那这个项目肯定也是支持的。

问一个愚蠢的问题，我试过直接填NextChat能用的地址，加/v1或者v1/chat/completions等都连不上，还有别的调用方式吗

**Comment by deanxv** [comment]
> > 项目已经对齐了openai的接口，如果支持openai原生接口，那这个项目肯定也是支持的。
> 
> 
> 
> 问一个愚蠢的问题，我试过直接填NextChat能用的地址，加/v1或者v1/chat/completions等都连不上，还有别的调用方式吗

查看你的docker logs是否有报错

**Comment by DoshideDK** [comment]
> > > 项目已经对齐了openai的接口，如果支持openai原生接口，那这个项目肯定也是支持的。
> > 
> > 
> > 问一个愚蠢的问题，我试过直接填NextChat能用的地址，加/v1或者v1/chat/completions等都连不上，还有别的调用方式吗
> 
> 查看你的docker logs是否有报错

有，都报404

**Comment by deanxv** [comment]
提供截图

**Comment by DoshideDK** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/105574972/5f36ecc3-5ddf-4f7e-b21f-d5560f464184)

**Comment by DoshideDK** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/105574972/87fefa83-1723-4b27-becd-835611f1018b)

**Comment by deanxv** [comment]
以上没有一个接口请求的是对的，请重新查看github的readme文档，并打开项目接口文档查找已对齐的接口。

**Comment by DoshideDK** [comment]
> 以上没有一个接口请求的是对的，请重新查看github的readme文档，并打开项目接口文档查找已对齐的接口。

好的，我去找找
