### ISSUE TITLE
支持多用户聊天分别针对每个用户的聊天进行上下文关联的功能吗？

### ISSUE THREAD

**Issue by weikecloud** [deanxv/coze-discord-proxy#5]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**

**应用场景**

**Comment by deanxv** [comment]
Discord中每个新的频道都是新的上下文
所以只需要在每个用户新建会话时为他创建一个新的频道就可以

接口文档里也提供了新增频道和删除频道的接口。

**Comment by weikecloud** [comment]
一个服务器能创建多少个频道呢？

**Comment by deanxv** [comment]
> 一个服务器能创建多少个频道呢？

好像是五百个，频道创建满了之后在环境变量中更换服务器id就可以，可能后期会支持多服务器轮询创建。

**Comment by weikecloud** [comment]
后续计划加上哪些功能呢？有交流群吗？

**Comment by deanxv** [comment]
> 后续计划加上哪些功能呢？有交流群吗？

后期可能会看看Issues里大家会提哪些功能吧。

刚建了个TG群[https://t.me/+LGKwlC_xa-E5ZDk9](url)

**Comment by weikecloud** [comment]
搞微信群或者QQ群吗？

**Comment by weikecloud** [comment]
这个链接好像打不开

**Comment by deanxv** [comment]
> 这个链接好像打不开

TG群必须科学上网才能进入，小项目不太想搞群，等用的人多了我再搞qq或者微信群吧
