### ISSUE TITLE
bot_config.json中设置了3个接入coze的机器人，但是在接口调用时指定model类型，在discord看到始终是@的我docker 环境变量中的COZE_BOT_ID的机器人，似乎bot_config.json未生效。

### ISSUE THREAD

**Issue by itq5** [deanxv/coze-discord-proxy#51]
![image](https://github.com/deanxv/coze-discord-proxy/assets/42521985/ab83dd83-d6af-4e10-bc1c-5f0e7f65cc9c)

**Comment by deanxv** [comment]
提供启动服务的所有日志，调试的请求头，请求参数，返回结果用来排查问题。

**Comment by itq5** [comment]
问题已解决，是容器内文件没挂载上导致
