### ISSUE TITLE
在使用GPT3.5时，似乎没法很好的区分上下文信息，3.5回答时会把发送给他的所有历史消息进行逐一重新答复，在4.0模型中就不存在这个问题。期待修复

### ISSUE THREAD

**Issue by itq5** [deanxv/coze-discord-proxy#52]
在使用GPT3.5时，似乎没法很好的区分上下文信息，3.5回答时会把发送给他的所有历史消息进行逐一重新答复，在4.0模型中就不存在这个问题。期待修复
![image](https://github.com/deanxv/coze-discord-proxy/assets/42521985/027200b3-95c6-442b-9160-474b9b5867d9)

**Comment by deanxv** [comment]
难度很高，proxy服务仅仅只是作为代理对话给coze的机器人，又想实现对话隔离，又想对齐openai官方接口的所有功能，难上加难。

**Comment by kokosensei** [comment]
@deanxv 问一下, 这里能否在openai api标准之上额外引入conversation_id的参数, 一个conversation_id对应一个channel_id从而实现上下文管理呢?

**Comment by deanxv** [comment]
> @deanxv 问一下, 这里能否在openai api标准之上额外引入conversation_id的参数, 一个conversation_id对应一个channel_id从而实现上下文管理呢? 如果conversation_id为空则默认使用原有新建channel的逻辑.
> 
> 此灵感来源于 Claude 非官方API

那为什么不直接用channelId，channelId为空则新建channel，其实在之前的版本就是这样做的，但后来因为多机器人配置等关联较复杂，就先去掉了
