### ISSUE TITLE
[error opening connection, Get "https://discord.com/api/v9/gateway": proxyconnect tcp: dial tcp 127.0.0.1:10801: connect: connection refused]

### ISSUE THREAD

**Issue by Travis-55** [deanxv/coze-discord-proxy#53]
![image](https://github.com/deanxv/coze-discord-proxy/assets/101291505/9f8e5755-4912-4935-8954-4008cc62fb2d)

**Comment by deanxv** [comment]
部署环境变量中的PROXY_URL请使用自己的，文档中只是我的示例。

**Comment by Travis-55** [comment]
[FATAL] 2024/02/13 - 16:39:02 | [error creating proxy client, 仅支持sock和http代理！] 
[SYS] 2024/02/13 - 16:39:02 | COZE-DISCORD-PROXY v3.2.3 started 
==> Common ways to troubleshoot your deploy: https://docs.render.com/troubleshooting-deploys
[SYS] 2024/02/13 - 16:39:04 | COZE-DISCORD-PROXY v3.2.3 started 
[FATAL] 2024/02/13 - 16:39:04 | [error creating proxy client, 仅支持sock和http代理！]

**Comment by deanxv** [comment]
> [FATAL] 2024/02/13 - 16:39:02 | [error creating proxy client, 仅支持sock和http代理！] 
> 
> [SYS] 2024/02/13 - 16:39:02 | COZE-DISCORD-PROXY v3.2.3 started 
> 
> ==> Common ways to troubleshoot your deploy: https://docs.render.com/troubleshooting-deploys
> 
> [SYS] 2024/02/13 - 16:39:04 | COZE-DISCORD-PROXY v3.2.3 started 
> 
> [FATAL] 2024/02/13 - 16:39:04 | [error creating proxy client, 仅支持sock和http代理！] 

自己看报错信息内容，PROXY_URL不要瞎写，这个也不是必填项，自己的使用场景下不需要可以不用写。

**Comment by Travis-55** [comment]
I did set the proxy url

**Comment by Travis-55** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/101291505/da0cec95-8ab3-4166-b33e-213b4fd4d108)

**Comment by deanxv** [comment]
> ![image](https://github.com/deanxv/coze-discord-proxy/assets/101291505/da0cec95-8ab3-4166-b33e-213b4fd4d108)
> 
> 

![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/5e777835-d779-492b-a520-c1f6c71423d9)

请拿出笔和纸，把PROXY_URL抄写一百遍。

**Comment by Travis-55** [comment]
I entered the proxy url already but its still giving the error

**Comment by deanxv** [comment]
> I entered the proxy url already but its still giving the error

你填写的PROXY_URL的值是什么？

**Comment by Travis-55** [comment]
htttps://myappname.onrender.com

**Comment by deanxv** [comment]
> htttps://myappname.onrender.com

为什么要写这个？这个环境变量的意义是在启动discord客户端时使用你的代理ip端口，不会使用的话，请删除此环境变量。

**Comment by Travis-55** [comment]
yes i want to use the api for another app

**Comment by deanxv** [comment]
> yes i want to use the api for another app

删除此环境变量后服务如果启动成功，用你部署服务器的ip及环境变量中的port调试即可
