### ISSUE TITLE
error sending message

### ISSUE THREAD

**Issue by diminghui** [deanxv/coze-discord-proxy#56]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
你好，我在成功部署render后，在nextchat客户端填了API和接口地址，但提问时会出现以下报错。对应的render上也会产生报错，能帮忙看下是为什么吗？非常感激你的贡献！

**相关截图**
{
  "error": {
    "message": "error sending message",
    "type": "invalid_request_error",
    "param": "",
    "code": "discord_request_err"
  }
}
![image](https://github.com/deanxv/coze-discord-proxy/assets/61655797/ea6742ce-6188-4966-9e21-18ac02aa5d83)

**Comment by deanxv** [comment]
Bot权限不足导致无法创建频道![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/3d16d0d2-ed3a-4ce2-80ce-c9c1ff68e961)

**Comment by diminghui** [comment]
是在之前6个权限的基础上添加Administrator的权限吗？
![image](https://github.com/deanxv/coze-discord-proxy/assets/61655797/317f6e16-8cb2-42b6-89d0-7ba1974370db)

**Comment by deanxv** [comment]
> 是在之前6个权限的基础上添加Administrator的权限吗？
> 
> ![image](https://github.com/deanxv/coze-discord-proxy/assets/61655797/317f6e16-8cb2-42b6-89d0-7ba1974370db)
> 
> 

添加了这个就不需要添加其他权限了

**Comment by diminghui** [comment]
可以了！！非常感谢您！
