### ISSUE TITLE
zeabur一键部署失败以及能否直接使用Go部署的疑问和尝试

### ISSUE THREAD

**Issue by qqwildfox** [deanxv/coze-discord-proxy#58]
大佬辛苦~
**问题背景：**
      尝试使用一键部署到zeabur时候失败，之前是右下角提示失败（现在操作是直接回到zeabur首页），遂使用手动部署成功，但由于是docker，zeabur的容器化服务被自动清除，最后尝试使用Go直接部署到zeabur改成了serverless服务，(已经配置好机器人)
**问题描述：**
      nextchat失败，安卓端如问天有几率成功不稳定
**日志附件：**
      以下是日志和nextchat的截图
![image](https://github.com/deanxv/coze-discord-proxy/assets/108218801/f096972e-c04e-4be5-a16d-7df0722f111f)
![image](https://github.com/deanxv/coze-discord-proxy/assets/108218801/5989a024-ee54-470b-a4b6-61c64758c93a)

**Comment by deanxv** [comment]
请使用postman调试接口，调试通过后再集成第三方对话面板，这样有助于排查是否为对话面板或服务本身的问题。

另外，NextChat这个报错大概率是面板内的baseUrl你设置的是http://ip:port的格式，请将该网页设置中的不安全内容改为允许，或者采用反代为https。

**Comment by qqwildfox** [comment]
感谢回复，问题解决途径如下
**排查过程**
        使用postman发送，似乎成功却未返回内容，但discord中出现了无法被自动删除的临时会话频道和正确的返回内容，接口无误，遂尝试在zeabur中添加环境变量FORCE_CONTAINERIZED=1强行变为容器化服务
**问题结果**
        nextchat正常返回，所有功能正常，因此原因在于使用zeabur的serverless服务，目前我个人的解决方法为：
1.使用容器化服务等被自动清除后重新部署，
2.付费订阅开发者方案，
3.更换新的平台（我使用Google账户登录render仍提示需要绑卡具体原因不明）
**最后**再次感谢开发者！
