### ISSUE TITLE
如何设置代理进行访问

### ISSUE THREAD

**Issue by wanghai-king** [deanxv/coze-discord-proxy#59]
[SYS] 2024/02/17 - 16:44:13 | COZE-DISCORD-PROXY v3.2.3 started 
[GIN] 2024/02/17 - 16:44:23 | 20240217164423246472247BJ3KhEsB | 204 |      46.443µs |    10.94.18.150 | OPTIONS /v1/chat/completions
[FATAL] 2024/02/17 - 16:44:33 | [error opening connection, Get "https://discord.com/api/v9/gateway": context deadline exceeded (Client.Timeout exceeded while awaiting headers)]

不使用代理无法访问https://discord.com/api/v9/gateway

**Comment by deanxv** [comment]
环境变量第11条，仅支持http

![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/b7a3cf8c-2c36-459c-b4cf-2271d46e8aaa)

**Comment by wanghai-king** [comment]
配置了，也不行，有时候会提示[FATAL] 2024/02/17 - 16:41:42 | [error opening connection, Get "https://discord.com/api/v9/gateway": dial tcp 67.230.169.182:443: connect: connection refused]

**Comment by deanxv** [comment]
> 配置了，也不行，有时候会提示[FATAL] 2024/02/17 - 16:41:42 | [error opening connection, Get "https://discord.com/api/v9/gateway": dial tcp 67.230.169.182:443: connect: connection refused]

说明你配置的不对

**Comment by Akimio521** [comment]
请问可以设置socks5和socks5h代理吗
