### ISSUE TITLE
[功能增强] 强化频道新增/讨论串可行性

### ISSUE THREAD

**Issue by bee10301** [deanxv/coze-discord-proxy#6]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
- API中增加更详细的参数，可以让新增的频道在指定id的分类中
- 考虑使用讨论串方案的可行性

**应用场景**
目前测试发现，在频道里使用讨论串功能，也是会话隔离的。
那么是否可以使用讨论串的方式来更好管理呢？

如果使用原有频道的方式，是否能指定分类id来创建呢，子频道继承分类的权限，避免直接暴露于大厅。

感谢！

**Comment by deanxv** [comment]
子频道确实是个好建议！我研究下！

**Comment by deanxv** [comment]
docker镜像已更新

1. 新建频道可指定父频道Id即可创建子频道
2. 新建线程(子区/串)
3. chat接口的ChannelId传线程Id即在指定的线程中对话

**Comment by bee10301** [comment]
感受到你的热血了！
给翻到这篇的小夥伴说一下，线程有一个不活跃自动隐藏的设定，根据[官方文档](https://discord.com/developers/docs/resources/channel#thread-metadata-object-thread-metadata-structure)，`archiveDuration`必须为 `60, 1440, 4320, 10080` 之一喔！

**Comment by deanxv** [comment]
> 感受到你的热血了！
> 
> 给翻到这篇的小夥伴说一下，线程有一个不活跃自动隐藏的设定，根据[官方文档](https://discord.com/developers/docs/resources/channel#thread-metadata-object-thread-metadata-structure)，`archiveDuration`必须为 `60, 1440, 4320, 10080` 之一喔！

谢谢你！有空我写个枚举限制一下！

**Comment by bee10301** [comment]
> 谢谢你！有空我写个枚举限制一下！

我觉得也可以考虑自动取最近的数值（ex. 使用者输入1000 则取1440）

**Comment by deanxv** [comment]
> > 谢谢你！有空我写个枚举限制一下！
> 
> 
> 
> 我觉得也可以考虑自动取最近的数值（ex. 使用者输入1000 则取1440）

也可以的！
