### ISSUE TITLE
7077 端口 404 page not found

### ISSUE THREAD

**Issue by LeoYOHU** [deanxv/coze-discord-proxy#60]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by LeoYOHU** [comment]
RT

**Comment by deanxv** [comment]
api项目，没有页面。
