### ISSUE TITLE
提交到discord的数据被转义了

### ISSUE THREAD

**Issue by CoolGaijin** [deanxv/coze-discord-proxy#61]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
1. 输入的内容是：Windows 10 has a tool called <b>Deployment Image Servicing and Management (DISM)</b> 
2. 提交之后，到discord看到的数据如下图
3. 被转换了。

**相关截图**
被转换了
![1](https://github.com/deanxv/coze-discord-proxy/assets/157477395/0754e995-53d0-408a-951f-70fb72f9188b)

如果没有的话,请删除此节。

**Comment by deanxv** [comment]
就是这样的

**Comment by zyd16888** [comment]
这是正常的，关键字 urlencode 搜一下就知道为啥了

**Comment by CoolGaijin** [comment]
> 就是这样的，感觉这样应该也不影响对话吧？

还是有影响的，gpt那边的结果有时候也是转义了（不是每个都这样），我最终拿到的结果也是转义了的，不知道怎么转回来...... 
但我没有办法复现了，刚才测试了几个文本又正常了。。。。

**Comment by deanxv** [comment]
> > 就是这样的，感觉这样应该也不影响对话吧？
> 
> 
> 
> 还是有影响的，gpt那边的结果有时候也是转义了（不是每个都这样），我最终拿到的结果也是转义了的，不知道怎么转回来...... 
> 
> 但我没有办法复现了，刚才测试了几个文本又正常了。。。。

因为你issue中的文本内容中有html的<b>加粗标签，正常请求中其实是不会有这种的，大概率是你不知道在哪粘贴过来的。

**Comment by CoolGaijin** [comment]
嗯，谢谢，明白了
