### ISSUE TITLE
报错提示 [环境变量 COZE_BOT_ID 不可为当前服务 BOT_TOKEN 关联的 BOT_ID] 

### ISSUE THREAD

**Issue by think007** [deanxv/coze-discord-proxy#62]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
报错提示 [环境变量 COZE_BOT_ID 不可为当前服务 BOT_TOKEN 关联的 BOT_ID] 
docker run --name coze-discord-proxy -d --restart always \
-p 7077:7077 \
-v $(pwd)/data:/app/coze-discord-proxy/data \
-e BOT_TOKEN="您的BOT_TOKEN" \
-e GUILD_ID="您的GUILD_ID" \
-e COZE_BOT_ID="您的COZE_BOT_ID" \
-e CHANNEL_ID="您的CHANNEL_ID" \
-e PROXY_SECRET="您的PROXY_SECRET" \
-e TZ=Asia/Shanghai \
deanxv/coze-discord-proxy
按理应该没错老是提示这个
**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
我不知道你这个环境变量的注释是在哪里看的，你可能并没有按照readme中的步骤来，也没有看TG群中的文字教程。

**Comment by deanxv** [comment]
readme已经写的很明白，token和id分别是两个bot的。请按照教程重新配置。
![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/51d7cd47-d335-45ec-b862-b524d1cd3ab7)
