### ISSUE TITLE
bot 每天创建几百个channel 后，bot 就失效了。表现的状况是，gin http api 可以接收请求，但不给响应了，一直 hold 着。

### ISSUE THREAD

**Issue by Yi-Lyu** [deanxv/coze-discord-proxy#64]
请问为什么不能在一个 channel 内一直让 bot 和 cozebot 对话下去？ 而要每次对话创建一个 channel、单词对话完毕再删除 channel 呢。

我看到 dircord 限制每个 bot 单日创建 channel 数量在 500 个。那 api 能单日响应的请求数只有 500 个。

这个问题有什么办法可以解决嘛？

**Comment by deanxv** [comment]
1. 因为bot的上下文是读取当前频道内的所有内容，所以才每一次对话时创建了新的频道用来做对话隔离。

2. 默认情况下在每一次对话结束后5s频道会自动删除，除非你自定义了环境变量AUTO_DEL_TIME，如果你5s内的并发达到了500，那我推荐启动多个服务关联多个服务器做轮询。

**Comment by Yi-Lyu** [comment]
> 1. 因为bot的上下文是读取当前频道内的所有内容，所以才每一次对话时创建了新的频道用来做对话隔离。
> 2. 默认情况下在每一次对话结束后5s频道会自动删除，除非你自定义了环境变量AUTO_DEL_TIME，如果你5s内的并发达到了500，那我推荐启动多个服务关联多个服务器做轮询。

关于 1，是担心 bot 取内容取错位嘛？ 
我做了点微调，看起来好像也还好，多轮会话都在一个 channel 里，并且还取消息取的正常。
![O97vvoQfEy](https://github.com/deanxv/coze-discord-proxy/assets/1308846/eed652c2-7d55-43c5-a901-70876ccf7c85)

**Comment by deanxv** [comment]
> > 1. 因为bot的上下文是读取当前频道内的所有内容，所以才每一次对话时创建了新的频道用来做对话隔离。
> 
> > 2. 默认情况下在每一次对话结束后5s频道会自动删除，除非你自定义了环境变量AUTO_DEL_TIME，如果你5s内的并发达到了500，那我推荐启动多个服务关联多个服务器做轮询。
> 
> 
> 
> 关于 1，是担心 bot 取内容取错位嘛？ 
> 
> 我做了点微调，看起来好像也还好，多轮会话都在一个 channel 里，并且还取消息取的正常。
> 
> ![O97vvoQfEy](https://github.com/deanxv/coze-discord-proxy/assets/1308846/eed652c2-7d55-43c5-a901-70876ccf7c85)
> 
> 

不是错位，在同一频道下当然可以正常对话，在这个项目2.0版本下就是这样实现的。

为什么3.0改成了创建频道，是因为coze-bot会将当前频道下的内容当做上下文，比如A在这个频道下问了a问题，B又在这个频道下问了b问题，但是对于coze-bot来讲，它的上下文既有了a又有了b，那么B再问问题的时候是不是就有可能会带出A曾经问过的a问题的内容？
