### ISSUE TITLE
API调用错误

### ISSUE THREAD

**Issue by Akimio521** [deanxv/coze-discord-proxy#66]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
在/swagger/index.html下调用API成功，使用[ChatGPT-Next-Web](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web)调用失败，提示`404 page not found`
**复现步骤**

**预期结果**

**相关截图**
![调用API成功](https://github.com/deanxv/coze-discord-proxy/assets/77880495/d349f925-21b8-4178-93a0-7701b46a5bd0)
![ChatGPT-Next-Web调用失败](https://github.com/deanxv/coze-discord-proxy/assets/77880495/abc6d036-03ee-4aa6-8380-4952f7dcbff5)
![自定义接口设置](https://github.com/deanxv/coze-discord-proxy/assets/77880495/a4e589f3-d33d-478c-88b8-e272ed34c707)

**Comment by deanxv** [comment]
接口地址填的什么

**Comment by Akimio521** [comment]
解决了，原来只用填host:port，不用跟后面的uri
