### ISSUE TITLE
感觉coze现在不会回应机器人的回答了

### ISSUE THREAD

**Issue by eightHundreds** [deanxv/coze-discord-proxy#67]

**Comment by eightHundreds** [comment]
<img width="885" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/18695431/f870f696-0bca-4ebe-a560-da4b18175b8f">

**Comment by viqbgrg** [comment]
我的也没有回复了

**Comment by New2en** [comment]
+1 , 来看看有没有解决方案

**Comment by yifangyujason** [comment]
我的也是，刚刚发现的

**Comment by Hwenyi** [comment]
确实，刚刚发现了，我的也没有

**Comment by hypzy123** [comment]
我也是，今天下午3点多的时候开始没回复的

**Comment by fewk** [comment]
也发现了，coze bot直接忽略了机器人@它了

**Comment by noahlias** [comment]
官方下手了哈哈

**Comment by deanxv** [comment]
v4.0.0已推送，多了两个环境变量。

**Comment by Akimio521** [comment]
> v4.0.0已推送，多了两个环境变量。

请问授权密钥要怎么获取

**Comment by deanxv** [comment]
> > v4.0.0已推送，多了两个环境变量。
> 
> 
> 
> 请问授权密钥要怎么获取

![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/5a425335-9057-4f67-8983-ee2d2a573c37)

**Comment by KasonWan** [comment]
> v4.0.0已推送，多了两个环境变量。

大佬，可以保留之前的/api/chat接口吗

**Comment by deanxv** [comment]
> > v4.0.0已推送，多了两个环境变量。
> 
> 
> 
> 大佬，可以保留之前的/api/chat接口吗，想在指定频道发送对话

是有想要指定某几个频道发送吗？还是说不想每次都新创建对话，想要保留住对话？因为后面会加上一个环境变量用来决定是否将对话发送至默认频道中

**Comment by KasonWan** [comment]
> > > v4.0.0已推送，多了两个环境变量。
> > 
> > 
> > 大佬，可以保留之前的/api/chat接口吗，想在指定频道发送对话
> 
> 是有想要指定某几个频道发送吗？还是说不想每次都新创建对话，想要保留住对话？因为后面会加上一个环境变量用来决定是否将对话发送至默认频道中

我是想按照一个用户创建一个频道来进行隔离对话，不想每次发送对话就删除一次频道

**Comment by KasonWan** [comment]
> /api/chat

/api/chat

> > > > v4.0.0已推送，多了两个环境变量。
> > > 
> > > 
> > > 大佬，可以保留之前的/api/chat接口吗，想在指定频道发送对话
> > 
> > 
> > 是有想要指定某几个频道发送吗？还是说不想每次都新创建对话，想要保留住对话？因为后面会加上一个环境变量用来决定是否将对话发送至默认频道中
> 
> 我是想按照一个用户创建一个频道来进行隔离对话，不想每次发送对话就删除一次频道

2.2.0之后的版本好像就移除了/api/chat接口

**Comment by deanxv** [comment]
> > /api/chat
> 
> 
> 
> /api/chat
> 
> 
> 
> > > > > v4.0.0已推送，多了两个环境变量。
> 
> > > > 
> 
> > > > 
> 
> > > > 大佬，可以保留之前的/api/chat接口吗，想在指定频道发送对话
> 
> > > 
> 
> > > 
> 
> > > 是有想要指定某几个频道发送吗？还是说不想每次都新创建对话，想要保留住对话？因为后面会加上一个环境变量用来决定是否将对话发送至默认频道中
> 
> > 
> 
> > 我是想按照一个用户创建一个频道来进行隔离对话，不想每次发送对话就删除一次频道
> 
> 
> 
> 2.2.0之后的版本好像就移除了/api/chat接口

是的，因为在之后的版本中主要核心是对齐openai，所以就删除了自有对话接口，discord中又有频道数量上限，所以其实也不建议自己去新建频道，手动维护频道的数量很麻烦，而且目前的对话设计是将每次的所有上下文都发送到新建的频道当中，如果指定了频道，感觉可能会有问题，不过后期也会考虑在对齐openai的接口中加上channelid字段，毕竟又想对齐openai，又想兼容NextChat，又想有这种指定channelid的扩展性，难度有点高的。

**Comment by KasonWan** [comment]
> > > /api/chat
> > 
> > 
> > /api/chat
> > > > > > v4.0.0已推送，多了两个环境变量。
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > 大佬，可以保留之前的/api/chat接口吗，想在指定频道发送对话
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 是有想要指定某几个频道发送吗？还是说不想每次都新创建对话，想要保留住对话？因为后面会加上一个环境变量用来决定是否将对话发送至默认频道中
> > 
> > 
> > > 
> > 
> > 
> > > 我是想按照一个用户创建一个频道来进行隔离对话，不想每次发送对话就删除一次频道
> > 
> > 
> > 2.2.0之后的版本好像就移除了/api/chat接口
> 
> 是的，因为在之后的版本中主要核心是对齐openai，所以就删除了自有对话接口，discord中又有频道数量上限，所以其实也不建议自己去新建频道，手动维护频道的数量很麻烦，而且目前的对话设计是将每次的所有上下文都发送到新建的频道当中，如果指定了频道，感觉可能会有问题，不过后期也会考虑在对齐openai的接口中加上channelid字段，毕竟又想对齐openai，又想兼容NextChat，又想有这种指定channelid的扩展性，难度有点高的。

哈哈，我这个加了每天自动删除所有频道，倒不是很麻烦。主要还是想利用频道自身的上下文，感觉比较方便一点。

**Comment by czd99053** [comment]
设置代理更新到4.0.4 我刚才试了。可以提出问题
