### ISSUE TITLE
CozeBot Proxy目前已经失效, 建议使用User Cookie/Token

### ISSUE THREAD

**Issue by kokosensei** [deanxv/coze-discord-proxy#68]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**
Cozebot 不再回复Proxy机器人, 估计是Cozebot更改了后端逻辑, 机器人的@信息被过滤不再生效. 这边推荐尝试一下使用用户(discord小号)的Cookie来代替机器人, 抓取User Cookie/Token后 直接调用使用官方的Create_Message API 与Cozebot进行交互. 理论可行, 待验证.

https://discord.com/developers/docs/resources/channel#create-message

![image](https://github.com/deanxv/coze-discord-proxy/assets/24643433/ada4254d-1a26-4662-8b73-12751e5d3a7a)

**Comment by jiangno111** [comment]
这样用的话，会不会被discord封号

**Comment by Ychangq** [comment]
大佬~~求教程，不会弄啊！！

**Comment by deanxv** [comment]
v4.0.0已推送，多了两个环境变量。

**Comment by noahlias** [comment]
> 这样用的话，会不会被discord封号

会有被ban的 风险🤣
![image](https://github.com/deanxv/coze-discord-proxy/assets/3949397/c0187d67-0675-4e42-a55b-cd68c8c35a00)

**Comment by Ychangq** [comment]
> v4.0.0已推送，多了两个环境变量。

已重新部署，但是nextchat上无反应，查看discord确实是发了消息，但消息没有返回到nextchat~
不知道是不是只有我是这样

**Comment by Ychangq** [comment]
> > > v4.0.0已推送，多了两个环境变量。
> > 
> > 
> > 已重新部署，但是nextchat上无反应，查看discord确实是发了消息，但消息没有返回到nextchat~
> > 不知道是不是只有我是这样
> 
> 群里很多人都部署完成并可以正常使用了，你这个问题大概率是由于环境变量USER_ID设置错误导致的

不应该吧，我在discord里看到coze机器人回复消息了，但是回复的消息没有显示在nextchat上，如果ID错误的话，应该无法成功发送消息给coze机器人的吧

**Comment by deanxv** [comment]
> > > > v4.0.0已推送，多了两个环境变量。
> 
> > > 
> 
> > > 
> 
> > > 已重新部署，但是nextchat上无反应，查看discord确实是发了消息，但消息没有返回到nextchat~
> 
> > > 不知道是不是只有我是这样
> 
> > 
> 
> > 群里很多人都部署完成并可以正常使用了，你这个问题大概率是由于环境变量USER_ID设置错误导致的
> 
> 
> 
> 不应该吧，我在discord里看到coze机器人回复消息了，但是回复的消息没有显示在nextchat上，如果ID错误的话，应该无法成功发送消息给coze机器人的吧

并不是，USER_ID是用来快速筛选出监听的消息中你的用户发出消息的回复，如果配置错误，会找不到。

**Comment by hypzy123** [comment]
> > v4.0.0已推送，多了两个环境变量。
> 
> 已重新部署，但是nextchat上无反应，查看discord确实是发了消息，但消息没有返回到nextchat~ 不知道是不是只有我是这样
我也一样，兄弟你这个问题解决了吗？

**Comment by hypzy123** [comment]
> > > > > v4.0.0已推送，多了两个环境变量。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 已重新部署，但是nextchat上无反应，查看discord确实是发了消息，但消息没有返回到nextchat~
> > 
> > 
> > > > 不知道是不是只有我是这样
> > 
> > 
> > > 
> > 
> > 
> > > 群里很多人都部署完成并可以正常使用了，你这个问题大概率是由于环境变量USER_ID设置错误导致的
> > 
> > 
> > 不应该吧，我在discord里看到coze机器人回复消息了，但是回复的消息没有显示在nextchat上，如果ID错误的话，应该无法成功发送消息给coze机器人的吧
> 
> 并不是，USER_ID是用来快速筛选出监听的消息中你的用户发出消息的回复，如果配置错误，会找不到。

请问下USER_ID是聊天界面头像右键，然后复制用户ID吗？

**Comment by hypzy123** [comment]
> > > > > > > v4.0.0已推送，多了两个环境变量。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 已重新部署，但是nextchat上无反应，查看discord确实是发了消息，但消息没有返回到nextchat~
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 不知道是不是只有我是这样
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 群里很多人都部署完成并可以正常使用了，你这个问题大概率是由于环境变量USER_ID设置错误导致的
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 不应该吧，我在discord里看到coze机器人回复消息了，但是回复的消息没有显示在nextchat上，如果ID错误的话，应该无法成功发送消息给coze机器人的吧
> > 
> > 
> > > 
> > 
> > 
> > > 并不是，USER_ID是用来快速筛选出监听的消息中你的用户发出消息的回复，如果配置错误，会找不到。
> > 
> > 
> > 请问下USER_ID是聊天界面头像右键，然后复制用户ID吗？
> 
> 是的，复制你自己的id

![1](https://github.com/deanxv/coze-discord-proxy/assets/152757426/e5421970-e72a-43b2-868d-833c34d19a1e)
![2](https://github.com/deanxv/coze-discord-proxy/assets/152757426/1c8e37f4-b3b6-4005-8094-6a55f6ac2fa9)
![3](https://github.com/deanxv/coze-discord-proxy/assets/152757426/89a100f4-2d3d-4be5-b1e4-4b351d940509)
![4](https://github.com/deanxv/coze-discord-proxy/assets/152757426/f819cbce-22a0-467b-b6a8-7a7a6e628950)
麻烦看下，discord上面确认收到回复了，但是本地一直没返回消息，不知道哪里设置出问题了

**Comment by deanxv** [comment]
> > > > > > > > v4.0.0已推送，多了两个环境变量。
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > 已重新部署，但是nextchat上无反应，查看discord确实是发了消息，但消息没有返回到nextchat~
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > 不知道是不是只有我是这样
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > 群里很多人都部署完成并可以正常使用了，你这个问题大概率是由于环境变量USER_ID设置错误导致的
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 不应该吧，我在discord里看到coze机器人回复消息了，但是回复的消息没有显示在nextchat上，如果ID错误的话，应该无法成功发送消息给coze机器人的吧
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 并不是，USER_ID是用来快速筛选出监听的消息中你的用户发出消息的回复，如果配置错误，会找不到。
> 
> > > 
> 
> > > 
> 
> > > 请问下USER_ID是聊天界面头像右键，然后复制用户ID吗？
> 
> > 
> 
> > 是的，复制你自己的id
> 
> 
> 
> ![1](https://github.com/deanxv/coze-discord-proxy/assets/152757426/e5421970-e72a-43b2-868d-833c34d19a1e)
> 
> ![2](https://github.com/deanxv/coze-discord-proxy/assets/152757426/1c8e37f4-b3b6-4005-8094-6a55f6ac2fa9)
> 
> ![3](https://github.com/deanxv/coze-discord-proxy/assets/152757426/89a100f4-2d3d-4be5-b1e4-4b351d940509)
> 
> ![4](https://github.com/deanxv/coze-discord-proxy/assets/152757426/f819cbce-22a0-467b-b6a8-7a7a6e628950)
> 
> 麻烦看下，discord上面确认收到回复了，但是本地一直没返回消息，不知道哪里设置出问题了

检查bot中这里的权限，三个都打开。
![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/743f19c9-23bb-4f7c-b9ae-63740b80bd32)

**Comment by kingdocker** [comment]
重新部署了，为什么还是机器人B（discord监听消息机器人）艾特机器人A（对接coze的机器人）发送消息呢。。。？
在discord直接at机器人A提问，是能正常回答的。

1. 容器日志：
[SYS] 2024/02/21 - 18:22:24 | COZE-DISCORD-PROXY v2.1.4 started 
[SYS] 2024/02/21 - 18:22:25 | Environment variable check passed. 
[SYS] 2024/02/21 - 18:22:25 | Bot is now running. Enjoy It. 
[GIN] 2024/02/21 - 18:30:45 | 20240221182545185844398Upy5s5gd | 200 | 5m0.270956892s |    8.140.253.74 |    POST /v1/chat/completions
[GIN] 2024/02/21 - 18:32:51 | 20240221182750836182055aYdT4oa9 | 200 | 5m0.255371696s |    8.140.253.74 |    POST /v1/chat/completions

2. 环境变量配置：
BOT_TOKEN=监听消息的discord机器人B的token
CHANNEL_ID=频道id
COZE_BOT_ID=与coze交互的机器人A的id
GUILD_ID=服务器ID
PROXY_SECRET=密钥
USER_AUTHORIZATION=按F12，discord用户（非机器人）发言后截取的authentication
USER_ID=用户（非机器人）id

3. 截图：
<img width="213" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/42495581/5783c00a-b416-4915-8288-b2aea7cc1db8">

**Comment by deanxv** [comment]
> 重新部署了，为什么还是机器人B（discord监听消息机器人）艾特机器人A（对接coze的机器人）发送消息呢。。。？
> 
> 在discord直接at机器人A提问，是能正常回答的。
> 
> 
> 
> 1. 容器日志：
> 
> [SYS] 2024/02/21 - 18:22:24 | COZE-DISCORD-PROXY v2.1.4 started 
> 
> [SYS] 2024/02/21 - 18:22:25 | Environment variable check passed. 
> 
> [SYS] 2024/02/21 - 18:22:25 | Bot is now running. Enjoy It. 
> 
> [GIN] 2024/02/21 - 18:30:45 | 20240221182545185844398Upy5s5gd | 200 | 5m0.270956892s |    8.140.253.74 |    POST /v1/chat/completions
> 
> [GIN] 2024/02/21 - 18:32:51 | 20240221182750836182055aYdT4oa9 | 200 | 5m0.255371696s |    8.140.253.74 |    POST /v1/chat/completions
> 
> 
> 
> 2. 环境变量配置：
> 
> BOT_TOKEN=监听消息的discord机器人B的token
> 
> CHANNEL_ID=频道id
> 
> COZE_BOT_ID=与coze交互的机器人A的id
> 
> GUILD_ID=服务器ID
> 
> PROXY_SECRET=密钥
> 
> USER_AUTHORIZATION=按F12，discord用户（非机器人）发言后截取的authentication
> 
> USER_ID=用户（非机器人）id
> 
> 
> 
> 3. 截图：
> 
> <img width="213" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/42495581/5783c00a-b416-4915-8288-b2aea7cc1db8">
> 
> 

日志很明显，你的版本为2.1.4，你并没有删除镜像重新拉取镜像。

**Comment by kingdocker** [comment]
> > 重新部署了，为什么还是机器人B（discord监听消息机器人）艾特机器人A（对接coze的机器人）发送消息呢。。。？
> > 在discord直接at机器人A提问，是能正常回答的。
> > 
> > 1. 容器日志：
> > 
> > [SYS] 2024/02/21 - 18:22:24 | COZE-DISCORD-PROXY v2.1.4 started
> > [SYS] 2024/02/21 - 18:22:25 | Environment variable check passed.
> > [SYS] 2024/02/21 - 18:22:25 | Bot is now running. Enjoy It.
> > [GIN] 2024/02/21 - 18:30:45 | 20240221182545185844398Upy5s5gd | 200 | 5m0.270956892s |    8.140.253.74 |    POST /v1/chat/completions
> > [GIN] 2024/02/21 - 18:32:51 | 20240221182750836182055aYdT4oa9 | 200 | 5m0.255371696s |    8.140.253.74 |    POST /v1/chat/completions
> > 
> > 2. 环境变量配置：
> > 
> > BOT_TOKEN=监听消息的discord机器人B的token
> > CHANNEL_ID=频道id
> > COZE_BOT_ID=与coze交互的机器人A的id
> > GUILD_ID=服务器ID
> > PROXY_SECRET=密钥
> > USER_AUTHORIZATION=按F12，discord用户（非机器人）发言后截取的authentication
> > USER_ID=用户（非机器人）id
> > 
> > 3. 截图：
> > 
> > <img alt="image" width="213" src="https://private-user-images.githubusercontent.com/42495581/306734958-5783c00a-b416-4915-8288-b2aea7cc1db8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDA5MjgsIm5iZiI6MTcwODU0MDYyOCwicGF0aCI6Ii80MjQ5NTU4MS8zMDY3MzQ5NTgtNTc4M2MwMGEtYjQxNi00OTE1LTgyODgtYjJhZWE3Y2MxZGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE4MzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NWMwNzNhOGFhOTExNWE1YWQwOTJhZmY3NDgxNDM2NGZmNGQ1YTI4ODAwNDc3ZGNkZmU5ODcxMDQ1NGZjM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DCv7aDl_n9Okq7l0X9xW85qXhOSSEODpVT5zkQz-tw8">
> 
> 日志很明显，你的版本为2.1.4，你并没有删除镜像重新拉取镜像。

T_T。。。感谢大佬！~ 以为仓库同步过了，失误了。。。
现在是v4.0.3了，好了~

**Comment by HIT-ZY** [comment]
请问大佬是怎么解决discord有回复但是nextchat没反应的问题的

**Comment by qqwildfox** [comment]
> 请问大佬是怎么解决discord有回复但是nextchat没反应的问题的

我在其他issue里看到作者大佬的回复不知道理解的对不对，但是我的确通过给bot2也授予同bot1一样的discord三项权限解决了（配置bot1时候那三个按钮）

**Comment by ioa8j9g** [comment]
README 中关于如何获取 `USER_AUTHORIZATION` 的说明：

> 打开F12发送一次消息,在https://discord.com/api/v9/channels/1206*******703/messages 接口header中获取Authorization(USER_AUTHORIZATION)。

不太明白这句话的意思，其中 `1206*******703` 是什么呢？能分享一下详细的步骤吗？谢谢！

**Comment by qqwildfox** [comment]
> README 中关于如何获取 `USER_AUTHORIZATION` 的说明：
> 
> > 打开 F12 发送一次消息，在 `https://discord.com/api/v9/channels/1206*******703/messages` 接口 header 中获取 Authorization(USER_AUTHORIZATION)。
> 
> 不太明白这句话的意思，其中 `1206*******703` 是什么呢？能分享一下详细的步骤吗？谢谢！

F12->找到“网络”选项卡，在主窗口给机器人发送一次消息，网络选项卡里会出现一个‘messages’去里面找请求里的‘AUTHORIZATION’即可（那串数字是你发送消息的频道好像是）

**Comment by ioa8j9g** [comment]
@qqwildfox 感谢，设置成功了！

**Comment by Roulders** [comment]
USER_AUTHORIZATION
这个会过期吧，有没有自动获取这个的方式

**Comment by onlyGuo** [comment]
> > > v4.0.0已推送，多了两个环境变量。
> > 
> > 
> > 已重新部署，但是nextchat上无反应，查看discord确实是发了消息，但消息没有返回到nextchat~
> > 不知道是不是只有我是这样
> 
> 群里很多人都部署完成并可以正常使用了，你这个问题大概率是由于环境变量USER_ID设置错误导致的

跟你的一样，用postman查看接口发现返回的流choices.delta.content全是空串。

**Comment by ERCB** [comment]
> > README 中关于如何获取 `USER_AUTHORIZATION` 的说明：
> > > 打开 F12 发送一次消息，在 `https://discord.com/api/v9/channels/1206*******703/messages` 接口 header 中获取 Authorization(USER_AUTHORIZATION)。
> > 
> > 
> > 不太明白这句话的意思，其中 `1206*******703` 是什么呢？能分享一下详细的步骤吗？谢谢！
> 
> F12->找到“网络”选项卡，在主窗口给机器人发送一次消息，网络选项卡里会出现一个‘messages’去里面找请求里的‘AUTHORIZATION’即可（那串数字是你发送消息的频道好像是）

同问，其中 `1206*******703` 是CHANNEL_ID吗？

**Comment by ERCB** [comment]
> > README 中关于如何获取 `USER_AUTHORIZATION` 的说明：
> > > 打开 F12 发送一次消息，在 `https://discord.com/api/v9/channels/1206*******703/messages` 接口 header 中获取 Authorization(USER_AUTHORIZATION)。
> > 
> > 
> > 不太明白这句话的意思，其中 `1206*******703` 是什么呢？能分享一下详细的步骤吗？谢谢！
> 
> F12->找到“网络”选项卡，在主窗口给机器人发送一次消息，网络选项卡里会出现一个‘messages’去里面找请求里的‘AUTHORIZATION’即可（那串数字是你发送消息的频道好像是）

![image](https://github.com/deanxv/coze-discord-proxy/assets/2218697/4f53487d-9065-4172-b1c5-ae24038588c5)
我发送消息后 message 是红色，header里也没找到 AUTHORIZATION

**Comment by deanxv** [comment]
> USER_AUTHORIZATION
> 
> 这个会过期吧，有没有自动获取这个的方式

时间很长，只要足够活跃，discord还可能会帮你续期。

**Comment by deanxv** [comment]
> > > README 中关于如何获取 `USER_AUTHORIZATION` 的说明：
> 
> > > > 打开 F12 发送一次消息，在 `https://discord.com/api/v9/channels/1206*******703/messages` 接口 header 中获取 Authorization(USER_AUTHORIZATION)。
> 
> > > 
> 
> > > 
> 
> > > 不太明白这句话的意思，其中 `1206*******703` 是什么呢？能分享一下详细的步骤吗？谢谢！
> 
> > 
> 
> > F12->找到“网络”选项卡，在主窗口给机器人发送一次消息，网络选项卡里会出现一个‘messages’去里面找请求里的‘AUTHORIZATION’即可（那串数字是你发送消息的频道好像是）
> 
> 
> 
> ![image](https://github.com/deanxv/coze-discord-proxy/assets/2218697/4f53487d-9065-4172-b1c5-ae24038588c5)
> 
> 我发送消息后 message 是红色，header里也没找到 AUTHORIZATION

参考
![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/0afc43a1-e5f2-4466-8441-5fa067d9a45b)

**Comment by ERCB** [comment]
> > > > README 中关于如何获取 `USER_AUTHORIZATION` 的说明：
> > 
> > 
> > > > > 打开 F12 发送一次消息，在 `https://discord.com/api/v9/channels/1206*******703/messages` 接口 header 中获取 Authorization(USER_AUTHORIZATION)。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 不太明白这句话的意思，其中 `1206*******703` 是什么呢？能分享一下详细的步骤吗？谢谢！
> > 
> > 
> > > 
> > 
> > 
> > > F12->找到“网络”选项卡，在主窗口给机器人发送一次消息，网络选项卡里会出现一个‘messages’去里面找请求里的‘AUTHORIZATION’即可（那串数字是你发送消息的频道好像是）
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/2218697/307049888-4f53487d-9065-4172-b1c5-ae24038588c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MTY1OTYsIm5iZiI6MTcwODYxNjI5NiwicGF0aCI6Ii8yMjE4Njk3LzMwNzA0OTg4OC00ZjUzNDg3ZC05MDY1LTQxNzItYjFjNS1hZTI0MDM4NTg4YzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMTUzODE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQ3NGEwN2Y0ZmRmZTQ5NmU5ZmM5MjJjNDNjZDc4N2Q5MTE2OTE2ZjU5Yzg0ODU4M2U0N2FhNDRkNGZmMjVlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-OV_HvkHwmgKgy_o7uZ_B2cVRtgbWSZ5P9A1Q-Ne7_A)
> > 我发送消息后 message 是红色，header里也没找到 AUTHORIZATION
> 
> 参考 ![image](https://private-user-images.githubusercontent.com/57529708/307051672-0afc43a1-e5f2-4466-8441-5fa067d9a45b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MTY1OTYsIm5iZiI6MTcwODYxNjI5NiwicGF0aCI6Ii81NzUyOTcwOC8zMDcwNTE2NzItMGFmYzQzYTEtZTVmMi00NDY2LTg0NDEtNWZhMDY3ZDlhNDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE1MzgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZmFlMDBlMDc3MzdjNTc5YTVjMzFkNzgyYjkwOTFiOGZiNGFlMDMxNzk4NjVhMGI4MmY0MDk2MzBiZWE2NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1rDTVkcWUx85ldqx6-CUFnOsMXO1sMAZF3OYWZzvDDA)

拿到AUTHORIZATION了，感谢大佬～

**Comment by baymax55** [comment]
我也是 bot中的三个权限没有打开导致前端收不到消息

**Comment by KasonWan** [comment]
大佬，能否加个参数控制不用json格式进行提问。
![image](https://github.com/deanxv/coze-discord-proxy/assets/58059719/22b9d7ce-f0bf-4aa3-a093-d869c693c147)
