### ISSUE TITLE
真的抱歉点错了不小心点到了pr，请问如何撤销求救

### ISSUE THREAD

**Issue by qqwildfox** [deanxv/coze-discord-proxy#69]
大佬您好我不小心点到了pr请问如何撤销我的操作？
真的抱歉真的抱歉真的抱歉55

**Comment by deanxv** [comment]
你那里应该有撤回或者取消，实在找不到也没关系的，晚点我拒绝掉就好了

**Comment by qqwildfox** [comment]
> 你那里应该有撤回或者取消，实在找不到也没关系的，晚点我拒绝掉就好了

好的好的我也在找按钮大佬，给您添麻烦了，谢谢
