### ISSUE TITLE
请问作者是否有对接oneapi的计划打算呢

### ISSUE THREAD

**Issue by leezhuuu** [deanxv/coze-discord-proxy#7]
请问作者是否有对接oneapi的计划打算呢

**Comment by deanxv** [comment]
> 请问作者是否有对接oneapi的计划打算呢

有的 会另外写与openai对齐的接口

**Comment by deanxv** [comment]
已添加接口

**Comment by leezhuuu** [comment]
效率好高

**Comment by leezhuuu** [comment]
是否支持v1/image或者v1/file接口呢，希望作者适配一下

**Comment by deanxv** [comment]
> 是否支持v1/image或者v1/file接口呢，希望作者适配一下

大概率应该都会放到计划中

**Comment by leezhuuu** [comment]
哦哦哦，这个已经是旧的issue了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月1日(周四) 凌晨1:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [deanxv/coze-discord-proxy] 请问作者是否有对接oneapi的计划打算呢 (Issue #7)




 
已集成很多了 请麻烦看下还需要哪些
