### ISSUE TITLE
频道已创建但没有发送对话

### ISSUE THREAD

**Issue by GavinGoo** [deanxv/coze-discord-proxy#70]
**例行检查**

+ [ &#10004;] 我已确认目前没有类似 issue
+ [ &#10004;] 我已确认我已升级到最新版本
+ [ &#10004;] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ &#10004;] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
更新前可正常发送对话，仅coze bot没有回复
更新截止目前的最新版(v4..0.3)并加入了两个新变量后，频道创建成功，但是没有发送对话。代理也换了几次，应该不是网络问题？
望作者大佬与路过的各位提供帮助，在此感激不尽
同时感谢作者的项目，曲折且独特的实现思路

**相关截图**
**1. 频道创建成功, 但并没有发送对话**
![微信图片_20240222025129](https://github.com/deanxv/coze-discord-proxy/assets/30521171/599792f0-18df-4961-b094-b62a22a2d5cd)

**2. Log & Postman 信息**
![微信图片_20240222022859](https://github.com/deanxv/coze-discord-proxy/assets/30521171/f4b7b1c4-446b-480e-a9a6-de87d6208c53)

**3. Docker 配置**
![微信图片_20240222023549](https://github.com/deanxv/coze-discord-proxy/assets/30521171/0f7444cb-be81-468a-9de5-4ebaa4548f4b)

**4. Bot 配置 & 在线情况**
![微信图片_20240222025026](https://github.com/deanxv/coze-discord-proxy/assets/30521171/46944678-b4f5-43d4-9075-6408de324e87)
![微信图片_20240222025142](https://github.com/deanxv/coze-discord-proxy/assets/30521171/da13c8dc-5ea3-444f-b76a-c8424a2df375)

**Comment by deanxv** [comment]
这个报错就是因为你的代理请求discord超时或者被拒绝了，你可以用一台国外vps部署服务测试一下是否和代理有关系

**Comment by GavinGoo** [comment]
> 这个报错就是因为你的代理请求discord超时或者被拒绝了，你可以用一台国外vps部署服务测试一下是否和代理有关系

我部署上去试了一下，还真是网络问题，奇了怪了
感谢解答

**Comment by deanxv** [comment]
排查了下，是4.0版本下使用用户端发送消息未使用代理的原因，晚些会修复

**Comment by GavinGoo** [comment]
> 排查了下，是4.0版本下使用用户端发送消息未使用代理的原因，晚些会修复

感谢，辛苦了！
