### ISSUE TITLE
dial tcp 128.242.245.93:443: i/o timeout

### ISSUE THREAD

**Issue by czd99053** [deanxv/coze-discord-proxy#71]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
只是增加了4.0.3的两个变量，其他参数没有变，但是日志报错
**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by czd99053** [comment]
curl -x socks5://10.0.16.2:10808 https://discord.com/api/v9/channels/1210019908692353104/messages
{"message": "401: Unauthorized", "code": 
代理没有问题，
- PROXY_URL=socks5://10.0.16.2:10808

**Comment by czd99053** [comment]
日志报错
[ERR] 2024/02/22 - 08:41:26 | 20240222084055970760420qG6ICAxG | error sending message: Post "https://discord.com/api/v9/channels/1210023385883484160/messages": dial tcp 199.59.148.89:443: i/o timeout 
Error sending request: Post "https://discord.com/api/v9/channels/1210023385883484160/messages": dial tcp 199.59.148.89:443: i/o timeout
[GIN] 2024/02/22 - 08:41:26 | 20240222084055970760420qG6ICAxG | 200 | 30.633441691s |    103.36.25.18 |    POST /v1/chat/completions

**Comment by deanxv** [comment]
代理不支持socks，只支持http

**Comment by czd99053** [comment]
大神回话了，我之前一直用的socks5没有问题，刚才修改为http后，还是不行
![1708563833779](https://github.com/deanxv/coze-discord-proxy/assets/36181614/5870d665-c92c-46d9-8dc4-b5edaae2d62d)
在discord看，新建了一个频道，但是没有发送消息

**Comment by czd99053** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/36181614/6c07a903-12e7-410a-a3cc-2e31f9c571bb)
我的配置如下
version: '3.4'
 
services:
  coze-discord-proxy:
    image: deanxv/coze-discord-proxy:latest
    # 如果你的网络环境访问docker hub不稳定的话，可以把上面的镜像地址改为下面的地址进行下载镜像
    #image: dockerproxy.com/deanxv/coze-discord-proxy:latest
    container_name: coze-discord-proxy
    restart: always
    ports:
      - "7077:7077"
    volumes:
      - ./data:/app/coze-discord-proxy/data
    environment:
      - USER_ID=1049912XXXXXXXXXXXXX
      - USER_AUTHORIZATION=MTA0OTkxMjcxxxxxxxxxx
      - BOT_TOKEN=MTIwNzY0NTQxxxxxxxxxxx
      # 此处Toekn为我们主动发送消息的Discord机器人的Token
      - GUILD_ID=1091145xxxxxxx
      # 此处为两个Discord机器人所在的同一个服务器ID
      - COZE_BOT_ID=1207639xxxxxxxxx
      # 此处为与Coze Bot进行绑定的Discord机器人的ID
      - CHANNEL_ID=1091145xxxxxxxxx
      # 默认频道(就是创建服务器之后默认会有个常规的频道)-在使用与openai对齐的接口时(/v1/chat/completions) 消息会默认发送到此频道
      - CHANNEL_AUTO_DEL_TIME=3600
      # [可选]频道自动删除时间(秒) 内的历史消息，此参数为每次对话完成后自动删除频道的历史消息(默认为5s)，为空或0时则不删除，推荐不设置(但是如果频道消息满了，需要自行到频
道里手动删除)
      - PROXY_SECRET=xxxxxxx
      # [可选]接口密钥-修改此行为请求头校验的值（多个请以,分隔；前后端统一）你可以理解为API KEY
      #- PROXY_URL=socks5://10.0.16.2:10808
      - PROXY_URL=http://10.0.16.2:10809
      # [可选]如果你服务器访问不了Discord API，那么尝试配置代理
      - TZ=Asia/Shanghai
      - USER_AGENT=Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36

**Comment by czd99053** [comment]
在discord看创新了一个频道，但是没有发送消息，感觉网络没有问题是不是我的配置有问题
- USER_ID=1049912XXXXXXXXXXXXX
这个我取的是我discord自身的号（非BOT）
- USER_AUTHORIZATION=MTA0OTkxMjcxxxxxxxxxx
- 这个我取的是我discord自身的号（非BOT）在F12中获取的AUTHORIZATION

**Comment by deanxv** [comment]
排查了下，是4.0版本下使用用户端发送消息未使用代理的原因，晚些会修复

**Comment by czd99053** [comment]
厉害
赞啊！！！！

**Comment by deanxv** [comment]
v4.0.4修复此问题，拉取最新镜像

**Comment by czd99053** [comment]
已部署，可以使用自己的id提出问题了，discode中也回答了问题，但是在Nextchat中一直是等待状态，貌似没有获得coze-discord-proxy的返回

**Comment by deanxv** [comment]
> 已部署，可以使用自己的id提出问题了，discode中也回答了问题，但是在Nextchat中一直是等待状态，貌似没有获得coze-discord-proxy的返回

涉及到的所有bot，重新给这三个权限。
![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/2915ee34-6872-45fe-a365-63327d8e46ed)

**Comment by czd99053** [comment]
感觉不如之前稳定了，
[GIN] 2024/02/22 - 11:05:28 | 20240222110528391572292VARmri3T | 204 |      29.847µs |     111.25.0.80 | OPTIONS /v1/chat/completions
[ERR] 2024/02/22 - 11:05:30 | 202402221105284250662252wcnX8uU | error sending message: Post "https://discord.com/api/v9/channels/1210059760209100870/messages": EOF 
Error sending request: Post "https://discord.com/api/v9/channels/1210059760209100870/messages": EOF
[GIN] 2024/02/22 - 11:05:30 | 202402221105284250662252wcnX8uU | 200 |  2.162940463s |     111.25.0.80 |    POST /v1/chat/completions

偶尔报错
![image](https://github.com/deanxv/coze-discord-proxy/assets/36181614/fe23a343-a0c6-49f3-8b65-9d8c2ea6caec)

**Comment by deanxv** [comment]
因为昨天coze限制了bot@bot的消息，所以改为了用户端发送消息，在一定的并发下可能会出现问题

**Comment by czd99053** [comment]
明白了，版主的建立接口的思路太棒了
