### ISSUE TITLE
如果返回的结果异常，则创建的频道不会自动删除

### ISSUE THREAD

**Issue by KasonWan** [deanxv/coze-discord-proxy#72]
**问题描述**
如果返回的结果异常，则创建的频道不会自动删除
**相关截图**
![1708576576323](https://github.com/deanxv/coze-discord-proxy/assets/58059719/d1b0b82e-0768-49de-9883-16aefb1ffdc5)

**Comment by deanxv** [comment]
会，服务不重启的话，5分钟自动删除异常的对话频道
