### ISSUE TITLE
大家有遇到这个问题吗：Something wrong occurs, please retry. If the error persists, please contact the support team.

### ISSUE THREAD

**Issue by czd99053** [deanxv/coze-discord-proxy#73]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
在discord中即使是人工@bot，也会收到这个结果，不论提的问题是什么，想问下大家有没有遇到这个问题的
**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by ShanySky** [comment]
有过，这是coze平台用的人太多导致的。现在coze免费开放使用，用的人比较多，在高峰的时候就会出现这个问题。

**Comment by czd99053** [comment]
多谢楼上兄弟解惑

**Comment by KasonWan** [comment]
现在经常出现这个问题

**Comment by kshz1445433** [comment]
我现在也是这个问题

**Comment by kshz1445433** [comment]
> 有过，这是coze平台用的人太多导致的。现在coze免费开放使用，用的人比较多，在高峰的时候就会出现这个问题。

大哥大哥，有什么办法可以避免这个问题吗？

**Comment by ShanySky** [comment]
> > 有过，这是coze平台用的人太多导致的。现在coze免费开放使用，用的人比较多，在高峰的时候就会出现这个问题。
> 
> 大哥大哥，有什么办法可以避免这个问题吗？

没有，只能等coze官方完善或者直接调用openai的官方接口。现在第三方代理的接口都可能会有问题，比如说偶尔将一个gpt3.5接口当成gpt4给你用，或者速度慢、容易崩。即使是微软的Azure的openai的接口也有调用gpt4接口速度慢的问题。
