### ISSUE TITLE
更新了大佬的两个配置，也能看到创建频道并且AI回答问题的，但是回答的内容回传不到第三方去了，这个是什么问题呢

### ISSUE THREAD

**Issue by 864579035** [deanxv/coze-discord-proxy#75]
![20bfb56167b7c185070c4286a956ba3](https://github.com/deanxv/coze-discord-proxy/assets/60454608/03a64d86-10d3-484b-94f4-f2fc5fb70f85)
![511ab9f8a7a77200efd0f3db3c3893b](https://github.com/deanxv/coze-discord-proxy/assets/60454608/2b04f466-54f5-4ed2-97c3-5a1a31422f41)

**Comment by Alocem** [comment]
我也有这种情况，请求画图时，对话平台中的响应时间到了10秒就超时了。
![image](https://github.com/deanxv/coze-discord-proxy/assets/71489252/9322d1aa-c68f-4af4-9aa6-5e5a44a82f72)
而查看docker日志，从请求到返回的时间是消耗了38秒。
![image](https://github.com/deanxv/coze-discord-proxy/assets/71489252/3021409a-abfd-4776-b4c2-e43d0b5dc1c9)
不知道是否是nextchat对话框的问题，docker-compose设置了STREAM_REQUEST_OUT_TIME=600。

**Comment by kshz1445433** [comment]
> 我也有这种情况，请求画图时，对话平台中的响应时间到了10秒就超时了。 ![image](https://private-user-images.githubusercontent.com/71489252/306962333-9322d1aa-c68f-4af4-9aa6-5e5a44a82f72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTkwNjYsIm5iZiI6MTcwODU5ODc2NiwicGF0aCI6Ii83MTQ4OTI1Mi8zMDY5NjIzMzMtOTMyMmQxYWEtYzY4Zi00YWY0LTlhYTYtNWU1YTQ0YTgyZjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEwNDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzODAyNDcyMzExZWEzMmQ4NzQxOGM4ODQzYmUyNjg2N2RlZGEzNjdmNjAzYjkxZTA5YmEzN2YxNzU0YzExMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eTlEfidelMHxUWa5KtVc5q8HZ_YJySq70Mr-i2LC4mo) 而查看docker日志，从请求到返回的时间是消耗了38秒。 ![image](https://private-user-images.githubusercontent.com/71489252/306962762-3021409a-abfd-4776-b4c2-e43d0b5dc1c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTkwNjYsIm5iZiI6MTcwODU5ODc2NiwicGF0aCI6Ii83MTQ4OTI1Mi8zMDY5NjI3NjItMzAyMTQwOWEtYWJmZC00Nzc2LWI0YzItZTQzZDBiNWRjMWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEwNDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYTk4NzYwZWI1ZDRhNTM1Yzk1MTY3YTYyYWExYjZiZDdjYTMxNzhmMjhjZTliMDQ3NjhhYzZmYTU3NjVhOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._XFGmdMNTgKUQv4Rar41tYtQ8cxNIXAoOyyzAdcb4t0) 不知道是否是nextchat对话框的问题，docker-compose设置了STREAM_REQUEST_OUT_TIME=600。 discord对话频道有返回 ![image](https://private-user-images.githubusercontent.com/71489252/306965028-75aebc08-7f91-494a-817e-aa6ec3cc7ceb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTkwNjYsIm5iZiI6MTcwODU5ODc2NiwicGF0aCI6Ii83MTQ4OTI1Mi8zMDY5NjUwMjgtNzVhZWJjMDgtN2Y5MS00OTRhLTgxN2UtYWE2ZWMzY2M3Y2ViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEwNDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMGM0YzNiNTBmY2M1YmNmOTRkMDI5MWYxYWEyYjJlNWI3YTUwYzZiMmFjYzRjNDJkYmY2NzI0MjJlNTM2NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3dATQI2HwDD-yhHztVqw2KPL0xAs6RC6J6X6IdHdzj0)

为啥你们都有内容返回，我的回答一直是Something wrong occurs, please retry. If the error persists, please contact the support team.

**Comment by Alocem** [comment]
> > 我也有这种情况，请求画图时，对话平台中的响应时间到了10秒就超时了。 ![image](https://private-user-images.githubusercontent.com/71489252/306962333-9322d1aa-c68f-4af4-9aa6-5e5a44a82f72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTkwNjYsIm5iZiI6MTcwODU5ODc2NiwicGF0aCI6Ii83MTQ4OTI1Mi8zMDY5NjIzMzMtOTMyMmQxYWEtYzY4Zi00YWY0LTlhYTYtNWU1YTQ0YTgyZjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEwNDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzODAyNDcyMzExZWEzMmQ4NzQxOGM4ODQzYmUyNjg2N2RlZGEzNjdmNjAzYjkxZTA5YmEzN2YxNzU0YzExMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eTlEfidelMHxUWa5KtVc5q8HZ_YJySq70Mr-i2LC4mo) 而查看docker日志，从请求到返回的时间是消耗了38秒。 ![image](https://private-user-images.githubusercontent.com/71489252/306962762-3021409a-abfd-4776-b4c2-e43d0b5dc1c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTkwNjYsIm5iZiI6MTcwODU5ODc2NiwicGF0aCI6Ii83MTQ4OTI1Mi8zMDY5NjI3NjItMzAyMTQwOWEtYWJmZC00Nzc2LWI0YzItZTQzZDBiNWRjMWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEwNDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYTk4NzYwZWI1ZDRhNTM1Yzk1MTY3YTYyYWExYjZiZDdjYTMxNzhmMjhjZTliMDQ3NjhhYzZmYTU3NjVhOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._XFGmdMNTgKUQv4Rar41tYtQ8cxNIXAoOyyzAdcb4t0) 不知道是否是nextchat对话框的问题，docker-compose设置了STREAM_REQUEST_OUT_TIME=600。 discord对话频道有返回 ![image](https://private-user-images.githubusercontent.com/71489252/306965028-75aebc08-7f91-494a-817e-aa6ec3cc7ceb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTkwNjYsIm5iZiI6MTcwODU5ODc2NiwicGF0aCI6Ii83MTQ4OTI1Mi8zMDY5NjUwMjgtNzVhZWJjMDgtN2Y5MS00OTRhLTgxN2UtYWE2ZWMzY2M3Y2ViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEwNDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMGM0YzNiNTBmY2M1YmNmOTRkMDI5MWYxYWEyYjJlNWI3YTUwYzZiMmFjYzRjNDJkYmY2NzI0MjJlNTM2NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3dATQI2HwDD-yhHztVqw2KPL0xAs6RC6J6X6IdHdzj0)
> 
> 为啥你们都有内容返回，我的回答一直是Something wrong occurs, please retry. If the error persists, please contact the support team.

被限制了，换个discord用户或者等到明天再次尝试

**Comment by deanxv** [comment]
所有bot打开权限
![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/22bb9142-6f48-4cb4-b253-7647d6f3c4d0)

**Comment by Alocem** [comment]
> 所有bot打开权限 ![image](https://private-user-images.githubusercontent.com/57529708/306971357-22bb9142-6f48-4cb4-b253-7647d6f3c4d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDE0NzQsIm5iZiI6MTcwODYwMTE3NCwicGF0aCI6Ii81NzUyOTcwOC8zMDY5NzEzNTctMjJiYjkxNDItNmY0OC00Y2I0LWIyNTMtNzY0N2Q2ZjNjNGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDExMjYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkN2IyYmYxY2Q5MzczZWJiOTdkOTJjN2UyY2ZmNWQ2MWJjMTJhNzY5ZGQwYWU3ZmRjZjMxMTc2OGFjNjVlYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p8lM1YtO5TUB3ulCYGu3IQEzQdaCW8UlBuVHVZbieNQ)

bot权限都开了，可以收到文字回复，图片会显示超时。
![image](https://github.com/deanxv/coze-discord-proxy/assets/71489252/c2d9dbc6-c35f-4ae4-8462-c26aee10f068)
