### ISSUE TITLE
我无法使用cozebot

### ISSUE THREAD

**Issue by MisZang** [deanxv/coze-discord-proxy#78]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
无法使用bot，discoder和nextchat都无法使用，这是nextchat错误代码：{
  "error": {
    "message": "no_available_user_auth",
    "type": "invalid_request_error",
    "param": "",
    "code": "invalid_parameter"
  }
}
render错误代码：==> Starting service...
[SYS] 2024/02/22 - 23:19:18 | COZE-DISCORD-PROXY v4.1.1 started 
[SYS] 2024/02/22 - 23:19:18 | Environment variable check passed. 
[SYS] 2024/02/22 - 23:19:18 | Bot is now running. Enjoy It. 
Your service is live 🎉
[GIN] 2024/02/22 - 23:19:22 | 202402222319224620572339wmAbqeH | 404 |         940ns |   35.227.183.65 |     GET /
==> Detected service running on port 10000
==> Docs on specifying a port: https://render.com/docs/web-services#port-detection
[GIN] 2024/02/22 - 23:19:28 | 20240222231928357529329mSem4Vaj | 204 |        6.04µs |       45.9.8.34 | OPTIONS /v1/chat/completions
[WARN] 2024/02/22 - 23:19:29 | 20240222231928823542910CtC4cBd9 | USER_AUTHORIZATION: 已失效 
[ERR] 2024/02/22 - 23:19:30 | 20240222231928823542910CtC4cBd9 | error sending message: USER_AUTHORIZATION 无效 
[GIN] 2024/02/22 - 23:19:30 | 20240222231928823542910CtC4cBd9 | 200 |  2.107646751s |       45.9.8.34 |    POST /v1/chat/completions
[GIN] 2024/02/22 - 23:19:31 | 20240222231931227011108oMa8LjqK | 204 |        6.18µs |       45.9.8.34 | OPTIONS /v1/chat/completions
[GIN] 2024/02/22 - 23:19:31 | 20240222231931519591283MfDbdBkA | 200 |       43.21µs |       45.9.8.34 |    POST /v1/chat/completions
[ERR] 2024/02/22 - 23:19:31 | 20240222231931519591283MfDbdBkA | 无可用的 user_auth ！

**复现步骤**

**预期结果**

**相关截图**
[屏幕截图 2024-02-22 233033](https://github.com/deanxv/coze-discord-proxy/assets/128830363/120b6906-9d3f-470a-823f-dd83dda88658)

**Comment by deanxv** [comment]
少了个环境变量 参考

![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/e17b125b-43a4-467a-9a59-6773058d2780)
