### ISSUE TITLE
/api/chat 无效 /api/chat/ 可以

### ISSUE THREAD

**Issue by xtccc** [deanxv/coze-discord-proxy#8]
**例行检查**

+ [x ] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
/api/chat 无效
/api/chat/ 有效
**复现步骤**
http post  http://127.0.0.1:7077/api/chat  -j <data.json
http post  http://127.0.0.1:7077/api/chat/   -j <data.json

**预期结果**
根据文档应该都行把，或者改改文档， 作为十分相信文档的人，怀疑了半天是那里错了
**相关截图**
![image](https://github.com/deanxv/coze-discord-proxy/assets/37169212/f743a489-5b09-4bad-a9b5-28f3eae8dec3)

如果没有的话，请删除此节。

**Comment by deanxv** [comment]
使用postman等工具试试呢

**Comment by xtccc** [comment]
curl 也是一样， 
不会用postman
![image](https://github.com/deanxv/coze-discord-proxy/assets/37169212/49251cf6-755f-4a26-ba3c-891ad59c18ea)

**Comment by deanxv** [comment]
> curl 也是一样， 不会用postman ![image](https://private-user-images.githubusercontent.com/37169212/300180742-49251cf6-755f-4a26-ba3c-891ad59c18ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNjI0OTAsIm5iZiI6MTcwNjM2MjE5MCwicGF0aCI6Ii8zNzE2OTIxMi8zMDAxODA3NDItNDkyNTFjZjYtNzU1Zi00YTI2LWJhM2MtODkxYWQ1OWMxOGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDEzMjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxOWUwNjMzZTYxYWI1ODdhNDJmZjA1MWZlNmU3NDY1MGFhYmIzYzk0OWU3ZTZlM2M3NzZmNzNiNzBlMGQ1MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d5lswjFkZJIAKZ6go881pnY48vpOE0iT91SvRTW8KBk)

url去掉单引号试下

**Comment by xtccc** [comment]
> > curl 也是一样， 不会用postman ![image](https://private-user-images.githubusercontent.com/37169212/300180742-49251cf6-755f-4a26-ba3c-891ad59c18ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNjI0OTAsIm5iZiI6MTcwNjM2MjE5MCwicGF0aCI6Ii8zNzE2OTIxMi8zMDAxODA3NDItNDkyNTFjZjYtNzU1Zi00YTI2LWJhM2MtODkxYWQ1OWMxOGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDEzMjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxOWUwNjMzZTYxYWI1ODdhNDJmZjA1MWZlNmU3NDY1MGFhYmIzYzk0OWU3ZTZlM2M3NzZmNzNiNzBlMGQ1MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d5lswjFkZJIAKZ6go881pnY48vpOE0iT91SvRTW8KBk)
> 
> url去掉单引号试下
一样啊，不是我客户端的问题吧
![image](https://github.com/deanxv/coze-discord-proxy/assets/37169212/0f3544ff-a735-4a18-a826-3bfaa36cd9df)

**Comment by deanxv** [comment]
> > > curl 也是一样， 不会用postman ![image](https://private-user-images.githubusercontent.com/37169212/300180742-49251cf6-755f-4a26-ba3c-891ad59c18ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNjI0OTAsIm5iZiI6MTcwNjM2MjE5MCwicGF0aCI6Ii8zNzE2OTIxMi8zMDAxODA3NDItNDkyNTFjZjYtNzU1Zi00YTI2LWJhM2MtODkxYWQ1OWMxOGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDEzMjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxOWUwNjMzZTYxYWI1ODdhNDJmZjA1MWZlNmU3NDY1MGFhYmIzYzk0OWU3ZTZlM2M3NzZmNzNiNzBlMGQ1MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d5lswjFkZJIAKZ6go881pnY48vpOE0iT91SvRTW8KBk)
> > 
> > 
> > url去掉单引号试下
> 
> 一样啊，不是我客户端的问题吧 ![image](https://private-user-images.githubusercontent.com/37169212/300181215-0f3544ff-a735-4a18-a826-3bfaa36cd9df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNjMwMzksIm5iZiI6MTcwNjM2MjczOSwicGF0aCI6Ii8zNzE2OTIxMi8zMDAxODEyMTUtMGYzNTQ0ZmYtYTczNS00YTE4LWE4MjYtM2JmYWEzNmNkOWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDEzMzg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYTY4OTFhZDM2NDNjMmViNzQ0MDM1MGE0ZTBhZmJkMzMzM2FkYWU2ZTM3ZjEzMWQ0NDQzNTRkNzExZWFjMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PMFjYhG16pVrKa_Kc7RrSuvuAamKKeKhGjwa0ttoMdA)

啊好像是curl的问题 我用curl的命令也要加/ 用其他的命令和postman工具就不需要了

**Comment by xtccc** [comment]
我写了个golang 客户端，确实不用加 /
  
建议readme里还是提一下吧，不然不懂的人 还是会有困惑的

**Comment by deanxv** [comment]
> 我写了个golang 客户端，确实不用加 /
> 
> 建议readme里还是提一下吧，不然不懂的人 还是会有困惑的
是的 一会我更新下

**Comment by deanxv** [comment]
问题已修复

**Comment by xtccc** [comment]
可以了
使用deanxv/coze-discord-proxy 
3d90aa179c52


```
curl -X 'POST' \
  http://gitea:7077/api/chat \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "channelId": "1200775893551960145",
  "content": "string",
  "stream": true
}'
event:message
data:Could you please clarify what you

```
