### ISSUE TITLE
多机器人配置报错，环境变量和bot_config配置都正常

### ISSUE THREAD

**Issue by eiweorerw** [deanxv/coze-discord-proxy#84]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
多机器人配置以后，创建频道正常，/v1/chat/completions返回authorization(proxy-secret)校验失败，header已加Authorization和proxy-secret，环境变量已配置多个secret
**复现步骤**

**预期结果**

**Comment by deanxv** [comment]
提供服务启动日志，请求头+参数截图，环境变量。

**Comment by deanxv** [comment]
你这个请求中出现太多问题了

1. 环境变量PROXY_SECRET在openai接口中是当作API_KEY的用法，你的请求头中的Authorization的value不仅不对，格式也不对，请去查看openai官方接口文档后再使用本项目调试。

2. 请求参数的model是gpt-4，而你的json中并未定义model为gpt-4的bot。

...我不能一步一步帮你排查出所有问题，有些细节还是要自己注意下。

**Comment by GoTop** [comment]
@eiweorerw 我也遇到相同的问题 #92 ，请问你的问题解决了吗？具体是怎么处理的？

**Comment by eiweorerw** [comment]
@GoTop 就是header里Authorization的值不对，理解错了，这里面放的就是PROXY_SECRET的值

**Comment by yingyuweiying** [comment]
这个请求头要怎么改呢，文档里没有说过啊
