### ISSUE TITLE
choices[0]->delta->content始终为空值

### ISSUE THREAD

**Issue by ShiFangJuMie** [deanxv/coze-discord-proxy#87]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**

今天刚刚部署的，所以是最新版本。在discord的聊天中有返回信息，API拿不到信息

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/deanxv/coze-discord-proxy/assets/9131886/de31008a-6578-4b64-913e-1211b343608a)

![image](https://github.com/deanxv/coze-discord-proxy/assets/9131886/6c579523-3962-42e0-93ce-9a913c07be1b)

![image](https://github.com/deanxv/coze-discord-proxy/assets/9131886/b7e754f1-6dcf-4bc8-be7a-5fd51170d6fc)

**Comment by deanxv** [comment]
**所有**bot打开以下权限
![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/29990013-b55a-4ee4-9b79-2ba6fe7d7e96)
