### ISSUE TITLE
在readme里添加一个使用源码运行的示例

### ISSUE THREAD

**Issue by atorber** [deanxv/coze-discord-proxy#89]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**功能描述**

在readme中添加一个基于源码运行的示例

**应用场景**

方便进行调试及二次开发

**Comment by sdlkhfksl** [comment]
Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

**Comment by HQ-Zhang-233** [comment]
+1，跪求一个在python环境，流式调用，和非流式调用的示例代码……

**Comment by deanxv** [comment]
> +1，跪求一个在python环境，流式调用，和非流式调用的示例代码……

接口和openai对齐的，示例代码直接在openai官方接口文档查询即可。
