### ISSUE TITLE
文生图没有返回图片url

### ISSUE THREAD

**Issue by yuanwangz** [deanxv/coze-discord-proxy#9]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
discord里coze机器人生成完图片后接口里返回url是空的。
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/deanxv/coze-discord-proxy/assets/34086226/bcef6663-dcad-4e79-8fde-67b3dc65cc24)

**Comment by deanxv** [comment]
> **例行检查**
> 
> * [x]  我已确认目前没有类似 issue
> * [x]  我已确认我已升级到最新版本
> * [x]  我理解并愿意跟进此 issue，协助测试和提供反馈
> * [x]  我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭
> 
> **问题描述** discord里coze机器人生成完图片后接口里返回url是空的。 **复现步骤**
> 
> **预期结果**
> 
> **相关截图** ![image](https://private-user-images.githubusercontent.com/34086226/300235051-bcef6663-dcad-4e79-8fde-67b3dc65cc24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTY1NjUsIm5iZiI6MTcwNjQxNjI2NSwicGF0aCI6Ii8zNDA4NjIyNi8zMDAyMzUwNTEtYmNlZjY2NjMtZGNhZC00ZTc5LThmZGUtNjdiM2RjNjVjYzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDA0MzEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNzlkMDYzY2I5NjBlMWU3ZWQ4MGQ1MzNkNjdmOTNlYThkZjRjYmM0NjQwNTE4Zjc5OTViOTNiYmY0ODk2NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d_t1gRPcfvR0dB2pU0teHzNs_DasrPaqvCN7GpxSxhI)

目前对于openai对齐接口中还未集成图片（在计划中），项目自有接口可以返回。

**Comment by deanxv** [comment]
已支持！
![asubfa](https://github.com/deanxv/coze-discord-proxy/assets/57529708/e7325ab3-f065-4cc5-987e-5c3b463af3f7)
![sdfawe](https://github.com/deanxv/coze-discord-proxy/assets/57529708/154cf9ea-bb9d-4d2b-892c-01249d5d3dbd)
