### ISSUE TITLE
配置单bot和多bot都会出现"authorization(proxy-secret)校验失败"错误

### ISSUE THREAD

**Issue by GoTop** [deanxv/coze-discord-proxy#92]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
配置单bot和多bot，使用postman测试的时候，都会出现"authorization(proxy-secret)校验失败"错误
**复现步骤**
配置文件：
<img width="1067" alt="截屏2024-02-25 22 32 16" src="https://github.com/deanxv/coze-discord-proxy/assets/1784319/c78bcc23-63ff-421f-8f24-6516b35f98ca">
<img width="368" alt="截屏2024-02-25 22 32 28" src="https://github.com/deanxv/coze-discord-proxy/assets/1784319/ff23f7c2-5c62-4b3b-bfff-388d61c6f788">

运行情况：
<img width="1269" alt="截屏2024-02-25 22 26 48" src="https://github.com/deanxv/coze-discord-proxy/assets/1784319/de800685-f291-413e-a697-ce49f0576607">

测试情况：
<img width="960" alt="截屏2024-02-25 22 28 09" src="https://github.com/deanxv/coze-discord-proxy/assets/1784319/5dde2903-1b8a-413e-96bf-a5aeac46e80e">

<img width="959" alt="截屏2024-02-25 22 27 10" src="https://github.com/deanxv/coze-discord-proxy/assets/1784319/d7544d92-8f99-4a47-8f43-980c673f0fdb">

**Comment by deanxv** [comment]
请按照openai请求头格式请求
Authorization:Bearer ******

**Comment by GoTop** [comment]
> 请按照openai请求头格式请求 Authorization:Bearer ******

换成Authorization:Bearer 1，也还是同样的错误提示

<img width="910" alt="截屏2024-02-25 22 46 29" src="https://github.com/deanxv/coze-discord-proxy/assets/1784319/ebf6508d-6086-4fed-9907-de16f231a5c0">

**Comment by deanxv** [comment]
部署到公网，提供ip端口秘钥，我远程调用一下

**Comment by zhaoyanxue666** [comment]
楼主，我也出现了这样的报错openai.error.AuthenticationError: authorization(proxy-secret)校验失败

**Comment by GoTop** [comment]
> 部署到公网，提供ip端口秘钥，我远程调用一下

好的，感谢～

zeabur.com现在好像不能免费部署docker了？提示我需要付费才能启动docker

<img width="372" alt="截屏2024-02-25 23 21 11" src="https://github.com/deanxv/coze-discord-proxy/assets/1784319/ebcd90c2-1ad7-40ec-b4b1-c6f6e4fe34da">

**Comment by deanxv** [comment]
> > 部署到公网，提供ip端口秘钥，我远程调用一下
> 
> 好的，感谢～
> 
> zeabur.com现在好像不能免费部署docker了？提示我需要付费才能启动docker
> 
> <img alt="截屏2024-02-25 23 21 11" width="372" src="https://private-user-images.githubusercontent.com/1784319/307602112-ebcd90c2-1ad7-40ec-b4b1-c6f6e4fe34da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzQ4MTAsIm5iZiI6MTcwODg3NDUxMCwicGF0aCI6Ii8xNzg0MzE5LzMwNzYwMjExMi1lYmNkOTBjMi0xYWQ3LTQwZWMtYjRiMS1jNmY2ZTRmZTM0ZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjVUMTUyMTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmFiMmFjY2Y3OWRmYTUyNDM1ZTA1N2UxNjZmNDgxMTNlZmM2ODMxZDc3MzRkY2EwN2UwYzBiNGE3MGI3YWQwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CT0dcPlfwUAoQVF9jWmGL36X6LodKfzhVmrvpGGBQpM">

是的 zeabur取消了永久免费的方案

**Comment by zhaoyanxue666** [comment]
> 部署到公网，提供ip端口秘钥，我远程调用一下

大佬能不能试一下我的，http://124.71.151.104:7077，没有设置密钥

**Comment by deanxv** [comment]
> http://124.71.151.104:7077

已请求通过 问题为"你好，现在是北京时间几点。"

**Comment by GoTop** [comment]
> > > 部署到公网，提供ip端口秘钥，我远程调用一下
> > 
> > 
> > 好的，感谢～
> > zeabur.com现在好像不能免费部署docker了？提示我需要付费才能启动docker
> > <img alt="截屏2024-02-25 23 21 11" width="372" src="https://private-user-images.githubusercontent.com/1784319/307602112-ebcd90c2-1ad7-40ec-b4b1-c6f6e4fe34da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzQ4MTAsIm5iZiI6MTcwODg3NDUxMCwicGF0aCI6Ii8xNzg0MzE5LzMwNzYwMjExMi1lYmNkOTBjMi0xYWQ3LTQwZWMtYjRiMS1jNmY2ZTRmZTM0ZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjVUMTUyMTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmFiMmFjY2Y3OWRmYTUyNDM1ZTA1N2UxNjZmNDgxMTNlZmM2ODMxZDc3MzRkY2EwN2UwYzBiNGE3MGI3YWQwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CT0dcPlfwUAoQVF9jWmGL36X6LodKfzhVmrvpGGBQpM">
> 
> 是的 zeabur取消了永久免费的方案

那还有其他免费的docker服务么？

**Comment by zhaoyanxue666** [comment]
> > http://124.71.151.104:7077
> 
> 已请求通过 问题为"你好，现在是北京时间几点。"

好的谢谢，我用微信机器人调用出问题，可能是机器人设置的原因，感谢您抽空调试

**Comment by GoTop** [comment]
> > > > > 部署到公网，提供ip端口秘钥，我远程调用一下
> > > > 
> > > > 
> > > > 好的，感谢～
> > > > zeabur.com现在好像不能免费部署docker了？提示我需要付费才能启动docker
> > > > <img alt="截屏2024-02-25 23 21 11" width="372" src="https://private-user-images.githubusercontent.com/1784319/307602112-ebcd90c2-1ad7-40ec-b4b1-c6f6e4fe34da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzQ4MTAsIm5iZiI6MTcwODg3NDUxMCwicGF0aCI6Ii8xNzg0MzE5LzMwNzYwMjExMi1lYmNkOTBjMi0xYWQ3LTQwZWMtYjRiMS1jNmY2ZTRmZTM0ZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjVUMTUyMTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmFiMmFjY2Y3OWRmYTUyNDM1ZTA1N2UxNjZmNDgxMTNlZmM2ODMxZDc3MzRkY2EwN2UwYzBiNGE3MGI3YWQwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CT0dcPlfwUAoQVF9jWmGL36X6LodKfzhVmrvpGGBQpM">
> > > 
> > > 
> > > 是的 zeabur取消了永久免费的方案
> > 
> > 
> > 那还有其他免费的docker服务么？
> 
> 没有

我在docker-compose.yml中删除掉 - PROXY_SECRET=1,2 这一行，修改bot_config.json文件名为bot_config.json-2，再启动compose，还是一样的错误提示。

不设置PROXY_SECRET应该就不检测验证了吧？还提示"authorization(proxy-secret)校验失败"会是什么原因呢？

**Comment by deanxv** [comment]
不设置PROXY_SECRET就不要传authorization请求头

**Comment by GoTop** [comment]
> 不设置PROXY_SECRET就不要传authorization请求头

在header中删掉了authorization，问题依旧，这是所有header里的设置：
<img width="578" alt="截屏2024-02-25 23 44 58" src="https://github.com/deanxv/coze-discord-proxy/assets/1784319/cbeaceba-b8b9-426e-9d14-08314626ef91">

**Comment by zhaoyanxue666** [comment]
> > http://124.71.151.104:7077
> 
> 已请求通过 问题为"你好，现在是北京时间几点。"
大佬，我加入one-api的时候依然出现和楼主同样的问题，我的PROXY_SECRET设置成han1314，麻烦您再看看？
version: '3.4'

services:
  coze-discord-proxy:
    image: deanxv/coze-discord-proxy:latest
    container_name: coze-discord-proxy
    restart: always
    ports:
      - "7077:7077"
    volumes:
      - ./data:/app/coze-discord-proxy/data
    environment:
      - USER_AUTHORIZATION=MTA4NzY1MTUxMzMzNTMwMDA5Ng.GYhFc8.rx7FTH2rtxszhefDIWuwJ93jWwVNlJkdMZApag
      - BOT_TOKEN=MTIwMDQxMzM2OTcwMjgxMzcxNg.GsJDXl.zdW724f-1_xj4yIQuAqu6tlsSPMV3t8ng6qL34  # 
      - GUILD_ID=1188140811477594252  # 必须修改为两个机器人所在的服务器ID
      - COZE_BOT_ID=1188141117091352576  # 必须修改为由coze托管的机器人ID
      - CHANNEL_ID=1188140811477594257  # 默认频道-(目前版本下该参数仅用来活跃机器人)
      - PROXY_SECRET=han1314  # [可选]接口密钥-修改此行为请求头校验的值(多个请以,分隔)
      - TZ=Asia/Shanghai


<img width="1186" alt="image" src="https://github.com/deanxv/coze-discord-proxy/assets/39113888/def65fb0-0e15-4ee4-a0c2-1604b8910ff7">

**Comment by deanxv** [comment]
> > > http://124.71.151.104:7077
> > 
> > 
> > 已请求通过 问题为"你好，现在是北京时间几点。"
> > 大佬，我加入one-api的时候依然出现和楼主同样的问题，我的PROXY_SECRET设置成han1314，麻烦您再看看？
> > version: '3.4' 版本：'3.4'
> 
> services: 服务 coze-discord-proxy: coze-discord-proxy： image: deanxv/coze-discord-proxy:latest图像：deanxv/coze-discord-proxy:latest container_name: coze-discord-proxy容器名称：coze-discord-proxy restart: always 始终重启 ports: 端口 - "7077:7077" 7077:7077 volumes: 卷： - ./data:/app/coze-discord-proxy/data./data:/app/coze-discord-proxy/data environment: 环境 - USER_AUTHORIZATION=MTA4NzY1MTUxMzMzNTMwMDA5Ng.GYhFc8.rx7FTH2rtxszhefDIWuwJ93jWwVNlJkdMZApag用户授权=1087651513335300096.GYhFc8.rx7FTH2rtxszhefDIWuwJ93jWwVNlJkdMZApag - BOT_TOKEN=MTIwMDQxMzM2OTcwMjgxMzcxNg.GsJDXl.zdW724f-1_xj4yIQuAqu6tlsSPMV3t8ng6qL34 #BOT_TOKEN=MTIwMDQxMzM2OTcwMjgxMzcxNg.GsJDXl.zdW724f-1_xj4yIQuAqu6tlsSPMV3t8ng6qL34 # - GUILD_ID=1188140811477594252 # 必须修改为两个机器人所在的服务器ID - COZE_BOT_ID=1188141117091352576 # 必须修改为由coze托管的机器人ID - CHANNEL_ID=1188140811477594257 # 默认频道-(目前版本下该参数仅用来活跃机器人) - PROXY_SECRET=han1314 # [可选]接口密钥-修改此行为请求头校验的值(多个请以,分隔) - TZ=Asia/Shanghai - TZ=亚洲/上海
> 
> <img alt="image" width="1186" src="https://private-user-images.githubusercontent.com/39113888/307604308-def65fb0-0e15-4ee4-a0c2-1604b8910ff7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzcxNzMsIm5iZiI6MTcwODg3Njg3MywicGF0aCI6Ii8zOTExMzg4OC8zMDc2MDQzMDgtZGVmNjVmYjAtMGUxNS00ZWU0LWEwYzItMTYwNGI4OTEwZmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDE2MDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZWY3NGJhOGIwYThkYmIwZDhkZGVmZjNlMDM0ZTMxMGVhYWEyOTgwMmUyMTdiNmU0ZjBkOTY4MjMyOGFjMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wgoKhLzhNmEnyxq05-wRUd7AssDARd3cuszjbOTqZgA">

删掉所有注释 重新部署，自己用postman调试proxy接口，通了之后再自己调试oneapi的接口，不是bug的话，我不能帮你一步一步调试，我也没有时间

**Comment by zhaoyanxue666** [comment]
> > > > http://124.71.151.104:7077
> > > 
> > > 
> > > 已请求通过 问题为"你好，现在是北京时间几点。"
> > > 大佬，我加入one-api的时候依然出现和楼主同样的问题，我的PROXY_SECRET设置成han1314，麻烦您再看看？
> > > version: '3.4' 版本：'3.4'
> > 
> > 
> > services: 服务 coze-discord-proxy: coze-discord-proxy： image: deanxv/coze-discord-proxy:latest图像：deanxv/coze-discord-proxy:latest container_name: coze-discord-proxy容器名称：coze-discord-proxy restart: always 始终重启 ports: 端口 - "7077:7077" 7077:7077 volumes: 卷： - ./data:/app/coze-discord-proxy/data./data:/app/coze-discord-proxy/data environment: 环境 - USER_AUTHORIZATION=MTA4NzY1MTUxMzMzNTMwMDA5Ng.GYhFc8.rx7FTH2rtxszhefDIWuwJ93jWwVNlJkdMZApag用户授权=1087651513335300096.GYhFc8.rx7FTH2rtxszhefDIWuwJ93jWwVNlJkdMZApag - BOT_TOKEN=MTIwMDQxMzM2OTcwMjgxMzcxNg.GsJDXl.zdW724f-1_xj4yIQuAqu6tlsSPMV3t8ng6qL34 #BOT_TOKEN=MTIwMDQxMzM2OTcwMjgxMzcxNg.GsJDXl.zdW724f-1_xj4yIQuAqu6tlsSPMV3t8ng6qL34 # - GUILD_ID=1188140811477594252 # 必须修改为两个机器人所在的服务器ID - COZE_BOT_ID=1188141117091352576 # 必须修改为由coze托管的机器人ID - CHANNEL_ID=1188140811477594257 # 默认频道-(目前版本下该参数仅用来活跃机器人) - PROXY_SECRET=han1314 # [可选]接口密钥-修改此行为请求头校验的值(多个请以,分隔) - TZ=Asia/Shanghai - TZ=亚洲/上海
> > <img alt="image" width="1186" src="https://private-user-images.githubusercontent.com/39113888/307604308-def65fb0-0e15-4ee4-a0c2-1604b8910ff7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzcxNzMsIm5iZiI6MTcwODg3Njg3MywicGF0aCI6Ii8zOTExMzg4OC8zMDc2MDQzMDgtZGVmNjVmYjAtMGUxNS00ZWU0LWEwYzItMTYwNGI4OTEwZmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDE2MDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZWY3NGJhOGIwYThkYmIwZDhkZGVmZjNlMDM0ZTMxMGVhYWEyOTgwMmUyMTdiNmU0ZjBkOTY4MjMyOGFjMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wgoKhLzhNmEnyxq05-wRUd7AssDARd3cuszjbOTqZgA">
> 
> 删掉所有注释 重新部署，自己用postman调试proxy接口，通了之后再自己调试oneapi的接口，不是bug的话，我不能帮你一步一步调试，我也没有时间

好的，谢谢楼主，麻烦了

**Comment by deanxv** [comment]
> > 不设置PROXY_SECRET就不要传authorization请求头
> 
> 在header中删掉了authorization，问题依旧，这是所有header里的设置： <img alt="截屏2024-02-25 23 44 58" width="578" src="https://private-user-images.githubusercontent.com/1784319/307603658-cbeaceba-b8b9-426e-9d14-08314626ef91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzcxNzMsIm5iZiI6MTcwODg3Njg3MywicGF0aCI6Ii8xNzg0MzE5LzMwNzYwMzY1OC1jYmVhY2ViYS1iOGI5LTQyNmUtOWQxNC0wODMxNDYyNmVmOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjVUMTYwMTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmNkNWNmM2Y4YjhlMTg4ZGJmM2I1ODY5ZmMxZDZiYWFhMjk3MTg3MThiMThmZTA2MzdjOTBmYjZmZDQzNGVmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0YwWojQ2YWOdp9e9XuvmNkCHvrSbtibHkSM5VYLGCx0">


光看这里看不出问题，提供公网部署的ip端口密钥。没有的话自己调试研究下。

**Comment by GoTop** [comment]
> > > 不设置PROXY_SECRET就不要传authorization请求头
> > 
> > 
> > 在header中删掉了authorization，问题依旧，这是所有header里的设置： <img alt="截屏2024-02-25 23 44 58" width="578" src="https://private-user-images.githubusercontent.com/1784319/307603658-cbeaceba-b8b9-426e-9d14-08314626ef91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzcxNzMsIm5iZiI6MTcwODg3Njg3MywicGF0aCI6Ii8xNzg0MzE5LzMwNzYwMzY1OC1jYmVhY2ViYS1iOGI5LTQyNmUtOWQxNC0wODMxNDYyNmVmOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjVUMTYwMTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmNkNWNmM2Y4YjhlMTg4ZGJmM2I1ODY5ZmMxZDZiYWFhMjk3MTg3MThiMThmZTA2MzdjOTBmYjZmZDQzNGVmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0YwWojQ2YWOdp9e9XuvmNkCHvrSbtibHkSM5VYLGCx0">
> 
> 光看这里看不出问题，提供公网部署的ip端口密钥。没有的话自己调试研究下。

零点的时候提示：
2024-02-26 00:00:01 coze-discord-proxy  | [SYS] 2024/02/26 - 00:00:01 | ChannelId{1211180670878093366} BotId{1211180925560561725} 活跃机器人任务消息发送成功! 

<img width="432" alt="截屏2024-02-26 00 04 50" src="https://github.com/deanxv/coze-discord-proxy/assets/1784319/30c78961-f705-4f59-a2b8-0cf28580d696">

看来token设置应该是没问题的吧

**Comment by deanxv** [comment]
> > > > 不设置PROXY_SECRET就不要传authorization请求头
> > > 
> > > 
> > > 在header中删掉了authorization，问题依旧，这是所有header里的设置：
> > 
> > 
> > 光看这里看不出问题，提供公网部署的ip端口密钥。没有的话自己调试研究下。
> 
> 零点的时候提示： 2024-02-26 00:00:01 coze-discord-proxy | [SYS] 2024/02/26 - 00:00:01 | ChannelId{1211180670878093366} BotId{1211180925560561725} 活跃机器人任务消息发送成功!
> 
> <img alt="截屏2024-02-26 00 04 50" width="432" src="https://private-user-images.githubusercontent.com/1784319/307605007-30c78961-f705-4f59-a2b8-0cf28580d696.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4Nzc1NDAsIm5iZiI6MTcwODg3NzI0MCwicGF0aCI6Ii8xNzg0MzE5LzMwNzYwNTAwNy0zMGM3ODk2MS1mNzA1LTRmNTktYTJiOC0wY2YyODU4MGQ2OTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjVUMTYwNzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzAwMDM4ZmJlMjEyNTA4YjFhNTUxMWY2NmMwMzkzNGYyZjQyN2QxM2UwMWQ4YmU2OWZlNjFjNWE0YzI5OGU0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kEZ30mF_AnD6wfFks5pJxc9kaTCnwNWAa6zOH6VVx6Q">
> 看来token设置应该是没问题的吧

是的

**Comment by zhaoyanxue666** [comment]
我同样的报错解决了，按照文档中在coze 设置-高级设置开启开发者模式，楼主可以试试

**Comment by GoTop** [comment]
> 我同样的报错解决了，按照文档中在coze 设置-高级设置开启开发者模式，楼主可以试试

请问是coze开始开发者模式，还是 discord开启开发者模式？

**Comment by GoTop** [comment]
解决了，原来是我的docker的yml文件里的第一行，少了一个单引号

https://private-user-images.githubusercontent.com/1784319/307598749-c78bcc23-63ff-421f-8f24-6516b35f98ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDAxNDMsIm5iZiI6MTcwODkzOTg0MywicGF0aCI6Ii8xNzg0MzE5LzMwNzU5ODc0OS1jNzhiY2MyMy02M2ZmLTQyMWYtOGYyNC02NTE2YjM1Zjk4Y2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjZUMDkzMDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDcwNTU4YzQyZDFiMDNmZDgxOTA2NTMzN2QxNDI2ZGQ0MjYyMTVmNThkMTRhNzdkMmI2MzUzM2Y1ZTRlNGQwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yqQWOFHlazPL2e5TL4lyr0qSW3cb-wQIXWVoucnMNiw
