### ISSUE TITLE
在discord对话框中和机器人聊天有回复，但是在NextChat或者post时报以下错

### ISSUE THREAD

**Issue by HIT-ZY** [deanxv/coze-discord-proxy#94]
**例行检查**

+ [ ✔] 我已确认目前没有类似 issue
+ [ ✔] 我已确认我已升级到最新版本
+ [ ✔] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ✔] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
{
  "error": {
    "message": "error sending message",
    "type": "invalid_request_error",
    "param": "",
    "code": "discord_request_err"
  }
}

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/deanxv/coze-discord-proxy/assets/102421741/2520b5be-c4a6-4da5-9027-81234f4cd1d3)
![image](https://github.com/deanxv/coze-discord-proxy/assets/102421741/5a4dee82-474a-4f3f-99e5-b8ac4a4482ec)
。

**Comment by HIT-ZY** [comment]
docker报错信息如下：
![image](https://github.com/deanxv/coze-discord-proxy/assets/102421741/6ad91592-a00d-40da-ad96-0c7674d8fecf)

**Comment by deanxv** [comment]
Discord中的Bot没有配置Admin权限

**Comment by HIT-ZY** [comment]
请问是这三个吗，这三个按钮是打开的
![image](https://github.com/deanxv/coze-discord-proxy/assets/102421741/29331799-6c78-46fd-9216-7d726c6942b3)

**Comment by deanxv** [comment]
> 请问是这三个吗，这三个按钮是打开的
> 
> ![image](https://github.com/deanxv/coze-discord-proxy/assets/102421741/29331799-6c78-46fd-9216-7d726c6942b3)
> 
> 

不止，要在这里配置admin权限重新拉入服务器
![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/3fecd6c8-9ce9-4885-acf3-0b015b7d4589)

**Comment by HIT-ZY** [comment]
解决了，谢谢大佬不吝赐教
