### ISSUE TITLE
使用api提问太多次后，返回错误：Something wrong occurs, please retry. If the error persists, please contact the support team，请问有什么方法增加提问次数么？

### ISSUE THREAD

**Issue by GoTop** [deanxv/coze-discord-proxy#95]
使用api提问太多次后，coze上使用 GPT4 tubor 128k模型的bot就会返回错误：Something wrong occurs, please retry. If the error persists, please contact the support team.

更换为同个coze账号下的另一个GPT4 tubor 128k模型的bot，也返回一样的错误。估计同一个coze账号使用GPT4 tubor 128k模型的bot，共享相同的提问次数或者token。

直接在discord对绑定coze的机器人提问，也返回同样的错误

要想提高提问次数，应该怎么解决呢？

**Comment by deanxv** [comment]
![image](https://github.com/deanxv/coze-discord-proxy/assets/57529708/40d75d81-4af6-4e90-aa20-85a1a9060cab)

**Comment by GoTop** [comment]
> ![image](https://private-user-images.githubusercontent.com/57529708/307757013-40d75d81-4af6-4e90-aa20-85a1a9060cab.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDkxODcsIm5iZiI6MTcwODk0ODg4NywicGF0aCI6Ii81NzUyOTcwOC8zMDc3NTcwMTMtNDBkNzVkODEtNGFmNi00ZTkwLWFhMjAtODVhMWE5MDYwY2FiLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxMjAxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmQ5ZTYwZWQxYjBhMzg1ODI4ZmY0Y2FlODY1MjUyZmRiMzBjYmM3MjJhNjljNTY4ODA1OGI3NGRhMTg3OGE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UPg__mbcXPiCtPiUwi5OEHLhoqF4yG0as3WYABX0zLU)

我这个其实是discord的限制？我还以为是coze的限制

**Comment by GoTop** [comment]
> > 我这个其实是discord的限制？我还以为是coze的限制
> 
> 是coze的限制，导致了发布的discord的bot也有限制。

哦，那就需要注册多几个discord账号，并邀请进同一个服务器，获取新账号的Authorization后输入环境变量USER_AUTHORIZATION中，这样就可以增加次数限制了吧

**Comment by deanxv** [comment]
> > > 我这个其实是discord的限制？我还以为是coze的限制
> 
> > 
> 
> > 是coze的限制，导致了发布的discord的bot也有限制。
> 
> 
> 
> 哦，那就需要注册多几个discord账号，并邀请进同一个服务器，获取新账号的Authorization后输入环境变量USER_AUTHORIZATION中，这样就可以增加次数限制了吧

是的
