### ISSUE TITLE
本项目返回的response和openai返回的response格式不一样

### ISSUE THREAD

**Issue by HIT-ZY** [deanxv/coze-discord-proxy#96]
**例行检查**

+ [✔ ] 我已确认目前没有类似 issue
+ [✔ ] 我已确认我已升级到最新版本
+ [✔ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [✔ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
以GPT4V为例：
本项目返回的response如下：
![image](https://github.com/deanxv/coze-discord-proxy/assets/102421741/bd130060-e5ef-43b9-ae44-ef32716c21f2)
本项目的所有回复内容都在"choices"，"message"，"content"返回
标准的openai返回应该是流式的在"choices"，"message"，"delta"里面返回
这导致了本项目和openai的接口对不齐
**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
如果这个项目没有和openai对齐的话你觉得这个项目会有这么多人用吗

**Comment by deanxv** [comment]
> 请问怎么使用流式输出

与openai的接口一致,请求参数中 "stream":true
