### ISSUE TITLE
删除频道错误，好像频道删不了

### ISSUE THREAD

**Issue by MisZang** [deanxv/coze-discord-proxy#97]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [x] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
一直删不了频道，这是服务器日志：2月26日 下午09：36：56[错误] 2024/02/26 - 21：36：56 | 未知 | 删除频道时异常 HTTP 404 Not Found， {“message”： “Unknown Channel”， “code”： 10003} 
**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by deanxv** [comment]
这个报错的出现原因是因为某些异常原因频道已经被提前删除了，备用删除方案未找到该频道，并非没有删掉频道。

**Comment by MisZang** [comment]
> 这个报错的出现原因是因为某些异常原因频道已经被提前删除了，备用删除方案未找到该频道，并非没有删掉频道。

谢谢你的回复，但是监听的机器人2不返回监听到的机器人1的消息是怎么回事呢？或者说机器人2没有监听到机器人1发的消息

**Comment by MisZang** [comment]
> 谢谢你的回复，但是监听的机器人2不返回监听到的机器人1的消息是怎么回事呢？或者说机器人2没有监听到机器人1发的消息

谢谢你的回复，但是监听的机器人2不返回监听到的机器人1的消息是怎么回事呢？或者说机器人2没有监听到机器人1发的消息，我有些疑惑，因为只有nextgpt返回了消息，但是其他应用使用的时候会显示API调用错误什么的，我在用WeChat-on-bot这个项目的时候，之前还能正常的回复，但是今天就不行了，我部署在render上

**Comment by deanxv** [comment]
> > 这个报错的出现原因是因为某些异常原因频道已经被提前删除了，备用删除方案未找到该频道，并非没有删掉频道。
> 
> 
> 
> 谢谢你的回复，但是监听的机器人2不返回监听到的机器人1的消息是怎么回事呢？或者说机器人2没有监听到机器人1发的消息

coze在上周把bot@其他bot的消息过滤掉了，所以4.0版本改成了以discord用户端发送消息，bot用来监听消息，所以你需要更新版本，并按照文档或者教程配置新的环境变量。

**Comment by MisZang** [comment]
> > > 这个报错的出现原因是因为某些异常原因频道已经被提前删除了，备用删除方案未找到该频道，并非没有删掉频道。
> > 
> > 
> > 谢谢你的回复，但是监听的机器人2不返回监听到的机器人1的消息是怎么回事呢？或者说机器人2没有监听到机器人1发的消息
> 
> coze在上周把bot@其他bot的消息过滤掉了，所以4.0版本改成了以discord用户端发送消息，bot用来监听消息，所以你需要更新版本，并按照文档或者教程配置新的环境变量。

谢谢你的回复，我也许使用的就是最新的docker镜像，我在render直接拉取镜像部署的，我还是不太理解所以来反馈一下😥

**Comment by deanxv** [comment]
> > > > 这个报错的出现原因是因为某些异常原因频道已经被提前删除了，备用删除方案未找到该频道，并非没有删掉频道。
> 
> > > 
> 
> > > 
> 
> > > 谢谢你的回复，但是监听的机器人2不返回监听到的机器人1的消息是怎么回事呢？或者说机器人2没有监听到机器人1发的消息
> 
> > 
> 
> > coze在上周把bot@其他bot的消息过滤掉了，所以4.0版本改成了以discord用户端发送消息，bot用来监听消息，所以你需要更新版本，并按照文档或者教程配置新的环境变量。
> 
> 
> 
> 谢谢你的回复，我也许使用的就是最新的docker镜像，我在render直接拉取镜像部署的，我还是不太理解所以来反馈一下😥

如果你发起请求后仍然是bot发送的消息，并没有配置user_auth等环境变量，请重新拉取镜像，部署后的日志中有版本号，最新版本号为4.2.0。
