### ISSUE TITLE
discord的bot接收到的信息里，有"role"，"user"，”content"这些字符串

### ISSUE THREAD

**Issue by GoTop** [deanxv/coze-discord-proxy#98]
我在coze新建了一个翻译英文的bot，使用以下形式发送post数据
```
"request": {
         "url": "http://localhost:7077/v1/chat/completions",
        "method": "POST",
        "headers": {
            "User-Agent": "Mozilla/4.0 (compatible; MSIE 5.5; Windows NT)",
            "Content-Type": "application/json",
            "Authorization": "2"
        },
        "data": {
            "model": "gpt4",
            "temperature": 0,
            "messages":  [{"role": "user","content": "Hello World!"}]
        }
```

在discord里看到对话记录，我发送给discord的bot的是
```[{"role":"user","content":"Hello World!"}] ```

这样会导致coze的bot翻译长文本的时候，有时会把前面的role，user也会被当成英文，进行翻译

为什么会出现这种情况呢？

**Comment by deanxv** [comment]
尝试缩短文本至2000以内的字符，超长文本下可能会出现GPT4对Json的理解不正确。

但如果仅仅是想单次对话翻译文本，建议配置以下环境变量:

ALL_DIALOG_RECORD_ENABLE:0

配置后再尝试超长文本翻译，应该不会出现问题。

(刚更新了4.2.0版本，改动了多机器人的配置，model改为了数组格式，请修改完json再更新。)

**Comment by GoTop** [comment]
> model

已更新4.2.0，设置ALL_DIALOG_RECORD_ENABLE=0后就正常了。

如果要使用ALL_DIALOG_RECORD_ENABLE=1，可以在prompt指定：
现在请按照上面的要求从第一行开始翻译以下内容为简体中文：
``` 
content
```
