### ISSUE TITLE
lobechat从discord拉图片过来的成功率很低，要试很多次才成功一次，但discord那能正常生图出来。

### ISSUE THREAD

**Issue by GforPG** [deanxv/coze-discord-proxy#99]
**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
如果没有的话,请删除此节。

**Comment by GforPG** [comment]
之前用nextchat试过，也差不多这样，经常失败，不知道为啥

**Comment by deanxv** [comment]
报错还是无响应，有报错提供报错截图，提供服务版本号，提供discord对话记录

**Comment by GforPG** [comment]
![QQ图片20240227212926](https://github.com/deanxv/coze-discord-proxy/assets/138672705/1fbf7586-8a26-4547-bbcc-9e5d8c70450e)
![QQ图片20240227213023](https://github.com/deanxv/coze-discord-proxy/assets/138672705/16defe8a-14c1-45b8-b276-04585ae90520)

**Comment by GforPG** [comment]
版本号是从3到4，到最新的，都这样，多试几次它就能出来图。

**Comment by deanxv** [comment]
504报错非项目内的错误，这个错误是响应时间超过了对话面板或者vercel的超时时间，请查找对话面板相关配置。

如果想验证是否为该cdp项目的异常，使用postman调用调试接口。

**Comment by GforPG** [comment]
可否针对lobechat做个解决这个问题的教程（比如如何设置超时时间）啊大佬，毕竟lobechat可以用vision，感觉是最适合这个项目的对话面板了。

**Comment by deanxv** [comment]
> 可否针对lobechat做个解决这个问题的教程（比如如何设置超时时间）啊大佬，毕竟lobechat可以用vision，感觉是最适合这个项目的对话面板了。

这个你要去lobeChat的文档中去查看了

**Comment by CellLz** [comment]
> 504报错非项目内的错误，这个错误是响应时间超过了对话面板或者vercel的超时时间，请查找对话面板相关配置。
> 
> 如果想验证是否为该cdp项目的异常，使用postman调用调试接口。

如果504报错是因为vercel超时造成的，那我在自己的服务器上部署chat-next-web是不是就有可能解决这个问题了呢？谢谢！
